### ISSUE TITLE
Authentication - login page

### ISSUE THREAD

**Issue by Trsak** [citizenfx/txAdmin#1]
First I want to say: Really nice project. Will definetly contribute to this, web control panel is what we needed.

But whole panel should have some kind of login screen with admin auth. Right now, anyone can see admin log and all the information should just be hidden to unauthorized people.

**Comment by tabarra** [comment]
**Fully agree.**  
I'll look into some simple library to help me do that, otherwise I might implement it manually.  
Out current RAM footprint is 43~60MB, and I personally haven't tested if adding a few new libs will actually increase the footprint that much.

**Comment by tabarra** [comment]
closed by #8406cde

**Comment by tabarra** [comment]
Closed by 8406cde0bec929423551d4b0533b82261b52ad0b
