### ISSUE TITLE
Error starting monitor

### ISSUE THREAD

**Issue by tr1ckz** [citizenfx/txAdmin#10]
After updating to v1 i get a monitoring error

[txAdmin:webConsole] ::Started
[txAdmin] Error starting 'Monitor' module. Make sure you executed 'npm install'.
[txAdmin] >>Stopping txAdmin
gta@ubuntu:~/txAdmin$

**Comment by tr1ckz** [comment]
fixed wit v1.0.1, <3

**Comment by tr1ckz** [comment]
this thing ROCKS

**Comment by tabarra** [comment]
A little fuck up from my part.
Fixed in v1.0.1.
