### ISSUE TITLE
[FEATURE]: Editable restart alert message

### ISSUE THREAD

**Issue by ChickenDipper1** [citizenfx/txAdmin#1009]
### Scope

In-Game Menu

### Feature Description

It would be a nice feature to be able to edit the server restart message.
I know we can disable it and use the event to trigger our own but when trying to keep things simple and use TX as much as possible this would be a great addition/modification.

### Use Case

Enter a custom server restart message using TX

### Proposed Solution

Allow restart message to be editable without modifying TX code.

**Comment by tabarra** [comment]
If all you wanna do is change text instead of behavior, I recommend you setting up a custom locale file:  
https://github.com/tabarra/txAdmin/blob/master/docs/translation.md#custom-locales

**Comment by ChickenDipper1** [comment]
Damm you are fast! 
I will do just that. Perfect, thanks very much :)
