### ISSUE TITLE
[FEATURE]: Function to allow bans to be passed to TXAdmin from another script

### ISSUE THREAD

**Issue by ChickenDipper1** [citizenfx/txAdmin#1015]
### Scope

Developer API

### Feature Description

It would be very handy to have a function or event that can be triggered passing the required player info to it, that will add a player ban to txadmin.

I am looking to implement auto banning using my anti cheat script if certain actions are made but would like to keep ban centralised in txadmin.

### Use Case

Keep a single ban list based in txadmin

### Proposed Solution

A function or event to allow addig a ban to txadmin from another script.

**Comment by tabarra** [comment]
Please refer to #442

**Comment by ChickenDipper1** [comment]
Thanks will do
