### ISSUE TITLE
[Suggestion] Server up/prevent joining

### ISSUE THREAD

**Issue by JnKTechstuff** [citizenfx/txAdmin#104]
It would be nice if we could get the following for features:

- Defer connections to server until full server authentication. Prevents issues with people joining too early and jacking a database because their stuff errors out.

- A manual restart timer built in. Like automatic restarts with announcements and everything being automated. The option to do it manually instead of going into settings and setting a scheduled restart like 5 minutes from now.

- Announcement in discord for when the server is up. Like: server is starting, then a console detection for sending heartbeat and then another discord message saying it's up. Helps again with suggestion 1.

Let me know what you think.

**Comment by xrtw** [comment]
Also would be great, if 1 minute left till server restart, everybody get kicked out from server and if its ~5min before restart, you can't join into it

**Comment by NoobKeksTV** [comment]
The "Gets restarted in2 mesasge is available for the discord bot.  Autorestart function alredy exists. People wont get kicke 1 min before restart rather right before the restart.

**Comment by JnKTechstuff** [comment]
> The "Gets restarted in2 mesasge is available for the discord bot. Autorestart function alredy exists. People wont get kicke 1 min before restart rather right before the restart.

You really half ass read my suggestion...

**Comment by jooaooalmeida** [comment]
> > The "Gets restarted in2 mesasge is available for the discord bot. Autorestart function alredy exists. People wont get kicke 1 min before restart rather right before the restart.
> 
> You really half ass read my suggestion...

Idk if u realize but zocker was talking to the dude suggesting auto kick before restart, still like your suggestions +1

**Comment by FlawwsX** [comment]
> Defer connections to server until full server authentication. Prevents issues with people joining too early and jacking a database because their stuff errors out.

Pretty sure you can start on the Lua side now.

**Comment by JnKTechstuff** [comment]
I am going to close this as the feature is in fact a thing in FiveM if you want to know how here it is:
![image](https://user-images.githubusercontent.com/7122547/87644688-6f621f00-c71a-11ea-9540-fdc31e0dc55d.png)
