### ISSUE TITLE
No resources, console says No such command txaReportResources

### ISSUE THREAD

**Issue by ShaggyRogersTBS** [citizenfx/txAdmin#108]
So, i installed the newest artifacts 2345 started everything and then when i go to start my server everything starts like it should and when i go to the resources tab it says the message "Couldnt load them". I went to the "Live console" tab only to discover No such command txaReportResources
and No such command txaBroadcast. Can you please help me somehow?

**Comment by tabarra** [comment]
I'm 99% sure you tried to install txAdmin and copied the old txAdminClient folder to your resources.  
Just read the README again.

**Comment by tabarra** [comment]
BTW, if you are on linux, open live console and type `ensure monitor` and see if it works.  
Please report back if it works or not with an screenshot of the diagnostics page, I just got another report about this issue that seems to be fxserver not automatically starting the `monitor` resource.

**Comment by ShaggyRogersTBS** [comment]
ok

**Comment by ShaggyRogersTBS** [comment]
it works just fine now, thanks

**Comment by Fabian-Luque** [comment]
you can add `start monitor` in your server.cfg and it´s works

**Comment by ShanuDey** [comment]
I found commenting `set con_disableNonTTYReads 1` line in server.cfg fixed the issue for me.
