### ISSUE TITLE
fatal: Remote branch conversion not found in upstream origin

### ISSUE THREAD

**Issue by joshllan26** [citizenfx/txAdmin#112]
So I'm running on an old fxserver build (there is reason for this, and its not just because I cba to update), and I remember a while back with the V1.0 of txAdmin I could install it and be done, then I found it had been removed for a while, now I find that its integrated with the new server build, and think "Ok, can I use it for my old build?". Then I find this near the bottom of the github page : https://github.com/tabarra/txAdmin/blob/master/docs/building.md

So I follow the steps and then the issue I get is as follows: `fatal: Remote branch conversion not found in upstream origin` 

Any idea why this is happening and how it can be fixed?

**Comment by tabarra** [comment]
This is the building instructions for the v2.  
What you want is the legacy branch, but unless you fix the `run.cmd` thing, it wont work.  
  
https://github.com/tabarra/txAdmin/tree/legacy
