### ISSUE TITLE
Builds 2315 and up, Problems with Discord Bot

### ISSUE THREAD

**Issue by Fallen4** [citizenfx/txAdmin#114]
![bugged](https://user-images.githubusercontent.com/64283671/80251671-00f25100-8644-11ea-8011-caa03fa74f7f.png)
![bugged2](https://user-images.githubusercontent.com/64283671/80251893-59295300-8644-11ea-8ace-7998f626a0f0.png)

Unsure if this is an issue on my end and couldn't locate the FiveM forum for this anymore but getting these 2 issues with the bot when on the most updated (2381) build. Build 2315 works without issues. Unsure if its just on my end. If so go ahead and close this issue.

**Comment by tabarra** [comment]
Solved in v2.3.1. 
Please update to the latest release.
