### ISSUE TITLE
Failed to read CFG File with error: File doesn't exist or its unreadable.

### ISSUE THREAD

**Issue by victjd** [citizenfx/txAdmin#115]
It keep ``saying Failed to read CFG File with error: File doesn't exist or its unreadable.`` even tho i have a server.cfg

**Comment by tabarra** [comment]
Then you inserted the wrong path or the user running txAdmin doesn't have permissions to read that file.

**Comment by bbabou** [comment]
Same issue but i am admin and it's the correct path

**Comment by tabarra** [comment]
> Same issue but i am admin and it's the correct path

Then the answer is the same: you have the wrong path
