### ISSUE TITLE
vRP framework 0.5 spamming error on the Server Console

### ISSUE THREAD

**Issue by MiguelNdeCarvalho** [citizenfx/txAdmin#116]
Hey,

vRP framework 0.5 is spamming this error on the Server Console:

> fn (@vrp/lib/utils.lua:48)
SCRIPT ERROR: @vrp/lib/utils.lua:43: attempt to call a nil value (upvalue 'callback')
> fn (@vrp/lib/utils.lua:48)
SCRIPT ERROR: @vrp/lib/utils.lua:43: attempt to call a nil value (upvalue 'callback')

I don't know if it is something related to the txAdmin module, but I am reporting it to have some feedback from your side.
Really thanks for your great job on this panel.

Thanks,
Miguel de Carvalho

**Comment by tabarra** [comment]
txAdmin doesn't interact with any resources, and doesn't change any fxserver parameters.  
  
On a side note, why are you still using vrp 0.5 since vrp 2.0 was released more than a year ago?

**Comment by MiguelNdeCarvalho** [comment]
Hey, 
Really thanks for your help, I wans't sure about it, that's why I asked here.
Thanks,
Miguel de Carvalho

**Comment by MiguelNdeCarvalho** [comment]
> On a side note, why are you still using vrp 0.5 since vrp 2.0 was released more than a year ago?

Somehow I didn't see the 2nd part of your quote. Basically I am just setting up the server on a communnity. He said me that there aren't many resources for vRP2.0
