### ISSUE TITLE
txAdmin stops after i exit the SSH

### ISSUE THREAD

**Issue by ShaggyRogersTBS** [citizenfx/txAdmin#117]
So i installed 2.4.0 and it works just fine until i exit from the ftp client. Then the txAdmin(the FXServer) doesnt. Leaving the server without admin panel until the server is restarted from the terminal.
Maybe it's an option i didn't see.

**Comment by tabarra** [comment]
My dude... that's just how ssh/linux works hahahahaha.  
Do a quick google search on how to use `screen` or `tmux`.
