### ISSUE TITLE
Internal Error on main page

### ISSUE THREAD

**Issue by aprzymus** [citizenfx/txAdmin#119]
Hi. I started FXServer today, set up txAdmin and encountered a problem. All subpages work (console, settings etc.) except the main one. **Internal Error on: /** is displayed. I started Verbose mode to get the error out of the console, it displays: **[txAdmin Error] Cannot read property 'artifactsLink' of null**. What should I do now? 

Node version: 13.14.0
NPM version: 6.14.4
FXServer version: 2431 (master)

**Comment by tabarra** [comment]
This is due to an issue with the update checker error handler.  
Fix available in release v2.4.1.
