### ISSUE TITLE
Error trying to launch FXServer

### ISSUE THREAD

**Issue by CronoVendetta** [citizenfx/txAdmin#12]
(Counter: 11/15) HealthCheck request error: connect ECONNREFUSED 127.0.0.1:32528

my server.cfg contains 0.0.0.0:32528

**Comment by CronoVendetta** [comment]
[txAdmin:Monitor] (Counter: 3/15) HealthCheck request error: connect ECONNREFUSED 127.0.0.1:32528
[txAdmin:FXRunner] Setting up FXServer scripting environment variables.
server thread hitch warning: timer interval of 456 milliseconds
Stopping resource txAdminClient
Creating script environments for txAdminClient
[txAdminClient] Version 1.0.0 starting...
Started resource txAdminClient
[txAdmin:Monitor] (Counter: 4/15) HealthCheck request error: connect ECONNREFUSED 127.0.0.1:32528
[txAdmin:Monitor] (Counter: 5/15) HealthCheck request error: connect ECONNREFUSED 127.0.0.1:32528

**Comment by tabarra** [comment]
Can you provide us your server.cfg?  
(please remove the rcon password and post it to pastebin)

**Comment by CronoVendetta** [comment]
```c
set es_enableCustomData 1 
set mysql_connection_string "xxxxxxxxxxxxxxxxx" 
endpoint_add_tcp "0.0.0.0:32528" 
endpoint_add_udp "0.0.0.0:32528" 

sv_maxclients 32


# Only change the IP if you're using a server with multiple network interfaces, otherwise change the port only.

#Resources Starter inside file resources.cfg
exec resources.cfg

# This allows players to use scripthook-based plugins such as the legacy Lambda Menu.
# Set this to 1 to allow scripthook. Do note that this does _not_ guarantee players won't be able to use external plugins.
sv_scriptHookAllowed 1

rcon_password xxxxxxxxxxx

# A comma-separated list of tags for your server.
# For example:
# - sets tags "drifting, cars, racing"
# Or:
# - sets tags "roleplay, military, tanks"
sets tags "default"

# Set an optional server info and connecting banner image url.
# Size doesn't matter, any banner sized image will be fine.
#sets banner_detail "https://url.to/image.png"
#sets banner_connecting "https://url.to/image.png"

# Set your server's hostname
sv_hostname "^9[^1E^3S^1P^9] ^9| ^6La Frontera ^9| ^5Roleplay Server ^9| ^8NWL ^9| ^4Economía Real ^9| ^3Scripts propios y originales ^9| ^5Mapeado custom ^9| ^8Drogas ^6Mafias ^7Bandas ^9|"

# Nested configs!
#exec server_internal.cfg

# Loading a server icon (96x96 PNG file)
load_server_icon 96.png

# convars which can be used in scripts
set temp_convar "hey world!"

# Uncomment this line if you do not want your server to be listed in the server browser.
# Do not edit it if you *do* want your server listed.
sv_master1 ""

# Add system admins
add_ace group.admin command allow # allow all commands
add_ace group.admin command.quit deny # but don't allow quit
add_principal identifier.steam:110000100000000 group.admin # add the admin to the group

# Hide player endpoints in external log output.
sv_endpointprivacy true


sv_licenseKey "xxxxxxxxxxxxxxxxxxxxxxxxx"

onesync_enabled 0

#This is an official FiveM server hosted by ZAP-Hosting.com. You do not need to put a license key here.
restart sessionmanager
```

**Comment by tabarra** [comment]
Make sure `global.fxServerPort` is set to 32528 in your txAdmin json configuration file (eg server.json)

**Comment by CronoVendetta** [comment]
{
    "global": {
        "verbose": true,
        "publicIP": "xxxxxx" ,
        "serverName": "LaFronteraRP",
        "fxServerPort": 32528
    },

**Comment by tabarra** [comment]
To further investigate the problem, please execute:
`npm run config-tester server01.json`

**Comment by CronoVendetta** [comment]
i do it, 0 errors reported
But if i press start on web, get the message reported
[txAdmin:Monitor] (Counter: 3/15) HealthCheck request error: connect ECONNREFUSED 127.0.0.1:32528

**Comment by tabarra** [comment]
If the counter is under 15 it's not a problem.  
Does your server keep restarting every other minute?

**Comment by CronoVendetta** [comment]
Not, but web panel dont retrieve any info,

**Comment by CronoVendetta** [comment]
but, it seems the script is taking localhost ip, how i can change it? from where is taking 127.0.0.1?
i have public ip

**Comment by tabarra** [comment]
I'm not understanding the issue, what do you mean with the panel not retrieving any information?  
We use 127.0.0.1 to connect to the fxserver since it is in the same machine as txAdmin.  
  
Just to be sure, you are **not** running fxserver right? You should only run txAdmin and let him start fxserver for you.

**Comment by CronoVendetta** [comment]
yes, i run txAdmin and in the web panel i press start server. but send me a lot of econnrefused

**Comment by tabarra** [comment]
Does the server come online? Can you join the server 30 seconds after pressing the start button?

**Comment by typhoonmining** [comment]
What is the fix for this?
