### ISSUE TITLE
Server crashing after some time

### ISSUE THREAD

**Issue by MiguelNdeCarvalho** [citizenfx/txAdmin#122]
Hey,
I am using the 2301 artifact and sometime the server crash without information on the server log. [Here](https://hastebin.com/ecimerugim.sql) are the logs.
Thanks,
Miguel de Carvalho

**Comment by w33ts** [comment]
This is for issues such as bugs, not operator errors. Please join the discord for support: https://discord.gg/dBbMbM

**Comment by MiguelNdeCarvalho** [comment]
I am already talking there. Thanks
