### ISSUE TITLE
Help

### ISSUE THREAD

**Issue by Yassinos-coder** [citizenfx/txAdmin#125]
![Capture](https://user-images.githubusercontent.com/37705952/82161776-206d4a00-988f-11ea-90d9-9f74a43db94b.PNG)

**Comment by jooaooalmeida** [comment]
Hello sir, do you mind joining us at https://discord.gg/vHmjTH where we can help you easily?

**Comment by Yassinos-coder** [comment]
Done

**Comment by tabarra** [comment]
The two things are not related.
