### ISSUE TITLE
Monitor High Tick

### ISSUE THREAD

**Issue by CruelAlpha** [citizenfx/txAdmin#126]
Hello,
We are running v2.4.0 for txadmin and are consistently seeing high ticks for "monitor" through etwtracing.

Is there somewhere I can diagnose these high ticks? 

ETW Traces:
https://i.gyazo.com/a625ee19033e3981756b74a902d3b6d6.png
https://i.gyazo.com/e9b095bb8f1fc5219b3a0e14d8729530.png
Thanks :)

**Comment by tabarra** [comment]
These screenshots are really out of context tho...  
Are you tracing the txAdmin's fxmonitor or the target server one?  
  
Please execute the actual fxserver profiler for 5 seconds and upload the saved file for me.  
Also, make sure you are on the latest version of txAdmin... which you are not.
