### ISSUE TITLE
How can i fix this 

### ISSUE THREAD

**Issue by dabznz** [citizenfx/txAdmin#137]
![C6072BA9-99D0-41A2-A50B-14CB903ED759](https://user-images.githubusercontent.com/65999205/82984677-b2015800-a003-11ea-8a11-812a6db59cc7.jpeg)
![BF97D250-324F-44F9-9717-B44AF8221D95](https://user-images.githubusercontent.com/65999205/82984692-b88fcf80-a003-11ea-8bd5-64d1781ca1d2.jpeg)

**Comment by tabarra** [comment]
This is networking issue.
