### ISSUE TITLE
I don't understand why my server is crashing

### ISSUE THREAD

**Issue by AndreasDamen** [citizenfx/txAdmin#139]
So every time i join my server it sais it detected a crash and it restarts. How can i fix this? Or, how can i stop this from happening? This did not happen before i installed txadmin. 
![image](https://user-images.githubusercontent.com/47353259/83175841-da30aa00-a11c-11ea-89b0-a171e049a502.png)
![image](https://user-images.githubusercontent.com/47353259/83176106-3693c980-a11d-11ea-9920-49c9614416b1.png)

**Comment by FlawwsX** [comment]
There's a wonderful Discord server you can join @ https://discord.gg/XYtS9Da
Maybe someone can help you out there.

**Comment by tabarra** [comment]
1. It's clear in your own screenshot that there was an error, and likely this caused an crash;
2.  The fact that you said "txadmin detects not existing crash" in the title is 100% contradictory to your own description;
3. txAdmin never crashed servers, you likely updated the fxserver artifact when installing txAdmin, and *this* is the reason why the crashes only started now;
4. You are **still** outdated.
