### ISSUE TITLE
Discord bot does not work

### ISSUE THREAD

**Issue by paulvilla** [citizenfx/txAdmin#14]
When I activate the discord bot it does not start the server, it stops after the launch command.
I followed the following manual to get the token that I am using. Is this okay?

https://www.youtube.com/watch?v=fv-H68OwsIA

I am use Linux Debian.

**Comment by tabarra** [comment]
What is the error displayed on the console?  
This video seems a bit too complicated;  
To configure your Discord bot, follow these two guides:  [Setting up a bot application](https://discordjs.guide/preparations/setting-up-a-bot-application.html) and [Adding your bot to servers](https://discordjs.guide/preparations/adding-your-bot-to-servers.html).    
  
(note: closed by accident)

**Comment by tabarra** [comment]
Closing for the lack of new information.
