### ISSUE TITLE
Fehlende Dateien

### ISSUE THREAD

**Issue by hardersergej** [citizenfx/txAdmin#140]
admin-add.js datei fehlt

**Comment by jooaooalmeida** [comment]
English, and for more support join the discord. Link in the README

**Comment by NoobKeksTV** [comment]
Du darfst dir tx  nicht von hier laden!!! 
Du musst es über den fxserver laden.
Es ist nämlich in dem fivem Server eingebaut.
Außer du compilst  dir das selber. Was aber dumm wäre lmao.

**Comment by tabarra** [comment]
Please read the README.  
This file does not exists anymore since its not needed.  
You are following an OUTDATED tutorial.
