### ISSUE TITLE
VPS Linux Ram Problem

### ISSUE THREAD

**Issue by lerdonhd** [citizenfx/txAdmin#142]
I started running my server to a Vps (linux)... but when i opened txAdmin
i saw that i got free only 9% of my ram (i got 8GB) but webuzo says when im running my server that i got 86% available ram... 
https://prnt.sc/sqx31j

**Comment by w33ts** [comment]
Well, if you had taken the time to look at the other open issues, you would have found #19

**Comment by lerdonhd** [comment]
man i read it... but i didnt understand.. this is the problem...

**Comment by lerdonhd** [comment]
so .. i shouldnt worry about that?? cuz i thought that My server was spending almost the 90% of my ram

**Comment by EvanDarwin** [comment]
No. But you should learn how [Linux memory management works](https://www.linuxatemyram.com/).

**Comment by tabarra** [comment]
Dup of #19
