### ISSUE TITLE
add a button for delete a warn or a ban

### ISSUE THREAD

**Issue by tydoo** [citizenfx/txAdmin#145]
All in the title :)

**Comment by tabarra** [comment]
its the revoke button, its already in there

**Comment by tabarra** [comment]
Not at the player modal, but at the players page.  
Also, I will probably take away the revoke button for the warns.

**Comment by tydoo** [comment]
@tabarra No, i want to clear completly ! Delete of database.

**Comment by Korioz** [comment]
Like to revert the warn if you failed?
Without any existing traces of an old warn?
