### ISSUE TITLE
question

### ISSUE THREAD

**Issue by SliderKP** [citizenfx/txAdmin#15]
works on CentOS 7.5? i having issues installing....

npm
http://puu.sh/DOaIJ/8d2aaac0ce.png

in this imagen can see its not supported, i think...
http://puu.sh/DOaKl/90d7645257.png

**Comment by tabarra** [comment]
The first image is normal.  
The second one looks like you tried to execute the command from the troubleshooting guide that was only for windows.  
  
Try running txAdmin and see if it complains that the dependencies were not found.

**Comment by SliderKP** [comment]
when i try to execut txAdmin:
http://puu.sh/DObcI/2c39ea45a2.png

server.json in txAdmin/data

{
    "global": {
        "verbose": false,
        "publicIP": "173.214.174.139",
        "serverName": "MalosAires",
        "fxServerPort": 30120
    },
    "logger": {},
    "monitor": {
        "timeout": 1000,
        "restarter": {
            "failures": 15,
            "schedule": ["05:00", "13:00"]
        }
    },
    "authenticator": {
        "adminsFilePath": "data/admins.json"
    },
    "webServer": {
        "port": 40120
    },
    "discordBot": {
        "enabled": false,
        "token": "change-me",
        "messagesFilePath": "data/messages.json",
        "statusCommand": "/status"
    },
    "fxRunner": {
        "buildPath": "/root/fx-server",
        "basePath": "/root/fx-server-data",
        "cfgPath": "/root/fx-server-data/server.cfg",
        "setPriority": false,
        "onesync": true,
        "autostart": false
    }
}

**Comment by tabarra** [comment]
try downloading it again, it looks like you edited the index file and broke it.

**Comment by SliderKP** [comment]
this is my folder tree:
http://puu.sh/DObfN/cd3ef1585a.png

okey i going to reinstall right now

**Comment by SliderKP** [comment]
getting the same problem!

when i try to run:

[root@qs19607 txAdmin]# node src server01.json
/root/txAdmin/src/index.js:88
    async startAuthenticator(config){
          ^^^^^^^^^^^^^^^^^^

SyntaxError: Unexpected identifier
    at createScript (vm.js:56:10)
    at Object.runInThisContext (vm.js:97:10)
    at Module._compile (module.js:549:28)
    at Object.Module._extensions..js (module.js:586:10)
    at Module.load (module.js:494:32)
    at tryModuleLoad (module.js:453:12)
    at Function.Module._load (module.js:445:3)
    at Module.runMain (module.js:611:10)
    at run (bootstrap_node.js:394:7)
    at startup (bootstrap_node.js:160:9)
[root@qs19607 txAdmin]#


when start txadminclient:
Started resource txAdminClient
[txAdminClient] This resource version is not compatible with the current txAdmin version. Please update or remove this resource to prevent any issues.

**Comment by tabarra** [comment]
Something is not right, do you mind joining our discord fore more help?
https://discord.gg/f3TsfvD
