### ISSUE TITLE
Error : [txAdmin:Monitor] Restarting server (server crash detected).

### ISSUE THREAD

**Issue by Marlbogaro** [citizenfx/txAdmin#161]
[txAdmin:Monitor] Restarting server (server crash detected).

Hello I am contacting you because I have this error that appears and I do not know where it comes from or how to fix it can you help me please.

These problems happen when a certain number of players connect

![image](https://user-images.githubusercontent.com/38571731/84844831-91994c00-b04b-11ea-85c9-30f4c9520f14.png)

**Comment by tabarra** [comment]
This very clearly indicates that your server is crashing.  
Also, this is not a place for support, join our discord and you might get more info.
