### ISSUE TITLE
Unable to specify IP in endpoints

### ISSUE THREAD

**Issue by josh-tf** [citizenfx/txAdmin#163]
Hi @tabarra 

FiveM allow specifying IP address in the endpoint in situations where you do not want to bind to all interfaces, from the top of the config:

```
# Only change the IP if you're using a server with multiple network interfaces, otherwise change the port only.
endpoint_add_tcp "0.0.0.0:30120"
endpoint_add_udp "0.0.0.0:30120"
```

When setting my IP in the above, I get this error:

`[txAdmin:FXRunner] FXServer config error: You MUST have one endpoint_add_tcp with IP 0.0.0.0 in your config`

Which I've traced back to this:

https://github.com/tabarra/txAdmin/blob/8d23fec525ae68e4ce83cbb93b726f0f2e133999/src/extras/helpers.js#L165

```
    let validTCPEndpoint = matches.find((match) => {
        return (match.type.toLowerCase() === 'tcp' && (match.interface === '0.0.0.0' || match.interface === '127.0.0.1'))
    })
    if(!validTCPEndpoint) throw new Error("You MUST have one <code>endpoint_add_tcp</code> with IP 0.0.0.0 in your config");
```

Is this a limitation with txAdmin?
How can we bind to specific IP addresses as this looks to be supported by FXServer but is prevented by txAdmin

Thanks

**Comment by tabarra** [comment]
For various reasons, txAdmin needs to connect to the server  using the localhost interface.  
Setting it up as `0.0.0.0` enables us to do that.  
As you can see in the code snipped you pointed out, we also allow if there is an `endpoint_add_tcp` with interface `127.0.0.1`. So you can have your specific IP endpoints, as well as an localhost interface.  
  
The only limitation is that you would need to bind them all to the same port, which might be a problem for some.  
There is already an `globals.forceFXServerPort` var you can put in your settings to do that.

**Comment by josh-tf** [comment]
Thanks for the quick response, that makes sense

What we're intending to do is have both servers on the standard port `30120` but on external IP addresses, I've set the IP specific endpoints, added the localhost endpoints on two different ports and added the global

I get a non fatal error mentioning in relation to what you pointed out, about ports being the same:

`[18:22:18][FXRunner]  FXServer config error: All <code>endpoint_add_*</code> MUST have the same port`

Aside from this everything appears to be running fine (on both tx and fx end)

**Comment by tabarra** [comment]
Open config.json file, and in the `globals` property you add `forceFXServerPort` with the port you set for the localhost endpoint.  
I'm closing this issue, feel free to join out Discord if you want.

**Comment by josh-tf** [comment]
Yep its all working fine - thanks for your help

**Comment by SuchtClub** [comment]
what? i write this forceFXServerPort  to my config.json and create so ?

**Comment by GLN123** [comment]
> Yep its all working fine - thanks for your help

Hi, would you be willing to help me? I had the same problem as you, everything is already working for me except that one of the servers is not showing in the server list

**Comment by Roy422243** [comment]
![Screenshot 2025-01-03 000041](https://github.com/user-attachments/assets/5bae9e46-0a97-4d3c-9c14-1d17c30e0fe5)
I need help please how to fix this one?
