### ISSUE TITLE
Bot Response

### ISSUE THREAD

**Issue by Darkeen** [citizenfx/txAdmin#164]
Hello.
I'd like to report that I've a bot to send commands and It doesn't get a response from /status command.

![image](https://user-images.githubusercontent.com/8920778/85503274-40430c80-b5b7-11ea-8782-80fd4d6dd5fa.png)

Thanks in advanced.

**Comment by tabarra** [comment]
.... that's on purpose

**Comment by jooaooalmeida** [comment]
Its to prevent users from spamming, no need to check server status each minute

**Comment by Darkeen** [comment]
Yeah of course, that was an example for the picture, just need a 1 hour message not every minute. I did the test with 10 minutes and the bot doesn't get any response too.  Anyway, thanks.

**Comment by tabarra** [comment]
bot messages are ignored
