### ISSUE TITLE
Old FX Server build

### ISSUE THREAD

**Issue by armin-ahmadii** [citizenfx/txAdmin#166]
Hey
TxAdmin has received an update but the fx server build is still using the old one. How do I manually update my txAdmin

**Comment by jooaooalmeida** [comment]
Hey
This is not SupportHub, please consider joining the discord linked in the README file for help.

**Comment by tabarra** [comment]
The most recent txAdmin version is still not present in the fxserver artifacts.
Download `monitor-v2.6.0.zip` from the following link:
https://github.com/tabarra/txAdmin/releases/latest
Then replace the `citizen/system_resources/monitor` folder contents with the files from the downloaded ZIP.
On linux, this folder is inside `alpine/opt/cfx-server/citizen/system_resources`.
