### ISSUE TITLE
Ideas for improving the Resources List UI

### ISSUE THREAD

**Issue by Hernior** [citizenfx/txAdmin#167]
Here are some suggestions for improving the interface:
1. Use accordion in resource categories
1. Create category tabs like pills to switch between them
1. Group resources by started / stopped
1. Show fxmanifest version

**Comment by tabarra** [comment]
Thanks for the suggestions.  
Unfortunately, mainly due to priorities, I won't put more time in the resources list considering its already working well enough.  
There are bigger fights to fight hahaha
