### ISSUE TITLE
txadmin not working with zap vserver

### ISSUE THREAD

**Issue by JJclbg** [citizenfx/txAdmin#168]
**i** dont now why it is not working but we  want to release our Server today we worked hard for it ****
https://prnt.sc/tbz0js
https://prnt.sc/tbzjwz
please answer as fast as you can i Need to fix that

**Comment by jooaooalmeida** [comment]
Hey, for support join the discord server, github issues are for... Issues...Anyways, what it's showing on the screenshots are a sigabrt, thst is not caused by txAdmin.

**Comment by JJclbg** [comment]
I Need the Dc link

**Comment by tabarra** [comment]
you need to read the docs then  
learn how to use your eyes
