### ISSUE TITLE
txAdmin is not updating

### ISSUE THREAD

**Issue by MisterMIntBoy** [citizenfx/txAdmin#169]
I am on the latest artifacts (2625), and have downloaded the 2.6.0 update from Github, but the txAdmin web GUI is saying that it is still version 2.5.1, and that it needs to update.

**Comment by tabarra** [comment]
**That is not the latest artifact.**    
  
Latest Windows: 2672  
https://runtime.fivem.net/artifacts/fivem/build_server_windows/master/?17  
Latest Linux: 2672  
https://runtime.fivem.net/artifacts/fivem/build_proot_linux/master/?17
