### ISSUE TITLE
Choose language

### ISSUE THREAD

**Issue by ghost** [citizenfx/txAdmin#17]
Add an option in the settings for change the language(especially for the discord bot ) (and if you need a french translator, i'am your guy :) )

**Comment by GrapsZ** [comment]
Solution : Translate your script ;)

**Comment by ghost** [comment]
yes but the bot stay in english

**Comment by tabarra** [comment]
There will be a way to translate the bot and server chat messages.

**Comment by ghost** [comment]
Turkish translator here, if needed.
