### ISSUE TITLE
Error rendering 'dashboard'.

### ISSUE THREAD

**Issue by Advance-xd** [citizenfx/txAdmin#170]
Error rendering 'dashboard'.
Message: Cannot read property 'message' of undefined

**Comment by tabarra** [comment]
screenshot of the entire terminal.

**Comment by Advance-xd** [comment]
https://prnt.sc/tcza3k

**Comment by tabarra** [comment]
1. you didn't had to update txAdmin, it already comes with artifact 2654  
2. you didn't actually updated... you are still outdated  
3. you forgot to also copy the web folder 🤦

**Comment by Advance-xd** [comment]
So I need to backup the web folder?

**Comment by tabarra** [comment]
This is github and not supporthub, if you want support go to our discord.  
Also, I already told you: 
> you didn't had to update txAdmin, it already comes with artifact 2654
