### ISSUE TITLE
[Suggestion] Bans & Whitelist

### ISSUE THREAD

**Issue by czsquizer** [citizenfx/txAdmin#171]
Hello, I would like to suggest some, maybye, cool things :)

1. Add possibility to Whitelist SteamHEX ID
2. Add posibility to ban IP

**Comment by tabarra** [comment]
1. it is actually possible in the backend, I'm just blocking it for now. Not sure when I will enable it.
2. no.... people in the fivem community need to forget IP exists. Blocking it means absolutely nothing. This is not the 2000's anymore.

**Comment by czsquizer** [comment]
Oki, thank you. Hope the 1. will be soon :)

Have a nice Day
