### ISSUE TITLE
Unable to revoke warnings

### ISSUE THREAD

**Issue by PaulyJ1** [citizenfx/txAdmin#172]
Issue: Unable to revoke any warnings.
Version: v2.6.0 atop FXServer 2681.
Evidence: https://streamable.com/c5i6o6

**Comment by jooaooalmeida** [comment]
Its a warning, u cant revoke a warning, what would revoking one do? A warn just shows a red screen for the user and disappears in 10 seconds, there is no way to revoke something that already is completed...
