### ISSUE TITLE
File doesn't exist or its unreadable for server.cfg

### ISSUE THREAD

**Issue by dimman24** [citizenfx/txAdmin#174]
The setup form cannot find my server.cfg
![11](https://user-images.githubusercontent.com/34796488/87217993-9eae1000-c357-11ea-91c7-717202ab3d9b.png)
![22](https://user-images.githubusercontent.com/34796488/87217995-a077d380-c357-11ea-945b-4980c0efed72.png)

**Comment by NonStopGamer** [comment]
First this is not supporthub this is for issues so read the docs and join the discord for help also here's a hint your cfg is a text file not a cfg file

**Comment by ZockerBoysHD** [comment]
mine is though lmao
but the ressources in path if prob. wrong. its not a ressource, its a server

**Comment by w33ts** [comment]
Like @NonStopGamer said, join the Discord. This is for actual issues, not a support page for operator error.

**Comment by tabarra** [comment]
https://i.imgur.com/ifLZg5G.png
