### ISSUE TITLE
Idea: txAdmin simple REST API

### ISSUE THREAD

**Issue by djmetla** [citizenfx/txAdmin#179]
It is possible? Simple endpoint for web requests for RESTART, START, STOP server authenticated with token Bearer or something else? Maybe oAuth?

**Comment by Trsak** [comment]
Not sure what would this be used for? 
Why would you need to control server through API and not directly?

After all, you could just create users with `server.control` permission.

**Comment by DmACKGL** [comment]
> Not sure what would this be used for?
> Why would you need to control server through API and not directly?
> 
> After all, you could just create users with `server.control` permission.

For more integrations, like admin websites (external for ESX), Discord Bots, Etc.

**Comment by gideongrinberg** [comment]
I also agree with this, we should be able to hook into txAdmin's API programmatically. My usecase for this would be adding scripts that use txAdmin features while still keeping txAdmin for manual work.

**Comment by NoobKeksTV** [comment]
Maybe also an api for getting the playtime of a player?

**Comment by Gravxd** [comment]
Having an api with an auth system to issue server commands like restart or just console based command in general

**Comment by jooaooalmeida** [comment]
> Having an api with an auth system to issue server commands like restart or just console based command in general 

Console commands can be executed by clicking f8 and typing it in there.

**Comment by Gravxd** [comment]
> > Having an api with an auth system to issue server commands like restart or just console based command in general
> 
> Console commands can be executed by clicking f8 and typing it in there.

Apologies I was a little unclear. I was meaning in the context of having an API usable by apps like discord bots.

**Comment by udit2303** [comment]
A REST API would be very useful incase of using bots like discord bots to access txAdmin directly to ban players, warn players, etc. Maybe also add some rate limiting to prevent spam.

**Comment by PLOKMJNB** [comment]
Me want API too please, I give cookie too

**Comment by AvarianKnight** [comment]
API When? Sounds neat

**Comment by coleminer0112** [comment]
TxAdmin android app.. coming soon to Google Play Store!

(Jk, I am not an android developer)

But yes, I agree that an endpoint for a POST request or the like allowing you to interface with your TxAdmin (securely) would be great for a discord bot that, for example, can ban players from the FiveM server automatically if their discord is banned from the server's Discord!

*edit:*
Perhaps the authentication could work by creating a hash of the bot's token, then on the bot side you execute the same hashing algorithm on the token - and that becomes your authentication key for allowing API actions in TxAdmin? This obviously would mean that the bot's developer would need to Gatekeep very well and prevent unauthorized use of this by those they don't want interacting with TxAdmin's functions.. but the option would perhaps be useful to some servers

**Comment by Nimplex** [comment]
Great idea! REST API will be very useful when creating for example a discord bot that will have integration with the server.

**Comment by caeptnlaen** [comment]
Please API

**Comment by n0tsiege** [comment]
+1 we want an API

**Comment by michieldesair** [comment]
+1 yes api

**Comment by Arm-0001** [comment]
+1 api or no more menu 🔫

**Comment by Nimplex** [comment]
+1 api

**Comment by TasoOneAsia** [comment]
-1

**Comment by NoobKeksTV** [comment]
+1

**Comment by tabarra** [comment]
> +1

Hey sir! No double voting! lmao

**Comment by wowjeeez** [comment]
tx rest api best rest api

**Comment by kotzeimer** [comment]
+1

**Comment by Nimplex** [comment]
Well, we can use RCON actually but REST API would be very cool thing

**Comment by Arm-0001** [comment]
> Well, we can use RCON actually but REST API would be very cool thing

don't think rest API is every coming unless someone other than tabby makes it cause he is l a z y eks dee

**Comment by TasoOneAsia** [comment]
Very funny Hamy, now let the contributors talk. REST API was in the task list for after stable menu release but at this time, currently unknown timeline.

**Comment by ghost** [comment]
😭😢

**Comment by SticksDev** [comment]
rest api +1

**Comment by tabarra** [comment]
This issue lacks a bit of focus, so I would like to invite anyone interest in using the new issue: #442

**Comment by eXahostCOM** [comment]
rest api +1

**Comment by Aimbas** [comment]
+1

**Comment by GravityScriptsV2** [comment]
+1

**Comment by Nimplex** [comment]
> This issue lacks a bit of focus, so I would like to invite anyone interest in using the new issue: #442

^^^^
