### ISSUE TITLE
Txadmin Automatic logged out when logged in

### ISSUE THREAD

**Issue by jhannah09** [citizenfx/txAdmin#184]
![Untitled](https://user-images.githubusercontent.com/68683973/89950448-36a36000-dc5c-11ea-918a-6151423060b8.png)
![Untitled](https://user-images.githubusercontent.com/68683973/89950215-b8df5480-dc5b-11ea-9b5c-edca2bfc3963.png)
 
I have updated my FX Server to the lates build and my tx admin to the latest but when i log in at my browser (not on our server browser) i automatically logged out when logged in

**Comment by jhannah09** [comment]
![Untitled](https://user-images.githubusercontent.com/68683973/89950387-1d021880-dc5c-11ea-9651-d268a565fbe9.png)

**Comment by jooaooalmeida** [comment]
Hey my friend, as you can read, this is the Issues part of github and not support, to get proper help join our [discord](https://discord.gg/ytg8bD)

**Comment by tabarra** [comment]
This is not an issue with txAdmin, its either with your browser or maybe even the cfx.re proxy.  
Also, this is not supporthub.
