### ISSUE TITLE
Total memory usage misleading in Linux instances

### ISSUE THREAD

**Issue by Epictek** [citizenfx/txAdmin#19]
The current memory usage implementation uses os.freemem() which reports buff/cache as memory used. Avaliable memory should be used instead as it's a lot more useful imo. Maybe even show both as a stacked bar? https://getbootstrap.com/docs/4.3/components/progress/#multiple-bars

**Comment by tabarra** [comment]
The annoying thing is that Node only gives us 'available' and 'total'.  
In windows, `total - free = used`, but in linux `total - free = used + cache + buffer`.  
  
This can be solved with me querying the OS for the actual values, but this require some complexity that I do not want to add to every monitor interval (1s). I could cache the data for 10 seconds or so, or just query it when the user is looking for it, but I just didn't have time to do it.  
  
Will leave this issue open until I fix the problem.  
BTW, you can always get the actual fxserver/txadmin values from the Full Status Report page.

**Comment by TheDjRider** [comment]
The same problem with me. 
Also txAdmin web version very very often show that the server is OFF and have 0 players instead of this the server is active for more than 12 hrs and have active players.

**Comment by NoobKeksTV** [comment]
like tabarra explained this is due to how linux counts memory usage...  But the thing with an offline server never happend to me?

**Comment by tabarra** [comment]
For now I'm just adding an "explanatory" message: 
![Image](https://i.imgur.com/gmLh1dC.png)

**Comment by NoobKeksTV** [comment]
may be a good idea xD

**Comment by EvanDarwin** [comment]
Suggestion: Show the different Linux memory types as separate colors? It will help the new messaging make more sense.

**Comment by tabarra** [comment]
> Suggestion: Show the different Linux memory types as separate colors? It will help the new messaging make more sense.

Annoying to write... I would need to write my own way of getting this by executing `free` on linux or something like that.  
In the end, I don't think it matters enough for me to prioritize it.

**Comment by AdventurePandah** [comment]
Would appreciate it, this could be useful: https://systeminformation.io/

It just scares off newbies if the memory is 100% 😆

**Comment by w33ts** [comment]
Then the newbies need to get good, learn how the OS they are administrating works and pop a banana in their ear.
