### ISSUE TITLE
[Ideas] New txAdmin options

### ISSUE THREAD

**Issue by Neddings** [citizenfx/txAdmin#193]
Have the CFG Editor handle multiple config files through a pulldown menu 

- preload all files that have the extension .cfg when opening this tab

Have the ability to clean the cache folder through a new menu option in Settings

- Easier to have the menu option then having to manually remove it

**Comment by jooaooalmeida** [comment]
Just a quick remember, u don't need to delete your server cache, thats something that had to be done in old FXServer builds. Cache helps your server to start up faster.
![image](https://user-images.githubusercontent.com/61633775/90499675-bdb37500-e141-11ea-9a4d-dccf39612f45.png)

**Comment by PLOKMJNB** [comment]
I second the multi .CFG editor

**Comment by tabarra** [comment]
The cache thing is a no.  
The CFG thing is a maybe, there is already one PR/Issue for that.
