### ISSUE TITLE
Idea: replace ping with Server ID in the playerlist

### ISSUE THREAD

**Issue by manzarek123** [citizenfx/txAdmin#195]
https://i.gyazo.com/4d2ff9b046249ae29509502461e6c6ec.png

I propose to replace the ping with the server ID, we could keep the color lines to have an idea of the ping and maybe display the ping in the modal  once we click a player.

**Comment by tabarra** [comment]
Would probably be confusing for vRP users, that's why I never did it this way.  
  
But for the sake of democracy, I will leave this thread open for a few days.  
Get people to come here convince me, and I will do it.

**Comment by jooaooalmeida** [comment]
I like the idea, but why replace a usefull funcion (player ping) with the ID? its better to just append [ID] to the name, also @tabarra why would it be confusing for vrp users? is it because they are used to fix IDs and FiveM IDs are dynamic? Asking as i always used ESX and well, it has dynamic IDs by default

**Comment by manzarek123** [comment]
I have no experience with vRP but the server ID is a Fivem feature, appending [ID] could be a solution but it would not be very well aligned if added at the end of the name but it could be prefixed maybe.
I proposed to move the ping to the modal to gain some space.

Because currently when I get an ID to ban or warn i have to do some dichotomic search in the list :)


Also another nice feature could be to be able to click on a ban and it opens the modal with the banned player information

**Comment by jooaooalmeida** [comment]
> I have no experience with vRP but the server ID is a Fivem feature, appending [ID] could be a solution but it would not be very well aligned if added at the end of the name but it could be prefixed maybe.
> I proposed to move the ping to the modal to gain some space.
> 
> Because currently when I get an ID to ban or warn i have to do some dichotomic search in the list :)
> 
> Also another nice feature could be to be able to click on a ban and it opens the modal with the banned player information

Doesn't clicking the player in the playerlist open his profile and u can ban from there?

**Comment by manzarek123** [comment]
Yes but I mean when I just know the ID I have to click in the playerlist multiple times until I find the correct profile. That is the main reason I initially proposed to add the server ID in the player list

**Comment by PLOKMJNB** [comment]
You know, you could add a toggle In the settings to prefix the payers name with `[ID]` after their ping, in a separate color

**Comment by codygulley** [comment]
I tend to like @PLOKMJNB suggestion. However, I would prefix a non-colored [ID] before the user and put the colored ping after the user. E.g.

![TxAdmin-PlayerIdSuggestion](https://user-images.githubusercontent.com/8097956/102337638-f9bfe080-3f4f-11eb-92b1-4b1a345de2e5.png)

**Comment by jooaooalmeida** [comment]
> I tend to like @PLOKMJNB suggestion. However, I would prefix a non-colored [ID] before the user and put the colored ping after the user. E.g.
> 
> ![TxAdmin-PlayerIdSuggestion](https://user-images.githubusercontent.com/8097956/102337638-f9bfe080-3f4f-11eb-92b1-4b1a345de2e5.png)

The ping looks kinda odd in there tho, makes it look just a random colored number there, maybe with some styling it could be made better, +1 on this one

**Comment by Rhydium** [comment]
You could make the format like this:
PING - [ID] **Username**

In this way you have a clear separation between the ping and ID and it doesn't look very weird.
Also the toggle for this option that @PLOKMJNB suggested seems like a good option because not all people need this and/or want this.

**Comment by FlawwsX** [comment]
This would be great.

**Comment by codygulley** [comment]
In an order of importance and most useful information IMHO it doesn’t make sense for the ping to be the first thing you see . 

Almost always you’ll be trying to find a user by ID or name .

**Comment by LySoon** [comment]
Would be great too, we really need IDs

**Comment by tabarra** [comment]
Done.  
Looks like this:
![playerlist](https://i.imgur.com/TxS9xbC.png)
