### ISSUE TITLE
How to launch a TigerEvent at server startup?

### ISSUE THREAD

**Issue by paulvilla** [citizenfx/txAdmin#202]
I am using a script to have persistent cars, but I need that when the server is restarted, either manually or automatically, it launches a tigerEvent to save the position of the cars.
I need to know in which file and line to be able to add that tigert event for it to work, since it is something very important for me

**Comment by NoobKeksTV** [comment]
Ressource start event
Or retard,  put it in the code anywhere without any function. Then it will auto-trigger 🤦‍♂️

**Comment by paulvilla** [comment]
> Ressource start event
> O retard, póngalo en el código en cualquier lugar sin ninguna función. Entonces se disparará automáticamente🤦‍♂️

this code has to be started before the server stops

**Comment by paulvilla** [comment]
> Ressource start event
> Or retard, put it in the code anywhere without any function. Then it will auto-trigger 🤦‍♂️

I have put the triggerevent in this part of the server file, but when I restart the server it does not launch.
It has to be on the server side, on the server restart command line, either manual or automatic

![image](https://user-images.githubusercontent.com/14887229/93234009-0def1880-f77c-11ea-96da-e5f03d97618f.png)

**Comment by NoobKeksTV** [comment]
wow.

U need to add it to "OnRessourcestartup" to run code when started
wtf are u dumb or stupid.

**Comment by NoobKeksTV** [comment]
Ofcourse. u trigger ur stuff when u kick all the players. wtf.

Check out OnResourceStop & OnResourcestart event. first event which u get on the fivem docs
