### ISSUE TITLE
Idea: server start and stop at specific time

### ISSUE THREAD

**Issue by raffycaccia** [citizenfx/txAdmin#203]
In the panel there is the possibility to restart the server at a specific time, it would be very useful to be able to set a start and shutdown time for the server

**Comment by aidenzybell** [comment]
Yes, you can do automatical restarts in the settings part of the panel. But you cannot shutdown the server have it down and then have it turn back on 2 hours later. Would possibly be a cool idea though.

**Comment by tabarra** [comment]
I see no real use case for that except maybe an event server, in which case you better have some staff anyways.  
Also, nobody ever asked for this so not worth doing it.
