### ISSUE TITLE
players.json corrupts itself

### ISSUE THREAD

**Issue by coleminer0112** [citizenfx/txAdmin#204]
Every once in a while [around once per month] our `players.json` file becomes corrupted. It seems like the entire file is overwritten with [NULL] characters, and opening it in VSCode yields this result: [screenshot](https://imgur.com/a/RBNvMrM)

**Comment by EvanDarwin** [comment]
@coleminer0112 Approximately how many players are you reaching when this happens?

**Comment by tabarra** [comment]
I'm guessing VM issues, since lowdb uses `JSON.stringify`and `fs.writeFile` directly, without any weird things.

**Comment by coleminer0112** [comment]
I'm not sure what kind of VM issues would cause this? Unexpected crashes / shutdowns?

**Comment by tabarra** [comment]
yes, maybe that

**Comment by coleminer0112** [comment]
so what could we do to prevent this? Ensure we always shutdown through txadmin before restarting the VM? As I'm sure txadmin would finish up any open file connections before exiting?

**Comment by tabarra** [comment]
Not sure.  
As any other database, you should backup regularly, but txAdmin is specially easy since you can just copy the file.  
  
I'm closing this issue since it doesn't look like it's an issue with txAdmin per se.  
You can always come to our discord for more support.
