### ISSUE TITLE
IP Allias with the support of endpoint_add_tcp/ udp

### ISSUE THREAD

**Issue by mariosmikroulis** [citizenfx/txAdmin#207]
I own two servers, where I've purchased 2 different IP addresses so I could have them separated and I could have my main IP where I will be dealing with other things. Both of those two servers will be having a different IP endpoint and different port.

When I've changed the endpoint_add_tcp /udp for the first server to the desired port:
`123.123.123.10:30100`

the problem I faced was it showed the following message without starting the server:
`[txAdmin:FXRunner] FXServer config error: You MUST have one <code>endpoint_add_tcp</code> with IP 0.0.0.0 in your config`

I've googled it and I've attempt to add on my txData/default/config.json the following:
`"forceFXServerPort": "30100"`

Once I did that, and started the server, it was still showing the FXServer config error but at least it was starting up the server.
The server started, but on the main page of txAdmin, it shows that the server started partially. Two minutes later, the console throws the following message:
```
[txAdmin:Monitor] (HB:2|HC:--) FXServer is not responding. (connect ECONNREFUSED 127.0.0.1:30100)
[txAdmin:Monitor] Restarting server (server partial crash detected).
[txAdminClientLUA] Admin Broadcast - txAdmin: Due to a partial crash, this server will restart in 1 minute. Please disconnect now.

[txAdmin:FXRunner] >> [5948] FXServer Exited.
[txAdmin:FXRunner] >> [5948] FXServer Closed. (code 0)
```

Just to note that, when I start the server without the txAdmin, it runs normally without issues and I can connect in both servers with different IPs, even though both of the servers are on the same machine.

Once this message appears, it restarts the server within a minute and the whole thing just repeats again and again. Any ideas or thoughts?

**Comment by idobyte** [comment]
I understand you're having issues, did you ever get them resolved?

**Comment by idobyte** [comment]
I'd try something more like this 
endpoint_add_tcp "0.0.0.0:30120"
endpoint_add_udp "0.0.0.0:30121"

And port forward both ports. And only open each port via firewall to prevent issues with connecting.

**Comment by mariosmikroulis** [comment]
This won't get my problem fixed. as mentioned, I am having 3 IPs that are owned by my host. They are purchased and became alliances. I am having two gameservers and I want to have two different ips from each. Therefore, 0.0.0.0 will trigger the main IP which is not what I aim

**Comment by PLOKMJNB** [comment]
If you aren't able to find a solution, as a comprable choice you can setup domain proxies with something like cloudflare

**Comment by mariosmikroulis** [comment]
@PLOKMJNB Will you be able to help me out to set this up? I'm actually having an account and domains

**Comment by PLOKMJNB** [comment]
join the discord, if you can share your screen there I can show you how

**Comment by mariosmikroulis** [comment]
I'm on the txAdmin voice channel. Come and join me. xFranky here

**Comment by tabarra** [comment]
You were supposed to create a new tcp endpoint with the port you set in the config.  
If you configure fxserver to only listen on the WAN interface, txAdmin wont be able to locally connect to it (hence the issue you are having).  
  
Well, this is from september so I guess the issue was already solved....
