### ISSUE TITLE
Adding an Reject whitelist button

### ISSUE THREAD

**Issue by AleksanderEvensen** [citizenfx/txAdmin#210]
If your server is large and you get tons of daily traffic your whitelist screen will most likely be full of whitelist requests. it would be nice if you could reject them, to clean up the list.

**Comment by Arm-0001** [comment]
there is an option to clear whitelist after each restart if you want that

**Comment by tabarra** [comment]
What would happen if the user tries to join back?  
Would we create a new ID for him? 
Would remember that he was rejected? in this case we would need to make an easy way to revert that....  
  
As Hamza said, the whitelist "filling up" is not an actual issue.
