### ISSUE TITLE
Error after Login on txAdmin Dashboard

### ISSUE THREAD

**Issue by dominikexe** [citizenfx/txAdmin#213]
Hey everyone.

We have the issue that we cant see only the dashboard on our txadmin site.
This error is comming: ´

![image](https://user-images.githubusercontent.com/72306818/94992977-fb534c80-058d-11eb-928a-c1bb8b3fff3b.png)

Can anyone help?
Thx

**Comment by jooaooalmeida** [comment]
Let me ask you something, what txAdmin version are you running?

**Comment by dominikexe** [comment]
v2.4.0 atop FXServer 2431

**Comment by jooaooalmeida** [comment]
> v2.4.0 atop FXServer 2431

My man you are using a VERY outdated version of course you are getting errors.... Download latest FXServer artifacts and tell me if it continues please.

NOT recomended, use the TOP one in the list

Linux: https://runtime.fivem.net/artifacts/fivem/build_proot_linux/master/?792

Windows: https://runtime.fivem.net/artifacts/fivem/build_server_windows/master/?867

**Comment by dominikexe** [comment]
okay, i will try it
