### ISSUE TITLE
Server timezone source?

### ISSUE THREAD

**Issue by YpsilonTM** [citizenfx/txAdmin#218]
It could be that it's my fault. But how does TXAdmin get the server timezone.
Because at the moment for me the Server's timezone is undefined.
I haven't had a moment to dig through all the code. So I was hoping someone could help out here.

My apologies if this is my own fault.

**Comment by tabarra** [comment]
please post an screenshot of the entire page, including footer.

**Comment by YpsilonTM** [comment]
![chrome_O2FGIlxPji](https://user-images.githubusercontent.com/22861150/96013835-fe7bf180-0e45-11eb-89b0-dbce6b3db98d.png)
Like this ?

**Comment by YpsilonTM** [comment]
I see that the js is getting the servertimezone with
`Intl.DateTimeFormat().resolvedOptions().timeZone;` 
but im starting the think its an issue where it can't get the time zone on the serverside.

Question: When the server timezone is undefined does the restart function still work?

**Comment by tabarra** [comment]
It should work, go to the txAdmin log page. There you should see the timestamp of things that happened.  
Offsetting it from your own time you should know the timezone the server is at.

**Comment by YpsilonTM** [comment]
Ok I just noticed the server time is at UTC 0 while we are UTC +2 atm so 2 hours offset.
Maybe a feature request is to have the option to set server timezone in options.

**Comment by tabarra** [comment]
Kinda an unnecessary complication.  
Since the servers are usually single purpose, there is no reason not to change its timezone.  
  
Seems like your issue was solved, so I'm closing this thread.  
Feel free to join our discord tho.
