### ISSUE TITLE
Save Server Log - Suggestion

### ISSUE THREAD

**Issue by czsquizer** [citizenfx/txAdmin#220]
Hey there!

I would suggest saving somewhere server log, to be possible to get access to it after server restart or access more to the top. Becauase there are many usefull information. Thank you for reading. For any futher questions about it do not hesitate to contact.

Have a nice day
Squizer

**Comment by Arm-0001** [comment]
it already saves to C:\[SERVER NAME]\txData\default\logs

**Comment by jooaooalmeida** [comment]
> it already saves to C:[SERVER NAME]\txData\default\logs

This isn't 100% correct, if the user has the server in a different place then txDdata will be in a different place, the logs are saved in `<citizen_root>/../txData/[profile name]/logs` for Windows and `<citizen_root>/../../../txData/[profile name]/logs` for Linux
