### ISSUE TITLE
Resources 

### ISSUE THREAD

**Issue by FIVEOEMG** [citizenfx/txAdmin#222]
increase limit

**Comment by PLOKMJNB** [comment]
why

**Comment by jooaooalmeida** [comment]
> increase limit

what? txAdmin will start every resource in your server.cfg there is no limit, if you put 400 resources u are going to get a warn in txadmin saying u have a high ammount of scripts tho

**Comment by PLOKMJNB** [comment]
he means the resource page which is limited to 200

**Comment by tabarra** [comment]
There is no limit.
