### ISSUE TITLE
Suggestion for the whitelist

### ISSUE THREAD

**Issue by Chxttr** [citizenfx/txAdmin#225]
In terms of the whitelist, don't get me wrong, it's a lovely system

But

I thought it would be cool, if we had some kind of logging system implemented so that we get a discord message when someone tries to join and requires Whitelist Approval so we can actually do it on discord

Apologies if there is already such system in place or being created.

**Comment by jooaooalmeida** [comment]
U can configure txAdmin Discord bot and use !addwl <Code here> I dont think its necessary sending that info to discord since u can easily ask for the user code when he applies for the server whitelist for example
