### ISSUE TITLE
Suggestion of MySQL control

### ISSUE THREAD

**Issue by ghost** [citizenfx/txAdmin#228]
You can **embed** the [Adminer ](https://www.adminer.org/)_(Database management in a single PHP file)_ in the txAdmin Panel. It is a single PhP file that can access the database and perform actions like insert/ export / update / drop etc.

[Adminer ](https://www.adminer.org/) (formerly phpMinAdmin) is a full-featured database management tool written in PHP. Conversely to phpMyAdmin, it consist of a single file ready to deploy to the target server. Adminer is available for MySQL, MariaDB, PostgreSQL, SQLite, MS SQL, Oracle, Firebird, SimpleDB, Elasticsearch and MongoDB.

Thank you for your time.

**Comment by EvanDarwin** [comment]
I believe this is outside the scope of txAdmin, let alone the fact there is no PHP environment.
