### ISSUE TITLE
Suggestion: Increase 24 hours player count status

### ISSUE THREAD

**Issue by DevDokus** [citizenfx/txAdmin#229]
Dear Tabarra. 
Often i would be interested to compare my player count with 
that of yesterday or 2 days ago. If i look now at 2 pm, I am only 
able to look back until 10 am this morning.

It would be nice if we where able to look back 
longer then 24 hours. It could be really useful. 

Many thanks for your time.

**Comment by tabarra** [comment]
In v3.3 I increased the chart to 30 hours.  
More than that would require a dedicated  charts page... not sure if I will do that soon.
