### ISSUE TITLE
Suggestion: Start All Resources

### ISSUE THREAD

**Issue by gideongrinberg** [citizenfx/txAdmin#230]
I recently ported the LC map to my server, but b/c I'm disorganized it's in around 200 resources. txAdmin displays them all, but it would be nice to have a "start all resources" button. Either it could be at the top of the page or each group of resources could have it's own.

**Comment by tabarra** [comment]
There is no elegant way for me to start all resources.  
So I wont implement it.  
MAYBE doing it by category: even if you are disorganized, you can put all the resources in some `[folder]` then just do `ensure [folder]`.  
  
This works even for some default folder organizations like `ensure [cars]`.
