### ISSUE TITLE
SSH Console

### ISSUE THREAD

**Issue by DeWilX** [citizenfx/txAdmin#242]
Hello, I recently started using txAdmin, I had created Discord integration with fxserver console thru Linux "screen" and now problem is that I can't type in there anymore and also tried to find if there is any API for txAdmin, but I didn't find any, I would like to know if there is any possible way that I can still send server commands thru ssh console?

Thanks.

**Comment by PLOKMJNB** [comment]
Just use txAdmin's console tab

**Comment by DeWilX** [comment]
> Just use txAdmin's console tab

You didn't understand my situation, I know that I can use from txAdmin, but I need access for my discord bot.

**Comment by tabarra** [comment]
Discord bot sending SSH requests?  
Sounds really really weird.  
  
Also, you can totally do connect your discord bot to the live console:
- POST /auth/password with login credentials
- start socket.io client setting the header cookie you got from the last request
- ???
- Profit
