### ISSUE TITLE
Suggestion : Auto Artifact Updater

### ISSUE THREAD

**Issue by ADRNALN** [citizenfx/txAdmin#250]
Don't know the exact size or complexity of such a thing (I'd assume very large), but it would be neat having the ability in the dashboard to update server artifacts through the panel itself. I can already see issues with this considering txAdmin require FXServer.exe to be executed prior to accessing the panel but it still may be do-able by closing the session while its updating?

**Comment by tabarra** [comment]
Can totally be done, and I really wanted that, but last time I asked one of The Elements from the CFX team said "no".  
Post this suggestion to the forum, maybe he is willing to change his mind.
