### ISSUE TITLE
Suggestion: View a full list of Bans/Warns/Whitelists

### ISSUE THREAD

**Issue by AleksanderEvensen** [citizenfx/txAdmin#265]
It would be nice if you could view a full list of all your Bans/Warns/Whitelists, not only the last 20 actions.

Maybe make these clickable
![image](https://user-images.githubusercontent.com/19311856/105029127-351f6480-5a52-11eb-8f73-1f16b4315b70.png)

or add an button here
![image](https://user-images.githubusercontent.com/19311856/105029263-65ff9980-5a52-11eb-9936-69ee7f9d0001.png)

or just make more cards at the bottom of the page.

**Comment by tabarra** [comment]
Full list is a no go.  
Some servers have thousands of bans... should I just print it all to the screen? Nope  
  
You have an amazing search box, use it while i find a good way to make it that is not super annoying.

**Comment by tabarra** [comment]
I will actually try to make something like that in the next update.  
Thanks for the suggestion.
