### ISSUE TITLE
Idea: txAdmin databas access -> delete permanetly users 

### ISSUE THREAD

**Issue by zickzackhd** [citizenfx/txAdmin#266]
**Idea**
Is if users get  permanently  banned over txadmin, also all entries in the database get deleted like items owned cars etc.
**How it coud get achieved?**
You could achieve it via the steam identified, which simply searches for it in the whole database and then delete the right row

1. get users rockstarlicence and steamhexid
2. seach in all tables for thies identifer

**Comment by tabarra** [comment]
not in the scope for txAdmin  
  
You can write a resource to listen for ban events (not available yet) and wipe the user from the db yourself.
