### ISSUE TITLE
Import Bans two Times

### ISSUE THREAD

**Issue by melonenmario** [citizenfx/txAdmin#272]
I have imported my Banns from Easy Admin and vMenu two times, no I have all bans double (374 bans). How can I delte the bans from Tx admin?

**Comment by PLOKMJNB** [comment]
> I have imported my Banns from Easy Admin and vMenu two times, no I have all bans double (374 bans). How can I delte the bans from Tx admin?

Please use the discord for support

**Comment by melonenmario** [comment]
Ok sry

**Comment by tabarra** [comment]
You were instructed to do a backup 🤣
