### ISSUE TITLE
Player count issue

### ISSUE THREAD

**Issue by matthias1005** [citizenfx/txAdmin#276]
When much players join our server, sometimes there are 20 ingame, while txAdmin only shows 19 or 18? what the hell is going on there. Those players are indeed ingame, I can tell that because we use TS3 Voice and when clicking on our Voice Channel there are 20 people inside. 

I use txAdmin Version v3.2.3
![image](https://user-images.githubusercontent.com/74554723/106353682-91a14000-62ec-11eb-9700-c3afe03b3d99.png)

**Comment by EvanDarwin** [comment]
This is related to a user with different `license` and `license2` identifier.

**Comment by tabarra** [comment]
Doesn't look like a bug tbh, but either ways the license/license2 thing will be evaluated when I'm adding the hardware id bans.
