### ISSUE TITLE
Server crash when i go to resources

### ISSUE THREAD

**Issue by FunnyBuddys** [citizenfx/txAdmin#278]
The whole FiveM server crashes when I click in the "Resources" window. On monitor.

Resources are not shown to me.

Error in console:
```Got a SIGSEGV while executing native code. This usually indicates a fatal error in the mono runtime or one of the native libraries used by your application.```

Version: `
v3.2.3 atop FXServer 3456`

**Comment by PLOKMJNB** [comment]
Please use the Discord for support.
