### ISSUE TITLE
Resources can't be loaded

### ISSUE THREAD

**Issue by NitchgamingStudios** [citizenfx/txAdmin#284]
Resources cant load i get this error 
![image](https://user-images.githubusercontent.com/72492013/107751265-4a499380-6d71-11eb-910f-ee747ae053ac.png)

**Comment by Arm-0001** [comment]
This isnt an issue with txadmin 😂😂😂😂. Also go to the txadmin discord for support. Invite link:https://discord.gg/STEXHZ56Wb

**Comment by NitchgamingStudios** [comment]
How would I fix this then?

**Comment by NitchgamingStudios** [comment]
> This isnt an issue with txadmin 😂😂😂😂. Also go to the txadmin discord for support. Invite link:https://discord.gg/STEXHZ56Wb

How do I fix this issue then?

**Comment by Arm-0001** [comment]
> > This isnt an issue with txadmin 😂😂😂😂. Also go to the txadmin discord for support. Invite link:https://discord.gg/STEXHZ56Wb
> 
> How do I fix this issue then?

its not an issue and go to the txadmin discord invite above

**Comment by NitchgamingStudios** [comment]
> > > This isnt an issue with txadmin 😂😂😂😂. Also go to the txadmin discord for support. Invite link:https://discord.gg/STEXHZ56Wb
> > 
> > 
> > How do I fix this issue then?
> 
> its not an issue and go to the txadmin discord invite above

will you be able to assist me from there?

**Comment by eeeee24242** [comment]
huh

**Comment by Tokyo-Cyber** [comment]
test

**Comment by tabarra** [comment]
As said above, this has nothing to do with txAdmin.  
Configure your paths correctly.
