### ISSUE TITLE
Suggestion: Additional Permissions

### ISSUE THREAD

**Issue by Ev3nflow** [citizenfx/txAdmin#290]
Is it possible to add permission to the other pages such as the resources and diagnostics? I have moderators who I wish to give access to the warn/kick/ban options but they don't need any other pages.

Thanks.

**Comment by n0tsiege** [comment]
Warn, kick, and ban are all their own permissions already... look through the options before you open an issue.

**Comment by Ev3nflow** [comment]
Perhaps you should read before you reply to an issue. That's very clear, however, the very first sentence says "Is it possible to add permission to the other pages such as the resources and diagnostics?"

**Comment by n0tsiege** [comment]
I'm fully aware of what you said, I'm not here to be a dick, but you mentioned warn, kick, and ban, which already exist. The others, I agree with.

**Comment by Ev3nflow** [comment]
Thank you, I suppose I should have worded it better. That's correct, I can give them warn/kick/ban, but I don't necessarily want them even seeing the list of resources, especially those that aren't running in case I'm prepping a surprise resource, for example. In that case, I'd like the opportunity to restrict those pages as well.

**Comment by tabarra** [comment]
All the running resources are already public, you can see which server is running which resource pretty easily. This does not apply for stopped resources tho.  
The diagnostics page do not contain any sensitive information, at most the name of your user profile?!  
  
But let's be honest here, if you don't trust your moderators to know the stopped resources you have, then you have bigger problems than txAdmin permissions.  
If I wanted, I could add 500 different permissions to the system, but this would just result in people giving "All Permissions" to their admins, and we don't want that do we?
