### ISSUE TITLE
[Request] Server Log persistence and retrieval endpoint.

### ISSUE THREAD

**Issue by abhishekdeshkar** [citizenfx/txAdmin#295]
Hi there,

Is there any way to store all the logs that we can see on ```http://LOG_URL/serverLog``` ?

I would like to analyse logs later. couldn't find way to store all the logs.

Thanks!

**Comment by tabarra** [comment]
Not yet.  
Will keep this issue open for now as a TODO and maybe a way to get some feedback.

**Comment by wilywork** [comment]
rename old file fxserver.log to fxserver_data.log and create new file fxserver.log

**Comment by tabarra** [comment]
Release v4.6 will have log persistence in the logs folder, the next update will have a way for you to download it.
