### ISSUE TITLE
Show the license that is banned.

### ISSUE THREAD

**Issue by YpsilonTM** [citizenfx/txAdmin#296]
If you now ban someone that wasn't online it just shows `BANNED license` so I have no clue who got banned. Maybe a was to show details if you click on it or show a license number.

![image](https://user-images.githubusercontent.com/22861150/109708739-160d0a00-7b9c-11eb-89fb-de5b26660286.png)

**Comment by tabarra** [comment]
I know its not ideal, but clicking on every ban to find which one to unban is also not very good UX.  
Because of that, if you already have an identifier (like license), you can just paste it in the search box and let txAdmin do the magic for you.
