### ISSUE TITLE
add steam hex for addwl

### ISSUE THREAD

**Issue by Andrea-98** [citizenfx/txAdmin#299]
It is possible to introduce steam hex to add players to the whitelist via the addwl command

**Comment by tabarra** [comment]
Not possible.  
And why not use the Request ID? 10x easier...

**Comment by Andrea-98** [comment]
because in this way I can add the player even while it is not online (to enter the server you currently have to be whitlisted via a verified role on dicord, the txserver whitelist I wanted to use as a second connection factor) and I can easily return to the database on any resource (example : I add a player to the whitelist and by means of a sciprt I copy the steam hex in vmenu and esx database enabling the basic commands, currently I should do it by hand and not use the whitelist system integrated in txadmin). How come it is not possible to add this thing?

**Comment by tabarra** [comment]
Please use our discord for discussions.
