### ISSUE TITLE
Suggestion: Whitelist Changes

### ISSUE THREAD

**Issue by zugg-zugg** [citizenfx/txAdmin#300]
Pending whitelist requests only show Username and ID.  It would be nice to see more information on the applicant such as the Steam or FiveM ID if possible.  

Secondly, I'd request a Reject/Deny button be added to clear the whitelist requests you know are not legitimate.

Thank you

**Comment by tabarra** [comment]
1. we don't have all that space in the interface
2. reject or deny doesn't make sense and has many innumerous issues with it... just ignore the people you don't want to allow
3. the main whitelist method is by whitelist request id... ask the player what's his id then you can whitelist him on the interface or using `/addwl <id>`... easier isn't it?

**Comment by zugg-zugg** [comment]
Asking a player, to confirm a random ID they get once when connecting and then logging into the interface and having to confirm is not easier but sure.

**Comment by matsn0w** [comment]
I think having the possibility to at least visually remove an entry from the whitelist would be very nice. Can become quite cluttered after a while.
