### ISSUE TITLE
I need help to upgrade txadmin fom 3.3.0 to the the new version...

### ISSUE THREAD

**Issue by Kathou99** [citizenfx/txAdmin#304]
I can't join your discord...

my discord:🌷🎀𝒦𝒶𝓉𝒽𝑜𝓊𝒬𝒞🎀💎#3838

**Comment by Kathou99** [comment]
<img width="1074" alt="whatttt" src="https://user-images.githubusercontent.com/71993497/110806498-1ec2a780-8250-11eb-9c31-5482b232fc8d.PNG">
In english is Impossible to join the server...and on my phone discord said I was ban...

**Comment by n0tsiege** [comment]
Download artifacts version 3622 or higher and it comes included. Here are the links:
[Windows] https://runtime.fivem.net/artifacts/fivem/build_server_windows/master/3622-a1cd64b01533704dde6fe5b43d85321c3336fef0/server.7z
[Linux] https://runtime.fivem.net/artifacts/fivem/build_proot_linux/master/3622-a1cd64b01533704dde6fe5b43d85321c3336fef0/fx.tar.xz
Those are 3622 but anything at that artifact or newer has v3.4.0 included. Here's an invite to the discord: https://discord.gg/CN7gVKDaMk

**Comment by PLOKMJNB** [comment]
There is no ban by your username unless you were previously banned and made a new account.

**Comment by Kathou99** [comment]
my older acount has ben hack like last two month so maybe is this one the name of the old account is ajajan dhaj I didn't remember the # digit,in less two hour my computer got infected by a token grabber so...I had make a new account a reformating the computer..
