### ISSUE TITLE
What The Fork?

### ISSUE THREAD

**Issue by ghost** [citizenfx/txAdmin#305]
I was banned from the discord server and I'm just confused why? Would like to contribute to the project if I can but goat hates me.
![image](https://user-images.githubusercontent.com/2265553/111043327-fa152e00-840f-11eb-976d-f3c2a3c04b68.png)

**Comment by w33ts** [comment]
This is for legitimate issues with the txAdmin program. You can still contribute without Discord access.

You were banned for your general attitude and comments made.
