### ISSUE TITLE
[Request] Log custom command: Give source parameter

### ISSUE THREAD

**Issue by melonenmario** [citizenfx/txAdmin#306]
Hey, the feature to log custom commands is nice but doesn't work perfect. You use the global.source, but that doens't work well with Register Command (Serversided). TxAdmin write in the log "Unknown executed..." You can ad an new command wich gives a source paramter to txAdmin:

**Suggestion:** _\n\n\n\nonNet('txaLogger:CommandExecutedSource', (source, data) => {\n    try {\n        logger.r(source, 'CommandExecuted', data);_

**In the script:** _TriggerEvent('txaLogger:CommandExecutedSource', source, rawCommand)_

Thanks a lot!

**Comment by tabarra** [comment]
It is done like that on purpose, you need to call it from the Client script.  
I know this is "incomplete", but at least this way when there is an source to the command, you know its correct.  
  
This system is due to improvements soon.

**Comment by melonenmario** [comment]
Yes i know, that I have to call them from the client, but most of the commands work serversided and it makes no sense to write them client only for TxAdmin.

But thanks for the answer :)
