### ISSUE TITLE
Resource Restart Refresh

### ISSUE THREAD

**Issue by NoxideLive** [citizenfx/txAdmin#317]
Why do you refresh the page on resource restart?

Please remove this as this makes development with restarting constantly annoying because you don't keep scroll position.

**Comment by tabarra** [comment]
Feel free to pull request an XHR-reloaded resource list.  
I don't want to code that.

**Comment by NoxideLive** [comment]
Expect it soon

**Comment by HypeLevels** [comment]
> Expect it soon

Expect your PR soon
