### ISSUE TITLE
Invalid session

### ISSUE THREAD

**Issue by rigomatuja** [citizenfx/txAdmin#322]
Hi there, first to thankyou for this great tool.
I am mounting a new server using this, and is impossible due to "invalid Session" error. I tried with several different artifact server versions, all browsers installed all with same results.
![imagen](https://user-images.githubusercontent.com/3653610/114750000-cea99a00-9d53-11eb-974e-38219a5dbdab.png)

**Comment by Arm-0001** [comment]
Please tell me what artifact this is so i can try to repro

**Comment by rigomatuja** [comment]
> Please tell me what artifact this is so i can try to repro

it happened to me with several different versions, the last tried was the 3784.  I solved it with the help channel in txadmin discord, replacing the admins.json file. Besides i am having issues with server deployer once i am trying to set up a new server using a non local database server, it always overrides whatever i type on the input field with the vps ip. Even once installed (with 3784 version): 
![imagen](https://user-images.githubusercontent.com/3653610/115044912-469fcd80-9ed6-11eb-9cb4-48506afe2f8e.png)

**Comment by rigomatuja** [comment]
> 
> 
> > Please tell me what artifact this is so i can try to repro
> 
> it happened to me with several different versions, the last tried was the 3784. I solved it with the help channel in txadmin discord, replacing the admins.json file. Besides i am having issues with server deployer once i am trying to set up a new server using a non local database server, it always overrides whatever i type on the input field with the vps ip. Even once installed (with 3784 version):
> ![imagen](https://user-images.githubusercontent.com/3653610/115044912-469fcd80-9ed6-11eb-9cb4-48506afe2f8e.png)

if i copy an old installatioon txdata folder it works, so it is just happening (at least for me) when creating a new server using plume template, or cfx base template (have not tried others)

**Comment by tabarra** [comment]
Closed by 0b5cab782a768d769cf02001cd95e42841c7f832
