### ISSUE TITLE
Suggestion: Saving all identifiers

### ISSUE THREAD

**Issue by IqFiskMos** [citizenfx/txAdmin#328]
It would be nice so be able to save allt identifiers for a player not just the license when they are offline.
When they play i can see all but not when offline. Please make it possible to save them all

Player Identifiers:
steam:,
license:,
xbl:,
live:,
discord:,
fivem:

**Comment by czsquizer** [comment]
It would be cool, but ...

**Comment by n0tsiege** [comment]
Your best bet would be to open a Pull Request with this code as the commit, if you know how 🙂

**Comment by tabarra** [comment]
This will be done, for now I'm closing this as duplicate of #385, thanks for the suggestion.
