### ISSUE TITLE
Impossible to create new profile 

### ISSUE THREAD

**Issue by Kathou99** [citizenfx/txAdmin#329]
I had try 426 ways all the time I had try to do it's said Invalid session
![bugggggggg](https://user-images.githubusercontent.com/71993497/115962833-26ca6400-a4eb-11eb-8b54-07152aa69651.PNG)

The version is  of fivem artifact:3854

**Comment by ElusionPDX** [comment]
I have this same issue. fresh server running on my local PC for testing stuff before pushing to live and cant get tx to let me set it up

**Comment by PLOKMJNB** [comment]
Please remember to use the Discord for support, there is fix which can be found pinned in the support channel

**Comment by Kathou99** [comment]
I am ban from the discord server so I can't acess🙄
-------- Message d'origine --------De : Danish Khan ***@***.***> Date : 2021-04-24  18 h 19  (GMT-05:00) À : tabarra/txAdmin ***@***.***> Cc : Kathou99 ***@***.***>, Author ***@***.***> Objet : Re: [tabarra/txAdmin] Impossible to create new profile  (#329) 
Please remember to use the Discord for support, there is fix which can be found pinned in the support channel
