### ISSUE TITLE
-- [Server Notice: hostname_rework]

### ISSUE THREAD

**Issue by GasparMPereira** [citizenfx/txAdmin#331]
Not a issue (i think), but what is this?
![image](https://user-images.githubusercontent.com/71574610/116305336-8d75a900-a79b-11eb-884e-c8ff736ab001.png)

**Comment by PLOKMJNB** [comment]
Thats probably a notice sent by cfx

**Comment by GasparMPereira** [comment]
> Thats probably a notice sent by cfx

What i need to do to solve this?

**Comment by PLOKMJNB** [comment]
> > Thats probably a notice sent by cfx
> 
> What i need to do to solve this?

Set the new name convars listed right below that message

**Comment by Gasparpereira2004** [comment]
But these scripts have nothing to do with error, (i think)

A terça, 27/04/2021, 21:02, Danish Khan ***@***.***> escreveu:
