### ISSUE TITLE
[Suggestion]: Database in TxAdmin

### ISSUE THREAD

**Issue by prawn185** [citizenfx/txAdmin#333]
It would be really useful if you could traverse the database within TxAdmin.

I'm happy to contribute if I can

**Comment by Arm-0001** [comment]
ofcourse you can contribute! thats why its on github :)

**Comment by tabarra** [comment]
which database? you mean the txadmin whitelist, bans and etc?

**Comment by rpiadam** [comment]
can add super admin in?
