### ISSUE TITLE
Error on start-up, causing the server to crash/reload every few mins

### ISSUE THREAD

**Issue by ThatGuyJacobee** [citizenfx/txAdmin#345]
Hi there,
So, I've been getting an issue that began after updating FXServer to latest version.
In console I've been receiving a "Logger upload fail" error constantly spamming every few secs.
Moreover, after few mins the server crashes and restarts by itself.
I've attached a picture of the error. If anything else I required such as logs let me know 😄
Thanks.
![](https://cdn.discordapp.com/attachments/807278696611184650/843109099738628106/unknown.png)

**Comment by Arm-0001** [comment]
Did you put txadmin in the resource folder? if yes dont do that. Also use the discord for support https://discord.gg/pFr29wzYB2

**Comment by ThatGuyJacobee** [comment]
Nope don't have it in resource folder. Ahh okay I'll go to the discord support thanks 😀
