### ISSUE TITLE
script error

### ISSUE THREAD

**Issue by maicek** [citizenfx/txAdmin#347]
![image](https://user-images.githubusercontent.com/46402692/118702851-bd055780-b815-11eb-8b95-39b69034e008.png)

Errors after updating txadmin with artiffacts

v3.8.0 atop FXServer 3961

**Comment by tabarra** [comment]
Its known, will be solved in a week.  
This is minor.

**Comment by MossyOak20009** [comment]
does this make your game crash cuz its making mine crash?

**Comment by tabarra** [comment]
> does this make your game crash cuz its making mine crash?

No, this is not making your server crash.
