### ISSUE TITLE
attempt to compare string with number

### ISSUE THREAD

**Issue by dunak-debug** [citizenfx/txAdmin#348]
`[      script:monitor] SCRIPT ERROR: @monitor/scripts/sv_logger.lua:17: attempt to compare string with number
[      script:monitor] > logger (@monitor/scripts/sv_logger.lua:35)
[      script:monitor] > handler (@monitor/scripts/sv_logger.lua:88)`

spamming this error in console, 
v3.8.0 atop FXServer 3970

**Comment by wowjeeez** [comment]
@synterrr SMH

**Comment by Arm-0001** [comment]
duplicate of https://github.com/tabarra/txAdmin/issues/347

**Comment by tabarra** [comment]
Known.  
Solved already, wait for the v4 release.
