### ISSUE TITLE
Replace browser alert() and prompt() with a JS equivalent

### ISSUE THREAD

**Issue by GoatG33k** [citizenfx/txAdmin#355]
These functions currently do nothing in NUI, and a JS solution would likely look better in general for both browser and menu.

**Comment by TasoOneAsia** [comment]
Has been started with this commit 490559e50f311986e29010cd71219da8a2729699

**Comment by TasoOneAsia** [comment]
Fixed with 6f3844bc045c942e738fcdda6978578caeef3e2a
