### ISSUE TITLE
Enhancement: Reorganize History/Actions, vice-versa Panel

### ISSUE THREAD

**Issue by ADASfmt** [citizenfx/txAdmin#357]
So I know this isn't really an issue but I've been recommended to use this platform instead.

  We initially started our server with txadmin but as time went by we felt like we needed something else. Our primary concerns were that we needed a ban system in-game for faster bans (We now know that a menu is in the works and we love the NUI). The second one was definitely how the player's actions (and overall) and the history were organized. It looks confusing and even though some adapted, others didn't.
  Our staff felt like making our own discord embeds was much easier to identify bans/warnings/kicks and the reasons for such.
  So I've come here to offer the suggestion to change the "css?" to something that other people can easily track and as an attachment, we selected our embeds in order to show the team what my colleagues found "easier" to work with.
  
  PS: I'm not criticizing the work and I really appreciate what you guys do. 
       Also, time and date are missing in the examples given due to discord's ability to do so (Which is fundamental to have)(Language: Portuguese)
![Unban](https://user-images.githubusercontent.com/85000402/120053688-96b89680-c023-11eb-8ec0-2c09763e2a54.png)

![Kick](https://user-images.githubusercontent.com/85000402/120053657-53f6be80-c023-11eb-8f60-7c478ecf7122.png)

![Ban](https://user-images.githubusercontent.com/85000402/120053617-15f99a80-c023-11eb-8699-478b3a6a83ab.png)

**Comment by tabarra** [comment]
I'm looking to improve the player's page for a long time.  
Do you have any specific suggestions?  
I already thought about separating players and actions search in separate pages, make them a table-ish with pagination.

**Comment by ADASfmt** [comment]
Besides my attachments, maybe just the search tool to have a feature that you can search for specific words.

For example search for the reason's text or a specific word (like discord's feature, but improved = Google's CTRL + F)
Designs itself ain't much my thing. I could do some drawings in Illustrator but there are better programs to draw web designs (like inDesign) in which I'm not competent enough.

**Comment by tabarra** [comment]
The players/actions page will be refactored.  
This gh issue sounds a bit old, since then we rolled out the menu, therefore I'm closing this issue.  
Thanks for the suggestion.
