### ISSUE TITLE
Suggestions: add temporary bans 

### ISSUE THREAD

**Issue by Arm-0001** [citizenfx/txAdmin#358]
This feature would be useful for big servers as its annoying to keep track of each ban and unban the players

**Comment by NonStopGamer** [comment]
![chrome_nQlUSbscKP](https://user-images.githubusercontent.com/45131034/120077864-84b61280-c07a-11eb-8eac-acf1cdce7654.png)

**Comment by TasoOneAsia** [comment]
nice

**Comment by n0tsiege** [comment]
hamy you're a donut😂
