### ISSUE TITLE
domain

### ISSUE THREAD

**Issue by kFxDaKing** [citizenfx/txAdmin#36]
Hello, i have own server domain, how to use it instead of ip:40120

**Comment by tabarra** [comment]
Just point it to your server IP.  
You are still going to need the :40120 at the end.  
This is networking stuff and unrelated to txAdmin itself.

**Comment by tristencrp** [comment]
Pointing as in CNAME or forwarding? Sorry; new to DNS config.

**Comment by tabarra** [comment]
@tristencrp  use our discord for support
