### ISSUE TITLE
Suggestion: Ability to disable commands & the discord status

### ISSUE THREAD

**Issue by DamonOnYT** [citizenfx/txAdmin#364]
Self-explanatory by the title, the ability to disable the Discord Bot Commands & The Discord Commands would be amazing. Majority of the stuff my community uses in terms of bots is custom and having txadmin's discord status and commands tends to interfere with that stuff

**Comment by n0tsiege** [comment]
You can either: A) entirely disable/remove the bot, ot b) make the prefix so incredibly long and hard to guess that nobody would get it.

**Comment by PLOKMJNB** [comment]
Then simply remove your token from the settings page.

**Comment by tabarra** [comment]
As above, you can:
- Disable the bot;
- Change prefix;
- Or even just remove his permission to speak in any channel that is not the server status one.
