### ISSUE TITLE
Question: Why is txAdmin's latest stable version async from FXServer's artifacts?

### ISSUE THREAD

**Issue by crocokyle** [citizenfx/txAdmin#368]
Less of an issue and just curious why txAdmin's latest stable version is not in line with Latest Stable from the artifacts site? 

I currently use a CI/CD pipeline to build a docker image for our FiveM server that runs daily. If the latest stable artifact changes, it updates the base image with the artifact build number. It also stores images with previous FXServer artifacts so we can roll back if needed. Today I noticed that txAdmin is prompting for an update when running on 3922 and I see that txAdmin is recommending 4022. 

Just wondering what the logic here is and whether I should modify my CI/CD configuration?

**Comment by tabarra** [comment]
That's because txAdmin is just one part of fxserver, and it being stable does not mean that fxserver at that version will also be stable.  
Generally, all txAdmin releases are considered stable, but this time CitizenFX will only update the Latest Recommended in the next update, since the txAdmin menu is currently in beta, which doesn't seem much, but for the menu to work, we are using some cutting edge features from fxserver that are actually untested, like the way to webpipe http requests from the NUI to the fxserver.  
  
I'm closing this issue, but feel free to comment more.

**Comment by aidenzybell** [comment]
FiveM's Artifact website is heavily cached and not constantly updated, the way I like to know the most "stable" version is to check the FiveM changelog either in the client or on the server's website, which shows the latest version production clients of FiveM are running on, currently anyone playing FiveM is running on build 4011, so personally, I would update my server to 4011, just to stay in sync with what *most* are currently using, if someone is running the canary build though they would be using build 4042 now. 

Changelog:
https://servers.fivem.net/changelog

You can get the latest artifact by doing !artifact in the txAdmin Discord:
https://runtime.fivem.net/artifacts/fivem/build_server_windows/master/?646_fix_cache_4042

This is just how I would personally update my server as I know the "recommended" button on the artifacts page is not constantly updated and can sometimes fall months behind what is really recommended.

**Comment by crocokyle** [comment]
Ah I see, thank you both for the replies. That is exactly how I'm getting the latest build number at the moment. Something like 
```bash
echo "BUILD_VERSION=$(curl https://runtime.fivem.net/artifacts/fivem/build_proot_linux/master/ | grep "LATEST RECOMMENDED" | grep -oP "\d{4}")" > build.env
```
Sounds like this may not be the most reliable solution :)

**Comment by tabarra** [comment]
You can also do:
```
https://changelogs-live.fivem.net/api/changelog/versions/linux/server?someRandomBs
```

**Comment by crocokyle** [comment]
Thanks! That looks a little cleaner
