### ISSUE TITLE
Timeout

### ISSUE THREAD

**Issue by kFxDaKing** [citizenfx/txAdmin#37]
Everyting is working fine, i love this.

But server was running for 20-30 minutes, and it timeout without error.

https://imgur.com/a/fAq2gEh

**Comment by kFxDaKing** [comment]
Server is online, but tx admin is off, cant use the panel.

**Comment by kFxDaKing** [comment]
When i type "check txAdminClient" in console, it works again.

**Comment by tabarra** [comment]
Go to the settings of CMD (both properties and defaults) and disable QuickEdit mode.  
Also, please join our discord server for more support.
