### ISSUE TITLE
FXServer crash: Assertion `(request_waiting_) >= (0)` failed

### ISSUE THREAD

**Issue by itsfaizy** [citizenfx/txAdmin#374]
txAdmin Console runs into the error (see image 2), this stop txadmin processes (webpage, in-game become inaccessible, and txban ban/whitelisting check when joining all stop working, rendering the server unjoinable). This issue has been persistent in all recent builds (currently running 4114 and still running into the issue, images may be a few days old but the error is the same.)

![unknown (1)](https://user-images.githubusercontent.com/46767055/122866881-13772180-d2ff-11eb-9659-8c1817ed72f5.png)
![unknown (2)](https://user-images.githubusercontent.com/46767055/122867143-72d53180-d2ff-11eb-8723-a3a026c14bac.png)

**Comment by tabarra** [comment]
Stale.
