### ISSUE TITLE
FX server dont start

### ISSUE THREAD

**Issue by einfachJanex** [citizenfx/txAdmin#375]
Im trying to install FiveM on my Linux server the problem is  a eror please help me
![Bild_2021-06-23_134045](https://user-images.githubusercontent.com/86356242/123090586-9c3dac80-d428-11eb-8f61-232a17ea1188.png)

**Comment by Arm-0001** [comment]
use our discord for support not github https://discord.gg/FcUK56md

**Comment by tabarra** [comment]
Probably no memory available.  
Either ways this is an issue with the child fxserver and not txAdmin.

**Comment by einfachJanex** [comment]
Ok thank you
