### ISSUE TITLE
Key validation does not work with new CFX key format.

### ISSUE THREAD

**Issue by The-Neco** [citizenfx/txAdmin#377]
The new CFX key format does not match the requirements of the following regex query:

https://github.com/tabarra/txAdmin/blob/e13f716b97f444f694eb5aba754c8d6eef483563/web/basic/deployer.html#L412

Therefore leading to this error:
![image](https://user-images.githubusercontent.com/13007790/123557196-76e1d300-d787-11eb-8fde-e691096936d5.png)

New format for reference: 
`cfxk_1kDPPvLBZmXOUehqU7utw_4PGjtG`

**Comment by tabarra** [comment]
Yeah bubble just pinged me hahahaha.  
Will be fixed shortly.
