### ISSUE TITLE
Suggestions: Menu Notifications

### ISSUE THREAD

**Issue by chrislenga** [citizenfx/txAdmin#380]
#1 -- Create a setting where we can customize how long an announcement is displayed on the server. Range it from say 15-60 seconds for example. Obviously not too high, to avoid performance issues on the client. 

#2 -- Make the noclip notification either movable or only appear for a certain amount of time. Seeing it constantly on the screen gets problematic. Also: We've encountered a bug where you have to type tx in the console to get out of noclip.

**Comment by TasoOneAsia** [comment]
To your first suggestion, announcement display time is now dynamically determined according to the length of the message sent.

To your second suggestion/bug. The bug has been fixed in the latest release. With your noclip suggestion, I can add a convar to disable persistent player mode notifications but @tabarra might have some input as well

**Comment by chrislenga** [comment]
> To your first suggestion, announcement display time is now dynamically determined according to the length of the message sent.
> 
> To your second suggestion/bug. The bug has been fixed in the latest release. With your noclip suggestion, I can add a convar to disable persistent player mode notifications but @tabarra might have some input as well

Sounds great! I bring that up, as many servers (including ours) have a logo in the top right and this notification obstructs it out of the box.

**Comment by tabarra** [comment]
1. Announcement times used to be fixed, and in v4.3 its bugged so it may last less than a second. But for the next update it will work dynamically and be clamped between 5 and 20 seconds.
2. What if its in the default position (center bottom)? The chat not opening in noclip has been solved in v4.3 thanks to Taso.

**Comment by chrislenga** [comment]
> 1. Announcement times used to be fixed, and in v4.3 its bugged so it may last less than a second. But for the next update it will work dynamically and be clamped between 5 and 20 seconds.
> 2. What if its in the default position (center bottom)? The chat not opening in noclip has been solved in v4.3 thanks to Taso.

In all the servers I've developed for and even ours, the bottom center actually seems like a neutral space. Sure, some huds are there, but I don't think you'll be worrying about health and armor when you're in noclip, at least I hope not! :D

**Comment by tabarra** [comment]
Since at the bottom it was interfering with  the scaleform, I set it to top center.
