### ISSUE TITLE
Suggestion: Who's Talking?

### ISSUE THREAD

**Issue by chrislenga** [citizenfx/txAdmin#381]
Something that is quite helpful, is knowing who's speaking via voice in-game. Not too many scripts out there that have this functionality anymore, and those that do, don't exactly work the best. Implementing this in with the menu system would be super ideal. Perhaps even make it so the prefix can be customized when displaying in-game.

**Comment by TasoOneAsia** [comment]
This is currently implemented in the menu when toggling the player id’s
