### ISSUE TITLE
Suggestion: Add Heading (Copy Coords Function)

### ISSUE THREAD

**Issue by chrislenga** [citizenfx/txAdmin#383]
Heading can often be important in a development aspect and should be included. :)

**Comment by TasoOneAsia** [comment]
Easy enough to do, I’ll add it in. I wonder if our tp to coords function also accepts vector4 coords as well, if not I’ll add it to our trello board.

**Comment by tabarra** [comment]
Closed by 8a97abb96f3c945d6f233a907d87740dca31e842.
