### ISSUE TITLE
Suggestion: Client Screenshots

### ISSUE THREAD

**Issue by chrislenga** [citizenfx/txAdmin#387]
There are a few menus out there, that when toggled, will take a screenshot of the players' screen and hud, and then either send it to an FTP upload script or post via webhook to Discord. Definitely a feature we use a lot to catch cheaters, hackers, and modders. The ability to screenshot an entire server is also key, for those moments you have a modder and not sure who it is.

Perhaps if the Discord piece is too much strain/stress on the plugin and script, maybe a temporary archive accessible from within txAdmin that stores photos. {Might also be too intensive for the resource}

**Comment by tabarra** [comment]
Oof, I really don't want this.  
Having to deal with upload apis, configs, UI and etc is so much of a pain...
