### ISSUE TITLE
Suggestion: Spectator Cycle

### ISSUE THREAD

**Issue by chrislenga** [citizenfx/txAdmin#389]
Say you want to start a spectator session in search of a modder. You initiate a spectate on one player, and then you cycle through the players on the server using a button on the UI, or a hotkey. This would in theory enable you to flip through and see the players on the server by using a hotkey such as left or right arrow key. 

Then depending on the player you're spectating, you have a way to initiate a secondary menu, or additional options where you can action said player you're spectating easily... Such as kick or ban of the user you're spectating.

**Comment by tabarra** [comment]
+1

**Comment by tabarra** [comment]
Done in #591.
