### ISSUE TITLE
Suggestion: Timed Announcements/Chat Messages

### ISSUE THREAD

**Issue by chrislenga** [citizenfx/txAdmin#390]
Right now for our servers, we use two completely separate resources for each function. 

The First would be something server owners can set where a timed announcement (top right) happens on intervals we set, or a timed chat message (standard chat) that we specify. 

This could also have some presets created and used, for example, a set message that advises users every 15 minutes to /report {id} {reason} if they need an admin, or perhaps one that lists the current staff online to assist, or even something as simple as a random notification of an event that might be happening soon.

**Comment by tabarra** [comment]
Doable, but the settings UI for this looks annoying, as well as the backend config save.

**Comment by tabarra** [comment]
Decided against this feature.

**Comment by yorick2002** [comment]
> 466878

This aint the place to put your txAdmin pin buddy
