### ISSUE TITLE
Suggestion: Staff Online

### ISSUE THREAD

**Issue by chrislenga** [citizenfx/txAdmin#391]
Right now, almost no system that I'm aware of offers a way to see what staff are currently online. My suggestion would be to implement two separate systems. 

1- Star or some type of an emoji identifying a user as a staff member on the players' tab, or perhaps coloring their name a certain way that differentiates them from the rest of the users. While we keep a pretty tight ship when it comes to keeping staff names the same in-game and on Discord, many servers have staff name changes regularly. For these servers, it could be hard to determine which staff are online, and how many are. 

2- An actual tab that lists all of the staff on that server and their online/offline status, as well as a last seen tooltip that we can see without clicking into the users' profile. Perhaps a hover-over option or simply listing it below the name. 

Both systems will be a tremendous help for larger servers, such as ours, where we have 30-40 people (or more) on txAdmin. Instead of visiting each player individually, being able to see all from a birds-eye view will speed up staff management responsibilities.

**Comment by tabarra** [comment]
Let's go with option 1.

**Comment by tabarra** [comment]
@TasoOneAsia I added a small shield next to the name, but I think it would be better if we set the color to yellow or something like that.  
I tried and failed to do that in the MUI Theme.  
Can you please have a look?

![image](https://user-images.githubusercontent.com/1808295/139538226-432986d3-8f77-49a0-8ee3-ffa066979fe2.png)

**Comment by TasoOneAsia** [comment]
Implemented with edbafcdbe637b78a0f6be716901571a32ec1bdfe
