### ISSUE TITLE
Suggestion: Multiple txAdmin Logins (Same Time)

### ISSUE THREAD

**Issue by chrislenga** [citizenfx/txAdmin#395]
As you know, we run several servers, and we're deploying a situation where it's the same core IP, different ports, for each of the txadmin installs. We're running into a problem, however, where on the same browser, we can only log in to one of them at a time. I'm sure many are in the same boat as I, and I've looked around support-wise, didn't really see anything. Everything walks you through how to set multiples up but doesn't cover being logged into multiple. 

Scenario: I'd like to be logged into five txAdmins (different servers) at the same time, where I can park that browser with tabs for each server on one of my external monitors, and scan through it at times.

**Comment by PLOKMJNB** [comment]
Im able to login and use 3 at the same time independently, probably more if I started more. These are all running on the same machine routed to different ports and subdomains.
![image](https://khan.iodine.gg/8fch6.png)

**Comment by Arm-0001** [comment]
> Im able to login and use 3 at the same time independently, probably more if I started more. These are all running on the same machine routed to different ports and subdomains.
> ![image](https://camo.githubusercontent.com/0943df6529eb42ee1ef9e28a26f215ec029434b2beb45104a76c372b5daa1c40/68747470733a2f2f6b68616e2e696f64696e652e67672f38666368362e706e67)

can you try using ip directly

**Comment by chrislenga** [comment]
> Im able to login and use 3 at the same time independently, probably more if I started more. These are all running on the same machine routed to different ports and subdomains.
> ![image](https://camo.githubusercontent.com/0943df6529eb42ee1ef9e28a26f215ec029434b2beb45104a76c372b5daa1c40/68747470733a2f2f6b68616e2e696f64696e652e67672f38666368362e706e67)

How are you routing to different ports with your setup? I don't see any port numbers there. I will do some testing on my end and report back my findings a few different ways.

**Comment by PLOKMJNB** [comment]
using ports works just the same
![gif](https://khan.iodine.gg/d10j9.gif)

**Comment by chrislenga** [comment]
My current setup is this. 

http://txadmin.ise.gg:40120
http://txadmin.ise.gg:40121

I'm using a records obviously, being sent to the same ip address as its easier for our setup load-wise. Other than srv records, which I don't think you can use on this, I'm eager to find out how your running different ports with a nice clean url.

**Comment by ChrisLenga** [comment]
This is what I run into problem wise. https://gyazo.com/42c09cf766e7ef4ed90e37dcb35e8388

**Comment by PLOKMJNB** [comment]
Try using password and username instead of cfx.re

**Comment by chrislenga** [comment]
This is my problem. 

https://user-images.githubusercontent.com/15137702/124272708-1cd96880-db0d-11eb-96cf-f1e86be0f5d4.mp4

**Comment by chrislenga** [comment]
> Try using password and username instead of cfx.re

I'll try that.

**Comment by tabarra** [comment]
Nope, that won't work because from the browser's cookie perspective, they are both the same site since the browser ignores the port.  
Infortunately that's part of the spec, and probably nothing I can do to solve.  
  
If you check plok's screenshot, he set different domains for the different txadmins.

**Comment by chrislenga** [comment]
> Nope, that won't work because from the browser's cookie perspective, they are both the same site since the browser ignores the port.
> Infortunately that's part of the spec, and probably nothing I can do to solve.
> 
> If you check plok's screenshot, he set different domains for the different txadmins.

Yeah, sadly no difference, as you expected. 

Plok, how did you get the url without a port for both of yours? the only method I'm aware of is srv records, but tx doesn't support them, at least I thought?

**Comment by PLOKMJNB** [comment]
> Plok, how did you get the url without a port for both of yours? the only method I'm aware of is srv records, but tx doesn't support them, at least I thought?

I did it via internal routing, setting up an nginx reverse proxy should get you the same result

**Comment by chrislenga** [comment]
> > Plok, how did you get the url without a port for both of yours? the only method I'm aware of is srv records, but tx doesn't support them, at least I thought?
> 
> I did it via internal routing, setting up an nginx reverse proxy should get you the same result

Thanks. I'll do some toying around with this concept.

**Comment by tabarra** [comment]
Okay, I just tested and you can login to two txadmin on the same ip at the same time, AS LONG AS they do not have the same  profile name.   
I'm pushing an update to take into consideration the path as well.
