### ISSUE TITLE
Suggestion: Kick in Last 20 Actions

### ISSUE THREAD

**Issue by fbigrs** [citizenfx/txAdmin#396]
Hey,

I would really like that Kicks could also be shown in the Last 20 Actions in the Players Tab, or implement a Setting to enable/Disable it to be shown in the Last 20 Action.

Best Regards,
Fabi

**Comment by chrislenga** [comment]
This is an awesome idea. +1

**Comment by tabarra** [comment]
Unfortunately that's just not how the database works.  
We do have kick logs tho, check the txAdmin Log page.  
  
This not not a "no", but definitely a "not planned".
