### ISSUE TITLE
Interface Rework discussion thread.

### ISSUE THREAD

**Issue by tabarra** [citizenfx/txAdmin#4]
**It's pretty clear the interface rework is a bit overdue.**  
To help organize and future-proof the enhancements, I would like to share what I see in the near-future of FXAdmin:
* Separate the admin log to another window
* Separate server Start/Stop/Restart from the other commands and add a confirmation modal.
* Adding a separate window or tab to show some configs from your `server.json`
* Statistics plotter window with charts for hitch detection, playercount and possibly more. This can even be in the home screen depending on the design
* Simple menu with the available windows + logout link

One of the most important factors to consider is that the playerlist might have no players, or up to 64 (or more!?) players, so responsiveness is quite essential.  
  
**What do you guys think?**

**Comment by CTRL-ALT-E** [comment]
I think all of those sound like great ideas. If I can be of any assistance let me know as I am a web dev.

**Comment by Javier-Diez** [comment]
Agree, also you could optimize with IOS and smaller resolutions.

**Comment by Trsak** [comment]
Some more suggestions:
- Add player ID to player's list (for commands)
- Add admin name on auth page, so auth is made with both name and password

And definetly make whole UI responsive. I can help out with it.

**Comment by tabarra** [comment]
Player ID as in vRP player ID? Not possible unless using extensions/server resources.  
The IDs we currently have available are only the server connection ID. I don't know how ESX works, but probably the ID won't work for anything but kicking players.  
  
About the username, I might add that if/when I end up implementing permissions system.

**Comment by tabarra** [comment]
I was thinking about using CoreUI or AdminLTE for the redesign.  
Any suggestions on which (if any) to choose?  
https://adminlte.io/themes/AdminLTE/index2.html  
https://coreui.io/demo/#main.html

**Comment by FcON21** [comment]
hi when i do this command npm start server.json
this happens 
[txAdmin:Config Exporter] Unnable to load configuration file 'data/server.json'. (json parse error, please read the documentation)

**Comment by tabarra** [comment]
v1 is finally out with the new interface.  
Closing this thread.
