### ISSUE TITLE
Admins can see all without perms.

### ISSUE THREAD

**Issue by ghost** [citizenfx/txAdmin#404]
Hi, my admins can see all pages without perms to it... 
![image](https://user-images.githubusercontent.com/28512867/125852764-1ea3e244-792b-49ea-806b-da43677cf0b2.png)

**Comment by Arm-0001** [comment]
its normal that they can see the tabs but they shoudnt be able to see the actual content of the page

**Comment by tabarra** [comment]
Sorry, issue # 404 not found.

**Comment by ghost** [comment]
> its normal that they can see the tabs but they shoudnt be able to see the actual content of the page

They see all of the content on the pages, and also they can go to resources and restart them without perms.




> Sorry, issue # 404 not found.

Why..?

**Comment by Arm-0001** [comment]
> Why..?

it was a joke lol cause its issue number 404, try updating your txadmin and use discord for support

**Comment by tabarra** [comment]
Nobody ever related anything close to this.  
I'm pretty sure you are mistaken.  
  
Please either record a video as evidence, or provide a way for us to reproduce the issue.
