### ISSUE TITLE
Suggestion: Put Server Profile Name in the tab label

### ISSUE THREAD

**Issue by ConductorWon** [citizenfx/txAdmin#405]
Pretty much what the title says. I dev for a community with multiple servers and I have all of the different txAdmins open at the same time. It would be nice to see the Profile name in the tab label so I know what server I'm looking at at a quick glance instead of this
![image](https://user-images.githubusercontent.com/76677480/125990057-f59fcc79-fde6-4116-bd8f-274d61878e78.png)

**Comment by Arm-0001** [comment]
+1 very good idea

**Comment by JNordin96** [comment]
@ConductorWon or just open the tab and take a minute to READ?

**Comment by tabarra** [comment]
After over a year, it's finally done.  
Will be available at v4.18.0.  
![image](https://user-images.githubusercontent.com/1808295/189007685-e5e0b8d2-b613-4b63-9485-7a9c459a456e.png)

**Comment by tabarra** [comment]
Closed by 3f024df0ba03db55d70e4fed5b930d8118f37d41
