### ISSUE TITLE
Internal Error on Diagnostics Page

### ISSUE THREAD

**Issue by kurozavara** [citizenfx/txAdmin#406]
Updated to: 4210 Linux build and now getting this ONLY on Diagnostics page:

[txAdmin v4.4.1] Internal Error
Message: Cannot read property 'length' of null
Route: /diagnostics
Make sure your txAdmin is updated.

Any ideas what went wrong?
Everything else works fine.

**Comment by tabarra** [comment]
Can you please post a screenshot of the fxserver tab in the settings page?

**Comment by kurozavara** [comment]
![screen](https://user-images.githubusercontent.com/87549904/126014172-296ba8c1-7495-4898-a8b9-2b10da777313.png)

**Comment by tabarra** [comment]
try adding `+set foo bar` in the additional arguments, save it, and then try going to the diagnostics page again.  
  
Please let me know if it works.

**Comment by kurozavara** [comment]
Yep, that did the trick!
Thanks for your timely help!
Appreciate it.

**Comment by tabarra** [comment]
tks for the feedback, now I know the issue.

**Comment by kurozavara** [comment]
Welcome.
