### ISSUE TITLE
Suggestion: Add resources to config button

### ISSUE THREAD

**Issue by kubaPL41** [citizenfx/txAdmin#408]
Pretty much what the title says, add a button near the resources in resource manager (web panel) to automatically add a line to the config: `start/ensure resource`

**Comment by tabarra** [comment]
I have no clue what you trying to say.  
Can you please draw it for me?

**Comment by TasoOneAsia** [comment]
Seems like he wants a interface for dynamically inserting `ensure resource` into the server.cfg, if not already present. Not sure its worth the effort / precedent for such a simple thing

**Comment by tabarra** [comment]
Stale.
