### ISSUE TITLE
Suggestion: Separate unban permission

### ISSUE THREAD

**Issue by MauriceKlusch** [citizenfx/txAdmin#410]
In some cases users may have the performance to ban players but not to unban.
Would be a nice little feature if unbanning gets an extra permission.

**Comment by chrislenga** [comment]
This has been suggested already here: https://github.com/tabarra/txAdmin/issues/379

And I completely agree. This function is actually a make or break for our organization. We may not end up using txAdmin if we can't keep them separate, as that's how we currently have it set up with EasyAdmin.

**Comment by TasoOneAsia** [comment]
Duplicate of #379
