### ISSUE TITLE
Logs improvement (IDEA) 

### ISSUE THREAD

**Issue by djmetla** [citizenfx/txAdmin#412]
Hey, we using TX Admin daily and we love TXAdmin <3 but our logs have hundred megabytes and for debugging is a pretty pain. It is possible separate .log files per FXServer (re)start? When not, it is possible make this function?

- add separate log files by FXServer (re)start or user defined option
- add timestamp or [YYY-MM-DD HH:ii:ss] before every line when is message logged for better debugging

Thanks <3

**Comment by tabarra** [comment]
Done 50730f97c68d9d5eb4e4d3b6a7762f9e529a97bb.  
I've implemented logrotate in the fxserver and admin logs as well.
Server logs and console logs pending.  
![image](https://user-images.githubusercontent.com/1808295/133489694-2c24523f-68d0-4311-9d74-44c2cee561c3.png)  
  
- FXServer:
    - Recent: 64~128kb
    - Interval: 1d
    - maxFiles: 7
    - maxSize: 5G
