### ISSUE TITLE
Suggestion: Ability to clear an area in the menu

### ISSUE THREAD

**Issue by ADRNALN** [citizenfx/txAdmin#415]
It would be nice to be able to reset an areas state by removing any objects, peds, or vehicles. Specifically when a modder comes on and spawns objects all around the map or cars in a concentrated area.

**Comment by Kawium** [comment]
Yes

**Comment by TasoOneAsia** [comment]
Added with d8f4de64c75ed22c479ad3df4fda124708a4fbf4, for now this won't be able to reset things that are spawned through the server.
