### ISSUE TITLE
In-Game Menu not authenticationg

### ISSUE THREAD

**Issue by PawanOsman** [citizenfx/txAdmin#417]
Hello, Thank you for the Great In-Game menu, i tested it in my local pc its amazing, but we have problem in our server its not authenticate admins in-game

we are using proxy to protect the server against ddos attacks
![image](https://user-images.githubusercontent.com/8727627/127898027-93fe044f-9ab5-4429-8bce-fc10534d6622.png)

but txadmin not authenticating in game menu and says "your identifiers do not match any admin registered in txadmin"

how to fix? i can send my test server ip to test, its the same with proxy and without

**Comment by tabarra** [comment]
Please use the discord guild for support.  
The link is in the README (and literally everywhere as well).
