### ISSUE TITLE
Suggestion: guide on how that graph works because I think nobody really knows

### ISSUE THREAD

**Issue by michieldesair** [citizenfx/txAdmin#420]
As the title says, a guide on that graph'd be pretty nice. low = good, yes. but, can it be a bit more advanced?

**Comment by tabarra** [comment]
Fine, will do one eventually.

**Comment by tabarra** [comment]
I might just change the chart to be more clear, or add a new chart that is way more obvious what is good or bad.

**Comment by tabarra** [comment]
> or add a new chart that is way more obvious what is good or bad  

This was done, do you think I still need a dedicated docs page on it?

**Comment by tabarra** [comment]
I'll close the issue as "not planned", but might reconsider if enough people still feel like the chart is unreadable.
