### ISSUE TITLE
Playerlist can often fail to update properly leading to an unchanging player list

### ISSUE THREAD

**Issue by TasoOneAsia** [citizenfx/txAdmin#422]
### Description 
The menu's `Player Page` often fails to update properly for an admin after an indeterminate amount of time. **This is not due to the NUI window freezing or any other issue within CEF**, instead most likely occurs within the client game scripts (this means that switching tabs or using the `Main` list items continues working).

###  Possible Cause
The player list was sent using latent events in order to ensure that users with slower internet connections do not experience issues relating to the size and subsequent bps of the event. This issue was most likely caused by the the assumption on the client side that these events would be received in order as they were sent (behavior of regular events). Latent events however do not have any guarantees for the order they arrive in.

**Unfortunately I haven't yet been able to personally repro this issue with debug logs enabled, as not many users have showed interest in allowing me debug access on a live server**

**Comment by tabarra** [comment]
Fixed in v4.7.0
