### ISSUE TITLE
Allow Users to Teleport in NoClip

### ISSUE THREAD

**Issue by TasoOneAsia** [citizenfx/txAdmin#423]
A common feature request expressed by users is the ability to teleport while in NoClip (most often used for moderation  as they can teleport to players while still remaining mobile and invisible). 

Currently teleports don't work because NoClip updates the camera every tick in response to user input, meaning when a player teleports, its started but camera is reset, essentially disgarding the teleport.

**Possible Solution**
* Add a patch to the freecam dep that could allow for the camera to be dynamically set to coords (or pause UpdateCamera loop till teleport complete) so we don't return back to previous positon.

**Comment by tabarra** [comment]
@TasoOneAsia any updates on this issue?

**Comment by tabarra** [comment]
@TasoOneAsia  When doing tp to marker while on noclip, the final Z is always 1.0, so litely underground.

**Comment by tabarra** [comment]
I improved but didn't solve totally the issue on 5025a31d4951b68273e27688e1df5c555ac1276a  
  
edit: never mind that broke the normal tp z detection somehow
