### ISSUE TITLE
Testing/Improvement of freecam handling when in a vehicle

### ISSUE THREAD

**Issue by GoatG33k** [citizenfx/txAdmin#426]
Currently when activating the freecam from within a vehicle, it simply makes it invisible and disables collision, and teleports it around with the user.

**Goals:**
- Resolve the issue of the vehicle entity vanishing when moving very quickly in freecam (OneSync)
- Additional testing with other types of vehicles
  - Helicopters
  - Bikes
  - Boats

**Comment by tabarra** [comment]
Freecam does SetEntityCoords on the ped, and then on the vehicle if there is one.  
Maybe that can cause the car to go \*poof*?

**Comment by tabarra** [comment]
This issue has been solved.  
The root cause was due to the vehicle not being teleported alongside the player.
