### ISSUE TITLE
[BUG] Memory leak in server log

### ISSUE THREAD

**Issue by vjota2** [citizenfx/txAdmin#427]
Hey! 

Currently we're facing issue causing txAdmin to crash.
Noone is able to load txAdmin website after this crash and txAdmin becomes completly unresposible.

Don't really know what else would you need from me. If you need anything else, hmu

![image](https://user-images.githubusercontent.com/70014692/130488477-42e11d3e-7a47-477b-9a3e-654309329d59.png)

**Comment by tabarra** [comment]
1. how often this happens?
2. how many average players?
3. which type of server (rp, free roam, deathmatch, etc)?
4. post a screenshot of the diagnostics page. Full page, from the browser tip to the windows clock at the bottom.

**Comment by vjota2** [comment]
Also, you this might come handy :D

![image](https://user-images.githubusercontent.com/70014692/130488750-70d0516a-a814-4ec3-9cdf-ba563ec3be18.png)

**Comment by vjota2** [comment]
> 
> 
>     1. how often this happens?
> 
>     2. how many average players?
> 
>     3. which type of server (rp, free roam, deathmatch, etc)?
> 
>     4. post a screenshot of the diagnostics page. Full page, from the browser tip to the windows clock at the bottom.

1. Once a week
2. Avg idk (200 currently, later at night 220) -> but crash does not seem to be affected by players amount, it can occur even at 6 AM (5 players online)
3. RP, sadly
4. Where can I find that page?

PS: Crash seems to be more related to how long fxserver.exe is running

**Comment by tabarra** [comment]
> Where can I find that page?

The menu on the left.  
Near the settings page, admin manager and etc.

**Comment by vjota2** [comment]
txAdmin is currently unavailable, because of the crash. (screen)
we have to restart server, gonna post diagnostics page soon

*just noticed, other server with not so much load (2-3 players) is not affected by this, only main server*

![txadmin](https://user-images.githubusercontent.com/70014692/130490261-d06319b7-6fe7-47b3-838a-1b80ffcc46da.png)

**Comment by tabarra** [comment]
Ahh then nevermind... Please just send me this screenshot in two days.  
The hypothesis is that the server log is causing a "memory leak" which eventually causes the crash.  
If you just started txAdmin, the numbers will be normal.  
  
I'll make sure to leave this issue open for a few days while I wait for the results, okay?

**Comment by vjota2** [comment]
Sounds good, gonna post it.

Also, do you think this can by caused by console log file size?
Noticed few hours ago, that log file size was +-180 mb? (Those things are just poping out in my head, cuz I've been out for a few weeks and my brain is kinda slow)

**Comment by tabarra** [comment]
Maybe, that's why i need the diagnostics.

**Comment by vjota2** [comment]
Update after 1:30 uptime

Prolly gonna post few of them over time, u never know when it crashes again..

![image](https://user-images.githubusercontent.com/70014692/130507026-46fbef53-3421-41f9-b57c-189e38aadd2e.png)

**Comment by vjota2** [comment]
Update..
Still running, but "txAdmin (inside FXserver)" memory seems pretty high

![image](https://user-images.githubusercontent.com/70014692/130822252-6d25e58e-f52f-417a-8ba7-681f0d1ba797.png)

**Comment by tabarra** [comment]
Yup.  
Issue confirmed.  
Will try to fix that in a good way for the next update, but may fixing it in a "dumb" way due to time constraints.

**Comment by vjota2** [comment]
> Issue confirmed.

Good luck with fixing it! 
If you need anything else simulating issue/test fixes u can hmu ;)

**Comment by vjota2** [comment]
Update! Crashed again

Memory of txAdmin (inside FXserver) was ~2gb hour before the crash

![image](https://user-images.githubusercontent.com/70014692/131555194-0175f8e9-59e1-4c2b-bb06-9537a66bfb9f.png)


![image](https://user-images.githubusercontent.com/70014692/131555081-417f0603-ddf2-4dbd-bfc9-86c836ce07e6.png)

**Comment by tabarra** [comment]
Although my commit capped the log size, after a lot of calculations I don't think this is the only reason.  
For the log alone to match your screenshot, we would need for it to be around 470mb, while on my test I could only get an 94mb increase in Resident Set Size.  
  
Did the last update solve your issue?  
I'm reopening this for now.

**Comment by vjota2** [comment]
> Did the last update solve your issue?

Hey! 
We're not sure yet (we did update yesterday), but he's the current screen
*nothing strange detected since the update

![image](https://user-images.githubusercontent.com/70014692/132388106-5d3093a6-d922-4eea-ad0e-f231bfda46e6.png)

**Comment by tabarra** [comment]
43k log entries, so if this actually solved the issue, tomorrow morning the tx memory usage shouldn't be above 300mb or so.

Mind sending me a new screenshot tomorrow?

**Comment by vjota2** [comment]
> Mind sending me a new screenshot tomorrow?

Absolutely, no problem. Gonna send it tmrw

**Comment by vjota2** [comment]
> screenshot

![image](https://user-images.githubusercontent.com/70014692/132645803-bbd48391-b7ff-4831-b89e-da30dffb5089.png)

**Comment by vjota2** [comment]
Seems working and fixed

**Comment by tabarra** [comment]
Great. **Thanks my dude.**  
If you want, join our discord and ping me so I can give you the a role specific for big servers.  
In the near future, we will have a locked and hidden channel specifically for the top servers of fivem, since they have particular needs.  
https://discord.gg/FKcxphyG
