### ISSUE TITLE
[BUG] Recipe deployer DOES NOT support new key types

### ISSUE THREAD

**Issue by Ruqen** [citizenfx/txAdmin#429]
txAdmin only supports old key types.

New key types like: cfxk_1e4sa1z9NIzdmkky1lq2w_3kpruj // Example key

is not supported and on recipe deployment, the last letter gets deleted (the letter "j" in this example).

**Comment by tabarra** [comment]
Thanks for reporting. I totally forgot that the new key has variable key size.
