### ISSUE TITLE
[BUG] Error txAdminInterface variable, can't start server

### ISSUE THREAD

**Issue by Deniel00** [citizenfx/txAdmin#430]
Hi

If add `+set txAdminInterface IP` show error on startup, and don't accept any settings in server.cfg. In server cfg setup correct settings, and don't accept it.
We're have 3 ip on server, and want restrict ip usage on server.

![kép](https://user-images.githubusercontent.com/12788940/131261474-72229b4b-7f69-40f5-a59d-0294c339fdad.png)
![kép](https://user-images.githubusercontent.com/12788940/131261545-2717c167-45cc-4d11-b1bf-150c76be9d56.png)

**Comment by tabarra** [comment]
Bug in a very annoying part of txadmin, will add to the TODO list, but it nos not top priority, unfortunately;

**Comment by Deniel00** [comment]
Just created a hotfix, i'm tested and working fine
