### ISSUE TITLE
Suggest use players data in other scripts

### ISSUE THREAD

**Issue by AstroNext** [citizenfx/txAdmin#436]
I suggest use player data in other script in server sided like player time play, players that have permission  or ...
I need these data in es_extended and ...
implement with exports or events !

**Comment by LiamDormon** [comment]
An API has already been suggested in #179

**Comment by tabarra** [comment]
Although not exactly the same thing, I'll mark as duplicated #179 like Mojito said.  
The permission exporting thing is absolutely in the roadmap, but i'm not sure how to do it yet.

**Comment by AstroNext** [comment]
i mean get player time play !
