### ISSUE TITLE
[Feature]: playersdb identifier history

### ISSUE THREAD

**Issue by whitigol** [citizenfx/txAdmin#445]
### Scope

Web

### Feature Description

Log the steam, discord, and license identifiers.

### Use Case

For example, when a player is not in server, but is requesting access to a script that uses ace perms, to be able to access their identifiers to add them to said whitelisted script.

**Comment by tabarra** [comment]
Will be partially covered in the next update by the server log logging the player join.

**Comment by whitigol** [comment]
Sounds great. Can't wait to see what the next update brings. You've done an excellent job on what has been brought so far, and I can't wait to see what the future brings for txAdmin.

**Comment by tabarra** [comment]
I'll reopen it as it is still a TODO for the players database.  
Will probably one be done after the new playerlist backend system be implemented.

**Comment by tabarra** [comment]
This will be done, for now I'm closing this as duplicate of #385, thanks for the suggestion.
