### ISSUE TITLE
[Feature]: Token Bans

### ISSUE THREAD

**Issue by Rm1998** [citizenfx/txAdmin#446]
### Scope

Web

### Feature Description

It would be cool to have the ability to "Token ban" people, this would be most helpful against pesky modders who target servers and use methods to unban themselves.

**Comment by Gravxd** [comment]
I might be dumb, but what do you mean by 'token ban'.

**Comment by Gravxd** [comment]
Are you on about the native GetPlayerToken()?

**Comment by AvarianKnight** [comment]
Player Tokens are a server-specific (owner specific, actually) HWID identifier, meaning if they change their discord/steam/license, etc, they will still get banned as long as one of the HWID match see: [GET_PLAYER_TOKEN](https://docs.fivem.net/natives/?_0x54C06897)

**Comment by Rm1998** [comment]
Not the best at explaining stuff, but here goes. Each server gives someone a unique token upon the first time joining. If you ban this token, the only way one could unban themselves from your server is by completely reinstalling windows. (They might require more steps but this is my very basic understanding of it)

**Comment by Rm1998** [comment]
Oh, AvarianKnight explained it much better than I ever could. Thanks!

**Comment by Gravxd** [comment]
Sounds like a really cool idea, would be great to have some form of this implemented. Thanks for the info both of you

**Comment by M4rlus** [comment]
> the only way one could unban themselves from your server is by completely reinstalling windows. (They might require more steps but this is my very basic understanding of it)

you just have to use a spoofer, this token bans are very easy to bypass

**Comment by AvarianKnight** [comment]
> > the only way one could unban themselves from your server is by completely reinstalling windows. (They might require more steps but this is my very basic understanding of it)
> 
> you just have to use a spoofer, these token bans are very easy to bypass

Not sure what spoofer you have that bypasses this, but either way it adds more security, also weird that there are so many people asking to be unbanned for something that's 'very easy to bypass'

**Comment by tabarra** [comment]
Planned.

**Comment by Hqrreh** [comment]
Did anything get done with this, would be really intrigued to see this in motion

**Comment by tabarra** [comment]
@Hqrreh LOL check back next year and maybe i'll have something planned a little better  
Our current database solution just isn't good enough to store 20 HWIDS for every banned player, and will take MONTHS before replacing the database becomes a priority.

**Comment by AvarianKnight** [comment]
Is txAdmin still limited to what database it can use internally?

**Comment by tabarra** [comment]
We can totally solve this issue, but we have many other things that have way higher priority.

**Comment by Hqrreh** [comment]
> @Hqrreh LOL check back next year and maybe i'll have something planned a little better Our current database solution just isn't good enough to store 20 HWIDS for every banned player, and will take MONTHS before replacing the database becomes a priority.

Ahahha fair enough mate

**Comment by dennisjongebloed** [comment]
Any updates?

**Comment by tabarra** [comment]
@dennisjongebloed Yes.  
This week I validated the average token count per player and it's likely doable to implement it in the current database without needing to refactor everything.  
**But still no ETA.**
