### ISSUE TITLE
[BUG] Mobile/Responsive Issues

### ISSUE THREAD

**Issue by TasoOneAsia** [citizenfx/txAdmin#447]
**Describe the bug**
A collection of mobile/responsive related issues.

**Issues**

![ban](https://i.tasoagc.dev/Kday)

![perf](https://i.tasoagc.dev/iXwU)

This should scale better for font/axis.

![cfg editor](https://i.tasoagc.dev/LaAX)

Font here should be scaled down on mobile.

![admin manager](https://i.tasoagc.dev/KQtF)

![player manager](https://i.tasoagc.dev/VF8L)

**Comment by tabarra** [comment]
Urgent bug:
You cannot stop/restart the server on mobile as the confirm button is out of screen.
![image](https://user-images.githubusercontent.com/1808295/155853695-2118bb4c-bc2a-42a5-9acf-811872618cdc.png)


EDIT: Never mind, i just solved this one

**Comment by tabarra** [comment]
All pages are slowly migrating to the new UI which does not have responsiveness issues.
