### ISSUE TITLE
[Feature]: Add revoke ban/whitelist to player modal

### ISSUE THREAD

**Issue by fasterplayer** [citizenfx/txAdmin#449]
### Scope

Web

### Feature Description

Show the BAN ID in more places (Like in the user History) to make unban easier as it's not possible to unban a person without knowing his ban ID. 

### Use Case

Trying to unban a player that is currently banned.

### Proposed Solution

Showing the BANID would help alot and having a revoke button directly in the history would be awesome.

### Additional Info

![image](https://user-images.githubusercontent.com/48169441/134786475-2b7c3fd9-f257-4f5b-9474-2837490dad13.png)

**Comment by tabarra** [comment]
Planned.

**Comment by tabarra** [comment]
Completed in release v5.0.0.
