### ISSUE TITLE
[Feature]: Discord Whitelist

### ISSUE THREAD

**Issue by fasterplayer** [citizenfx/txAdmin#450]
### Scope

Web

### Feature Description

Have the option to use the already ewxisting discord bot feature to check if the user that is trying to connect to the server is on the (specified from id) discord server and has one of the (specified with id's) roles. Alot of servers uses discord Whitelist system with a discord bot script to check this.

### Use Case

Using whitelist system and maybe combine have the option to combine both Whitelist system. Checks if the user is Whitelisted in TxAdmin or Has the role on the server.

### Proposed Solution

Another cool option would be to add a command in the existing bot to whitelist a discord member from a command executed from a GuildMember that has the Whitelist permission on TxAdmin.

And if we want the best of all, integrate a Context Menu option with the latest Discord api options. Right click on the user, Whitelist.

### Additional Info

I'm a js/ts dev so i could collaborate if needed.

**Comment by tabarra** [comment]
Discord whitelist by role ID or guild membership is planned.

**Comment by fasterplayer** [comment]
> Discord whitelist by role ID or guild membership is planned.

Nice!!

**Comment by gergewgr** [comment]
Greetings the discord integrity can't be saved in the settings could someone help me in advance thank you

**Comment by tabarra** [comment]
Feature confirmed for txAdmin v5.1 (sorry for the delay).
