### ISSUE TITLE
[Feature]: shortcut to open a player modal via `/tx <id>`

### ISSUE THREAD

**Issue by tabarra** [citizenfx/txAdmin#451]
### Scope

In-Game Menu

### Feature Description

Although the menu players page is versatile, admins want an easier way to open the player modal by the player ID.  
I propose we expand the `/tx` (and `/txadmin`) command to accept a player ID.  
**Make sure to also update the chat suggestion so people find out this exists.**

### Use Case

You quickly want to ban player ID 123, so you type in chat `/tx 123` and then ban him.

### Proposed Solution

.

### Additional Info

.

**Comment by TasoOneAsia** [comment]
Implemented in fb189dc53c2a93837e1190f72a178c7876b8724e. 

[Preview](https://streamable.com/dq64zg)

**Comment by tabarra** [comment]
![image](https://user-images.githubusercontent.com/1808295/134792430-211c8581-a161-49fa-b8c9-c929ddf43245.png)

**Comment by fasterplayer** [comment]
Tysm for this. You are so fast! Will be in the october release i imagine?
