### ISSUE TITLE
[Feature]: Restart Button on CFG Editor Page

### ISSUE THREAD

**Issue by n0tsiege** [citizenfx/txAdmin#459]
### Scope

Web

### Feature Description

A small "restart" button next to "Save File" As well as it would be nice to auto-save config when restarting if this were implemented.

### Use Case

Many developers modify the server.cfg and then restart the server. I do this myself and I think this would be a nice quality of life improvement. 

### Additional Info

Though it is possible through the dashboard and console pages, this would make for one less click.

**Comment by CsokiHUN** [comment]
i think this feature is implemented. i checked in latest release
@tabarra you can close the PR

**Comment by tabarra** [comment]
True, thanks @CsokiHUN
