### ISSUE TITLE
Discord restart messages in game doesn't work

### ISSUE THREAD

**Issue by M1K3-NL** [citizenfx/txAdmin#46]
I have the discord bot on and scheduled restarts on. When a restart has been scheduled, this was neatly placed in the in-game chat in the previous version. Now only "txAdmin" appears and if I do an Admin Broadcast, my username will be there.

![bbyqftrs](https://user-images.githubusercontent.com/39988281/66705116-198fbf00-ed23-11e9-80b6-379392f2118b.png)
![unknown](https://user-images.githubusercontent.com/39988281/66705117-198fbf00-ed23-11e9-881e-36d9a1d3c670.png)

**Comment by tabarra** [comment]
Sorry, i'm not sure if I understood it correctly, what does this have to do with the discord bot?  
Are you using the default chat?
i'm not seeing whats wrong, can you please elaborate or join our discord?

**Comment by M1K3-NL** [comment]
Hey Tabarra,

Thanks for the quick response!


I do indeed use the standard chat, but I made an adjustment that you have to type with a command. So /ooc /tweet /say /job and so on.
The previous txAdmin version had no problems placing the restart reminder in-game when the server started restarting (the 30, 15, 10, 5, 4, 3, 2, and 1 minute notifications).
Now that the update has been done from txAdmin, this is reflected in the console as

txaBroadcast "txAdmin" "Wensveen Roleplay is scheduled to restart in 15 minutes."
[txAdminClient] Admin Broadcast: txAdmin

In-game you will only see "txAdmin". This used to be "Wensveen Roleplay is scheduled to restart in 15 minutes."

If I want to do an admin broadcast via the dashboard with, for example: We're going to restart the game.

Then there will be in-game: AdminMike (my username).
No further message is displayed.

The only thing I have changed is the old version of txAdmin and the new version put back. So there has been an adjustment in txAdmin so that it no longer works for custom chat scripts.

**Comment by tabarra** [comment]
Ohh okay I see whats happening.  
I added a new parameter for the name of the admin doing the broadcast, and totally forgot to change the compat version limiter for the resource.  
Just delete the txAdminClient resource and restart the server inside txAdmin and it will work fine (it will be reinjected).

**Comment by M1K3-NL** [comment]
Hello,

I did exactly what you asked, but still getting the same response.
Do you maybe have the old txAdminClient from the past version?

**Comment by tabarra** [comment]
Did you managed to fix it?  
I'm closing this issue, if you still need support please check our discord server (link in the README).
