### ISSUE TITLE
[Feature]: Removed revoked Warns

### ISSUE THREAD

**Issue by fbigrs** [citizenfx/txAdmin#461]
### Scope

Web

### Feature Description

In the Latest txAdmin Update, you implemented the Feature to cleanup the Database.

I really like it, but i think it could be helpfull, to also remove "revoked" Warns.
In my Case, i dont want to clear old warns, because it shows the History of a user. But we also use Warns, to call people in the Support, and for better visibilitly, we revoke them afterwards and only let the real warns active. So to remove revoked Warns, like you can remove revoked Bans, would be helpfull

### Use Case

To Cleanup revoked Warns in the History because they are not needed anymore.

### Proposed Solution

Add a "remove revoked" into the Clean Database Section at the "Warns" Dropdown.

**Comment by tabarra** [comment]
Easy enough.  
Consider it done.

**Comment by tabarra** [comment]
Available in v4.7.0.
