### ISSUE TITLE
[BUG] Freeze command does not work for players in vehicles

### ISSUE THREAD

**Issue by tabarra** [citizenfx/txAdmin#463]
**Expected behavior**
Should stop the car/vehicle, and on unfreeze, should unfreeze vehicle/player.  
The issue is that a player can exit the vehicle while frozen, so we would need to freeze the player, and freeze te vehicle, but then if he leaves and we unfreeze him, we would also need to unfreeze the vehicle but he's not inside of it anymore... so probably need to keep watching with a thread to make sure we are only freezing a vehicle if he is the driver... idk.

**Comment by TasoOneAsia** [comment]
Fixed in #466
