### ISSUE TITLE
[BUG] yarn_cli.js not getting moved in a recipe

### ISSUE THREAD

**Issue by ghost** [citizenfx/txAdmin#465]
**txAdmin/FXServer versions:**
v4.6.1/4747
  
**Describe the bug**
When using a recipe(tested with external) the **yarn_cli.js** file gets stuck in a folder (\citizenfx-cfx-server-data-b907aa7\resources\[system]\[builders]\yarn) in my case

**To Reproduce**
1. Run the txAdmin recipe deployer
2. Try and start the server. The yarn resource will throw an error ([script:yarn] SCRIPT ERROR in promise (unhandled): Error: Cannot find module './yarn_cli.js')

**Recipe i used**
https://raw.githubusercontent.com/LittleDraily/basic-esx-recip-txadmin/main/recipe.yaml

**Expected behavior**
That the files gets moved into the correct resource path

**Additional context**
Windows 11

**Comment by ghost** [comment]
I just tested it on a windows 10 vps. On there it worked! Maybe a windows 11 problem or a thing that happens sometimes.

**Comment by carlos55ml** [comment]
I can confirm it migh has something to do with windows 11. Me, as a windows 11 user, im experiencing this issue in my local machine.

**Comment by TasoOneAsia** [comment]
This isn't a bug with txAdmin but rather something going wrong with the embedded `yarn` found in the default `cfx-server-data` files.
