### ISSUE TITLE
[BUG] Server logs are not readable with light theme

### ISSUE THREAD

**Issue by manzarek123** [citizenfx/txAdmin#471]
**txAdmin/FXServer versions:**
4.6.1
  
**Describe the bug**
Server logs are not readable with light theme but is ok on dark theme

**To Reproduce**
1. Go to Server Log
2. See error

**Expected behavior**
Server logs readable in light theme

**Screenshots**
https://i.gyazo.com/e51e3f756d33f1fdbc1000c2a414ec23.png

**Comment by tabarra** [comment]
Fixed on c3e16024e606910b982b6680a931aa54b7cb9ed2  
Thanks for reporting.
