### ISSUE TITLE
[Feature]: Add minutes to ban time

### ISSUE THREAD

**Issue by PC1up** [citizenfx/txAdmin#474]
### Scope

Web

### Feature Description

I think the title is pretty self-explaining, just add an option to ban a player for a given amount of minutes e.g. 30 minutes or sth like that

### Use Case

If you want to ban an user for the rest of the day and its e.g. 06:34 pm you have to ban him either until 11:34 pm or 00:34 am

**Comment by tabarra** [comment]
Although this is not a bad idea, it is just not worth for us to change this specific thing right now.  
Specially because we have the warn feature, so less than one hour ban is mostly in the warn category.  
If more people ask for it I might reconsider.
