### ISSUE TITLE
[Feature]: Taking screenshot of the players screen

### ISSUE THREAD

**Issue by maxcamorra** [citizenfx/txAdmin#475]
### Scope

In-Game Menu

### Feature Description

It would be nice to have a screenshot button for taking screenshot and send it over a discord webhook into the server discord with for example using screenshot-basic

**Comment by tabarra** [comment]
Sorry, but one I can't do.  
1. txAdmin needs to work for servers up to 1 thousand players, handling this many screenshots would be a nightmare;  
2. Where would we upload those screenshots without violating ToS and getting blocked?
3. This is barely useful, and kinda bad for user privacy;
4. I really don't want to deal with making an UI for that;
5. It wouldn't capture most of the cheats, and people would complain about it.
