### ISSUE TITLE
[BUG] Have to enable debug and reauth to open menu

### ISSUE THREAD

**Issue by PC1up** [citizenfx/txAdmin#477]
**txAdmin/FXServer versions:**
4793
  
**Describe the bug**
I want to open the menu via /tx or a hotkey and I just hear the click sound. To fix this I always have to enable the debug mode, type in this "txAdmin-reauth" command and then disable debug mode again to make the menu open.

**To Reproduce**
1. Try to open the menu and just hear the click sound
2. Open the F8 console
3. Type in "txAdmin-debug 1"
4. Type in "txAdmin-reauth"
5. Type in "txAdmin-debug 0"
6. Close the console
7. The menu will work now until I restart my game

**Expected behavior**
Open the menu without having to enable debug mode

**Screenshots**
---

**Additional context**
Video: https://vimeo.com/637387244

**Comment by tabarra** [comment]
Got it, thanks for the high-quality report.  
We aim to fix the auth issue next update, and we hope the "sound but no workey" issue goes away with it.

**Comment by tabarra** [comment]
Likely fixed on 9bbd09c58f5657b864dccb382e3547f5a66a6ea3.  
If the error persists after v4.8 release, please let us know!
