### ISSUE TITLE
Rename txAdmin script running inside FXserver

### ISSUE THREAD

**Issue by mist8kengas** [citizenfx/txAdmin#48]
I would like to suggest to rename the txAdmin script running inside the FXserver folder.

I did some testing and when you setup the FXserver and run it via txAdmin webpage normally, it adds a new folder to your set resources folder called "[txAdmin-cache]" which has a script/folder named "txAdmin".
The aforementioned "txAdmin" script needs to be renamed to "txAdminClient" for the txAdmin script to work properly, it should automatically install the script to have the name of "txAdminClient", I do not know the clear case of the issue but if I leave the script to the original state, it would not work properly. So I had to rename the script to "txAdminClient", in order to have a properly working txAdmin script.

I hope this issue gets fixed in the next update.

**Comment by tabarra** [comment]
Hmm that's a new one.  
Actually, the name of the script that goes inside `[txAdmin-cache]` is actually `txAdminClient`, unless you renamed the folder `txAdmin/extensions/txAdminClient` to `txAdmin/extensions/txAdmin`.  
  
Execute a `git pull` to make sure your files match the ones here on github, and let me know if this solves the issue.

**Comment by tabarra** [comment]
Also make sure your txAdmin folder is not *inside* your resources folder.
