### ISSUE TITLE
[Feature]: Simple git actions in txAdmin web interface

### ISSUE THREAD

**Issue by AleksanderEvensen** [citizenfx/txAdmin#480]
### Scope

Web

### Feature Description

A way of executing simple git actions like pulling, branch switching, maybe also view commit history, if the server-data folder is a git repository.
Maybe adding a new page like this:
![image](https://user-images.githubusercontent.com/19311856/139146824-ea32034b-20c6-437a-a18d-712bbd939742.png)
![Frame 1](https://user-images.githubusercontent.com/19311856/139149449-a0eafa15-f8b5-4bdc-8c69-78fb5e2d15cb.png)

### Use Case

This is more a quality of life thing. By having git actions integrated into txAdmin, you can fetch the newest changes from your remote repository without logging into your server either via a remote desktop client or a remote shell.

### Proposed Solution

Well, I have already pitched one of my ideas in the Feature description, but an easier way would be to just add a small button to the dashboard page.

**Comment by tabarra** [comment]
That looks sick.  
What if we scan the entire server data folder for git repositories, then add them to that git page.  
And once in a while we fetch upstream to look for "updates" and let the admin know some X resource can be updated?  
This would work well for the recipes if they start doing git clones (depth=1) instead of just zip file downloads from github.  
  
And that HTML+CSS, you willing to send me that or even work more on that idea?

**Comment by AleksanderEvensen** [comment]
Well. I just made the design in Figma. I could probably try to make something if you want me to do so. I'm glad you liked the idea

**Comment by TasoOneAsia** [comment]
Wow a feature request with actual design concept renders! @tabarra, if we decide to go with this feature, I can help implement frontend.

**Comment by AleksanderEvensen** [comment]
Clap Clap Clap... you guys can do your shit

**Comment by tabarra** [comment]
> Clap Clap Clap... you guys can do your shit

Ohh, you probably read what Taso said as sarcasm, but he (and I) actually really liked the idea, and absolutely appreciate the effort (and help to make the html, if you up for that).  
Feel free to join our discord and ping me if you want to talk more about it.

**Comment by AleksanderEvensen** [comment]
Well... already in the discord. Taso Knows my name PS: AleksHSE

**Comment by M4rlus** [comment]
I like this idea, but I’ll appreciate it if you implement this in the advanced tab from txadmin. Too much kids don’t understand GitHub, that’s why I use it for riven project management xD

**Comment by AleksanderEvensen** [comment]
If the kids dont understand Git then Git gud

**Comment by tabarra** [comment]
Although this predates #933 by a lot, since that one is more updated I'm closing this one as duplicated.  
Continued conversations regarding this feature should be done in #933.
