### ISSUE TITLE
[Feature]: CallAdmin/Report

### ISSUE THREAD

**Issue by austinconway** [citizenfx/txAdmin#484]
### Scope

In-Game Menu

### Feature Description

Possibly add a /calladmin or /report that goes straight to the txAdmin menu.

### Use Case

This would be useful because then /calladmin & /report will go straight to txAdmin. My communities staff team is thinking about switching to txAdmin instead of EasyAdmin, and this feature would really complete the in-game menu.

### Proposed Solution

We could just use a script that does this, but it would be much easier if it was integrated into the menu.

**Comment by TasoOneAsia** [comment]
Duplicate of #388
