### ISSUE TITLE
[BUG] Live Console Performance with Large Logs

### ISSUE THREAD

**Issue by TasoOneAsia** [citizenfx/txAdmin#486]
**txAdmin/FXServer versions:**
4.8-dev
  
**Describe the bug**

**To Reproduce**
1. Go to 'Live Console' with large backlog
2. First paint will be slow

**Expected behavior**
First paint should be fast

**Additional context**
Although this issue is more apparent on lower-end devices, it still applies to all environments. 
We should lazily render text nodes as required instead of appending all on load.

**Comment by tabarra** [comment]
Solved in txAdmin v7 by using xterm.js
