### ISSUE TITLE
[BUG] OS Detection

### ISSUE THREAD

**Issue by cdouth99** [citizenfx/txAdmin#487]
**txAdmin/FXServer versions:**
Versions: v4.7.0 / 4933
  
**Describe the bug**
OS not detecting.

**To Reproduce**
1. Go to /diagnostics
2. View Environment/OS

**Expected behavior**
It should say Windows 11.

**Screenshots**
https://cdouth99.fileglass.com/jjEfsZeIJs.png
https://cdouth99.fileglass.com/wcS5YHM2gp.png

**Additional info**
This server was deployed well after the Windows 11 install.

**Comment by cdouth99** [comment]
Let me know if this is a client issue.

**Comment by aidenzybell** [comment]
I believe this would have been fixed in https://github.com/tabarra/txAdmin/commit/70fc4757596a57ab86dc0476a329546b5ed40b66.

**Comment by cdouth99** [comment]
Marvelous! Closing now.

**Comment by tabarra** [comment]
I haven't tested, but will probably work.

**Comment by cdouth99** [comment]
What artifact has this been updated into, if any? I’ll test it when available. 

Edit: Assuming this will be posted to the next txAdmin version.

**Comment by cdouth99** [comment]
Issue will be closed once testing is finished on next version release.

**Comment by cdouth99** [comment]
This has been resolved.
