### ISSUE TITLE
[Feature]: Punishment ID in Ingame Menu

### ISSUE THREAD

**Issue by PC1up** [citizenfx/txAdmin#496]
### Scope

In-Game Menu

### Feature Description

Just show the punishment id in the history menu of a player. I professionally photoshopped a picture to underpin my idea: https://prnt.sc/1z1gu7v

**Comment by tabarra** [comment]
The idea since forever was to use the same div as we have in the players page for the modal... including the revoke button.  
I'll have to check if everything fits tho.

**Comment by TasoOneAsia** [comment]
Implemented with v5.0.0
