### ISSUE TITLE
[Feature]: Select ban end date & time

### ISSUE THREAD

**Issue by PC1up** [citizenfx/txAdmin#498]
### Scope

Web

### Feature Description

It's kinda annoying to always calculate the time you have to ban an user so I would appreciate if you could select the ban end date and time instead of selecting a time.

### Use Case

For example I want to ban a user until 00:00 and it's like 8:42pm I always have to dig out my calculator to find out how long I have to ban this user

### Proposed Solution

In the popup to ban an user there is this field "custom". Below this field just create another field called "Date" or smth like that where you can choose a date and time when this user should  be unbanned

**Comment by tabarra** [comment]
Sorry, but I don't want to deal with dates.  
I promise you it's more annoying to deal in code than in real life. For instance, how about servers not hosted in the same timezone as the server?  
  
Also would need to take care of using two different date picker libraries, one for web, one for react.
