### ISSUE TITLE
[BUG] TxAdmin / FiveM connection problems

### ISSUE THREAD

**Issue by Jannis010** [citizenfx/txAdmin#501]
TxAdmin Version : v4.4.2 atop FXServer 4394

So i have the issue that i cant connect with the server on fivem. I start the FXServer, setted up TxAdmin the right way with the server.cfg and used right scripts but as i connect to the FiveM there i no connection or a timeout info on the screen. 
I'm trying it only with the ServerIP that i have but that doesnt work.

Does anyone know if im Missing somethig that i can join my server or did i do somewher a mistake?

Please Help :)

**Comment by tabarra** [comment]
1. Not related to txAdmin
2. Please update
3. You may want to check out our discord: https://discord.gg/txadmin
