### ISSUE TITLE
[BUG] cannot give permissions I don't have.. but I have all permissions

### ISSUE THREAD

**Issue by PC1up** [citizenfx/txAdmin#503]
**txAdmin/FXServer versions:**
4947
  
**Describe the bug**
I wanted to give one of my mods permission to warn users. I myself have "all permissions". As I clicked on "Save" the following message appeared: "You cannot give permissions you do not have"

**To Reproduce**
1. Go to the admin manager
2. Create a new admin or edit an existing one
3. Tick the permission of your choice
4. Click 'Save'
5. Watch the miracle with great interest

**Expected behavior**
I expect txAdmin to let me give permissions to my mods

**Screenshots**
https://prnt.sc/2033b6z
https://prnt.sc/2033cax (I am PC1up)

**Additional context**
None

**Comment by tabarra** [comment]
Issue was solved already, will be available in the next update.  
Thanks for reporting tho!
