### ISSUE TITLE
[BUG] with the Txadmin menu

### ISSUE THREAD

**Issue by CubevomStudio** [citizenfx/txAdmin#505]
**txAdmin/FXServer versions:**
Versions: v4.8.0 / 4960
  
**Describe the bug**
A user doesn´t have a tx admin account, but he can use the tx admin menu in the game, with a hotkey from another server.

**To Reproduce**
1. Go to 'in the settings, you bind a hotkey for tx admin'
2. connect of another server and klick the hotkey
3. you became the menu in your screen

**Expected behavior**

**Screenshots**
https://imgur.com/a/qbGUDaS

**Comment by tabarra** [comment]
Kown and solved, the fix will be available in the next update.  
Thanks for reporting!
