### ISSUE TITLE
API / POST request 

### ISSUE THREAD

**Issue by lukaskabc** [citizenfx/txAdmin#51]
Hi,
is there some api for post request?
Or it would be good idea to make.

What about if I have a website with some php code and I want to start some function on fivem server?
Is would be great if I can make POST request from php (with curl for example) to txAdmin panel.
In request will be some secret code for authenticate and autorize the request and then run some command in fivem console.

:thinking:

**Comment by lukaskabc** [comment]
for example i will send post request to my.site.com:50120/api/post.php with fields
secret: "somereallySecretStringToVerifyRequest"
cmd: "/somecommand"
hash: "has of string secret+cmd for verify"

response is not needed just return true on success command execution and false on error (for example if server is off...)

**Comment by tabarra** [comment]
that would be pretty easy to configure if the extensions system was ready since it already implements secrets for the intercom get/posts
