### ISSUE TITLE
[Feature]: Maintenance mode for players

### ISSUE THREAD

**Issue by djmetla** [citizenfx/txAdmin#516]
### Scope

Web

### Feature Description

I ask for this because we want some tool how to temporary disable access to server for players, but some peoples (maybe flag for admin) can join. All this for updates, scripts, maintenance on server and other reasons.

**Comment by matsn0w** [comment]
+1

**Comment by tomasalves8** [comment]
+1

**Comment by Artinoo1** [comment]
Hey you can enable the Whitelist? 
@djmetla

**Comment by tomasalves8** [comment]
@Artinoo1 In whitelisted servers it won't work.

**Comment by Artinoo1** [comment]
@tomasalves8 okay that's true.

**Comment by tabarra** [comment]
Feature confirmed for txAdmin v5.1 (sorry for the delay).
