### ISSUE TITLE
[Feature]: Resource start, stop, restart queue

### ISSUE THREAD

**Issue by BerkieBb** [citizenfx/txAdmin#518]
### Scope

Web

### Feature Description

I want to know if it is possible to make a selection of resources in the resources list start in a queue. If it could be done it could be a great time saver

### Use Case

I have had a lot of times where I need to restart, stop or start a few resources at the same time and doing this by writing commands or via the resources tab is not all that fast.

### Proposed Solution

You have a selection box right next to a resource and if you select more than one you can choose to start, stop or restart the selected resources.

**Comment by tabarra** [comment]
I think your issue is very very particular.  
If it's always the same resources, I recommend saving a `restart_things.cfg` alongside your `server.cfg` containing the exact operations you execute (stop/ensure/etc) and when you need you can just run `exec restart_things.cfg` in the live console.

**Comment by tabarra** [comment]
For now i'm closing this feat request, but am willing to reconsider if new information comes up.
