### ISSUE TITLE
HealthCheck failed: Request failed with status code 400

### ISSUE THREAD

**Issue by mist8kengas** [citizenfx/txAdmin#52]
Hi, I am in need of help with txAdmin, when it tries to refresh the Status Info pane in the Dashboard, it spams out a code 'HealthCheck failed: Request failed with status code 400' in the console and after some time it has a partial crash, I have tried reinstalling txAdmin and tried updating it to the latest version. Still no luck.

**Comment by tabarra** [comment]
For support, please use our discord server.  
You are probably putting txAdmin on the fxserver port, or something else in the port you specified in the `endpoint_add_tcp` command in your `server.cfg`.
