### ISSUE TITLE
[Feature]: Enable offline warning

### ISSUE THREAD

**Issue by PC1up** [citizenfx/txAdmin#522]
### Scope

Web

### Feature Description

Atm, youre not able to warn offline players. Maybe, idk if its even possible, enable this and inform the player that he got warned, when he gets online the next time?

### Use Case

For example if someone is  fleeing from RP you, obviously, can't warn them because they,  well, aren't online anymore.

**Comment by tabarra** [comment]
The main issue here is how do we make them acknowledge the warn.  
Like, if you show it when they come back to the server the interface overlay might be obfuscated by another overlay (eg. spawn point selection) or something like that.  
This is very prone to issues.

**Comment by PC1up** [comment]
Ah, I get what you mean. Uhm, idk then maybe just w/out the message when joining. Just the simple warning so other staff members know and, if they want, inform the player by themselves.

**Comment by userzfr** [comment]
Nice

**Comment by tabarra** [comment]
Update: I'm finally considering it. Not for v7.1 but maybe soon.

**Comment by tabarra** [comment]
Done.  
This will be available in the upcoming weeks when v7.3 is released.
