### ISSUE TITLE
[BUG] Performace & Player chart in Dashboard is broken

### ISSUE THREAD

**Issue by thecrafterjt** [citizenfx/txAdmin#523]
**txAdmin/FXServer versions:**
 txAdmin v4.9.0 atop FXServer 5053 on Ubuntu 20.04
  
**Describe the bug**
No new data gets added to the right of the chart. It hangs at the point then i updated my FXServer from 4995 to 5053.
I deleted the heatmap json file and new one got created, but it wont fill up with data. Its contenents are only "[]".
I tried restarting the whole fxserver with txAdmin, nothing changed.

**To Reproduce**
1. Setup txAdmin with FXServer 4995 on Ubuntu 20.04
2. Upgrade FXServer to 5053, and keep the txAdmin folder.
3. Delete the heatmap file from txAdmin directory.
4. The chart in Dashboards says "Players & Performance chart will be available in an hour." for **days**!

**Expected behavior**
New data (server tick time, player count) should get added to right of chart.

**Screenshots**
![grafik](https://user-images.githubusercontent.com/20760395/145772109-20be99a2-ea2c-48e2-b078-8c546f007d19.png)

**Additional context**
This worked fine until the update of txAdmin to 4.9

**Comment by tabarra** [comment]
This bug is not related to txAdmin v4.9, but instead fxserver 5011+;  
Either ways, it has been solved already and one update will be available in a few hours.
