### ISSUE TITLE
[BUG] Web panel with cfx.re URL doesnt work anymore. 

### ISSUE THREAD

**Issue by kaugehunt** [citizenfx/txAdmin#526]
**txAdmin/FXServer versions:**
4.10.0 5079
  
**Describe the bug**
cfx.re URL doesn't work anymore after 5020 artifact. Cannot get to admin panel from browser using link. 
Can open the page using IP in browser. But we have our server under VPN tunnel and accesible with whitelisted IPs only. Worked before with same system on artifact 5020. Many other developers having same problem in txAdmin discord and get error "This site can’t be reached" 

**To Reproduce**
1. copy txadmin webpanel link from console 
2. Open link
3. Get error "This site can’t be reached" from browser.

**Expected behavior**
Opening of txAdmin

**Screenshots**
![image](https://user-images.githubusercontent.com/53463213/145905610-7ad56f1f-2c59-4da3-9325-63f7113e2ce9.png)

**Additional context**
Server hosted on Windows OS, problem started when moving from artifact 5020

**Comment by aidenzybell** [comment]
Unable to reproduce.

**txAdmin/FXServer versions:**
 v4.10.0 atop FXServer 5079

The link for my txAdmin panel works perfectly [fine](https://monitor-7fdd3mfpfyrgoesv7jvaynw2w7gxab7m.users.cfx.re/auth). (Might not for you, as I don't have it port-forwarded)

**Comment by kaugehunt** [comment]
Its weird, I can open web panel using server IP and port, but not with generated URL, any ideas why?

**Comment by kaugehunt** [comment]
Can't open your link either. Even if I try to use the link on the server machine itself, it woun't open 
![image](https://user-images.githubusercontent.com/53463213/145907097-ac08f257-31f7-4f6d-a439-ea1656910c19.png)

**Comment by aidenzybell** [comment]
Yeah, as I said I don't have it port forwarded and txAdmin is now closed so you won't be able to, however opens fine for me.

**Comment by ghost** [comment]
I was unable to reproduce. The panel link worked perfectly fine for my FXServer (Windows Server 2016 - 5070).

**Comment by ItsANoBrainer** [comment]
Unable to reproduce on v4.10.0 atop FXServer 5090.

**Comment by tabarra** [comment]
Couldn't reproduce.  
This URL can change if the reference to the `server-monitor-token.key` changes, this can happen if you change or update artifacts.
