### ISSUE TITLE
[BUG] Uncaught ReferenceError: $ is not defined

### ISSUE THREAD

**Issue by rubencosta13** [citizenfx/txAdmin#529]
**txAdmin/FXServer versions:** 5104

  
**Describe the bug**
Uncaught ReferenceError: $ is not defined

**To Reproduce**
1. Start the server 
2. Login to server GUI using localhost:40120
3. Opening Console

**Expected behavior**
The web should work, but without jQuery It doesn't

**Additional context**
Server hosted on Win11 64bit.

**Fixed the issue on my own fork: https://github.com/rubencosta13/txAdmin-master**

**Comment by tabarra** [comment]
`Showing 322 changed files with 97,456 additions and 0 deletions.`  
Your repository is not even a fork, so hard to compare what you did

**Comment by rubencosta13** [comment]
@tabarra.
Sorry, so the file that I edited was located on: https://github.com/rubencosta13/txAdmin-master/blob/master/web/basic/setup.html

To be precise, line: 17

**Comment by tabarra** [comment]
There were more files.
