### ISSUE TITLE
[BUG] txAdmin tries to execute custom ban message as command

### ISSUE THREAD

**Issue by PC1up** [citizenfx/txAdmin#533]
**txAdmin/FXServer versions:**
FXServer: 4985, txAdmin: v4.9.0
  
**Describe the bug**
If you set up a custom locale.json and edit the ban message txAdmin tries to execute messages in a new line as command.

**To Reproduce**
1. Set up a custom locale.json
2. Edit the ban messages so that there is a \n and something afterwards in it
3. Restart txAdmin
4. Ban someone
5. Take a look at the console
6. See, that txAdmin tried to execute everything after the \n

**Expected behavior**
That txAdmin does not try to execute things after the \n

**Screenshots**
Console:
![image](https://user-images.githubusercontent.com/63553505/146678584-bdd88a0a-6b7a-4227-8cea-5d9c907127ee.png)

locale.json:
![image](https://user-images.githubusercontent.com/63553505/146678615-4f683683-ddb9-48a7-b422-d206f6059f13.png)

It's in German but I think it shows the bug pretty good

**Additional context**
None

**Comment by tabarra** [comment]
Thanks for reporting this issue.  
Will be available in tomorrow's update.
