### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by zThundy** [citizenfx/txAdmin#54]
Is there a way to disable partial crash restarts? Other then setting up in the config 9999... failures??

**Comment by tabarra** [comment]
Why would you do that?

**Comment by BroodLK** [comment]
Honestly he probably just has a long loading script and only needs to change the cool down to accommodate for the super slow script rather than fixing the script

**Comment by tabarra** [comment]
Well, github just isnt the right place for this questions, join our discord.
