### ISSUE TITLE
[BUG] Game crash when noclip

### ISSUE THREAD

**Issue by kenjischier** [citizenfx/txAdmin#540]
When I and my staff members use noclip after a certain we crash. Maybe you can optimize your script, or fix this issue?

**Comment by ghost** [comment]
thank you for providing the needed information for a bug report. this might just be the most useless issue request txAdmin has ever seen

**Comment by TasoOneAsia** [comment]
> Maybe you can optimize your script, or fix this issue?

I have not had a crash as a result of entering noclip anytime in my many hours of testing. If you have solid reproduction steps, please reopen this issue with those included.
