### ISSUE TITLE
[BUG] Recipe doesn't deploy correctly

### ISSUE THREAD

**Issue by BestRazer** [citizenfx/txAdmin#543]
**txAdmin/FXServer versions:**
txAdmin: v4.10.0
  
**Describe the bug**
When trying to deploy a recipe, this error appears in the console:
`[txAdmin:WebServer:anonym] [txAdmin v4.10.0] Route timed out: /deployer/recipe/setVariables`

**To Reproduce**
1. Create a new server
2. Choose QBCore or any other popular template
3. Configure the key and database
4. Click on 'Save'
5. The error should appear in the console

**Expected behavior**
The recipe should be deployed and the QBCore framework should be installed.

**Screenshots**

**Additional context**
The server is hosted on a pterodactyl panel.

**Comment by tabarra** [comment]
Could not reproduce.

**Comment by tabarra** [comment]
I'm closing this due to no other reports matching this description.  
If you have any new information feel free to provide here.

**Comment by Deadgaminglive** [comment]
im having this same issue

**Comment by Deadgaminglive** [comment]
did you find a fix?
