### ISSUE TITLE
[BUG] Typing broken in some settings tabs

### ISSUE THREAD

**Issue by carlos55ml** [citizenfx/txAdmin#550]
**txAdmin/FXServer versions:**
v4.11.0 fxserver: 5143
  
**Describe the bug**
When in some tabs of the settings page, trying to type in some fields will constantly move your cursor to the start of the paragraph, forcing you to type backwards.

**To Reproduce**
1. Go to settings page
2. go to fxserver settings
3. use "aditional arguments" field for this example
4. try to type anything

**Expected behavior**
Not normal behavior of typing. it should write letter after letter

**Screenshots**
Gif of trying to type in that specific field: [https://carlos55ml.is-horny.wtf/9leZFXhddL.gif](https://carlos55ml.is-horny.wtf/9leZFXhddL.gif)

**Additional context**
Hosted in windows 11 machine.
It also happens in "Whitelist Rejection Message" in player manager tab and in "Status Command Message" in discord tab.

**Comment by tabarra** [comment]
Fixed already.
