### ISSUE TITLE
[BUG] Adding or Changes in Discord setting is not saving

### ISSUE THREAD

**Issue by sandunisuru** [citizenfx/txAdmin#551]
**txAdmin/FXServer versions:**
v4.11.0 atop FXServer 5149/ZAP
  
**Describe the bug**
When I tried to change discord settings in the Settings tab. It is not saving correctly. I can see some error on console when I click on the Save button.
![image](https://user-images.githubusercontent.com/27560724/147841805-eadf2b92-5fe0-473b-90bd-46c0f568b967.png)

**To Reproduce**
1. Go to 'Settings'
2. Click on 'Discord Tab'
3. Click on 'Save Discord Settings' Button
4. Settings is not saving and after opening the error you can see error in screenshot

**Expected behavior**
Settings need to be updated

**Screenshots**
![image](https://user-images.githubusercontent.com/27560724/147841819-072ff980-9488-4686-a024-cb8bc19301dd.png)

**Additional context**
Happening for adding new and updating both things

**Comment by ghost** [comment]
This is a known issue with v4.11. 

Quick Fix: Inside the artifact folder, go to <citizen>\system_resources\monitor\web\settings.html and add this missing dot at the line 709.
For linux, it is on alpine/opt/cfx-server/citizen/system_resources/monitor/web.

**Comment by ghost** [comment]
![img](https://cdn.discordapp.com/attachments/578045190955335691/922876425017626674/unknown.png)

**Comment by sandunisuru** [comment]
Issue is I'm using zap tx admin game server

> This is a known issue with v4.11.
> 
> Quick Fix: Inside the artifact folder, go to \system_resources\monitor\web\settings.html and add this missing dot at the line 709. For linux, it is on alpine/opt/cfx-server/citizen/system_resources/monitor/web.

**Comment by ghost** [comment]
There is no way to fix the bug with ZapHosting. You will need to wait for a new artifact update.

Source: Tab, via txAdmin Guild

**Comment by sandunisuru** [comment]
Okay, thanks then.

**Comment by ghost** [comment]
This issue can be closed if it's been resolved with an answer.
