### ISSUE TITLE
[BUG] Discord bot not saving config in the txAdmin panel

### ISSUE THREAD

**Issue by lunasupps** [citizenfx/txAdmin#554]
**Config won't save**
**---------------------**
When I try to save the discord bot config in the txAdmin panel, the one that the server status command is supposed to show (see attached image), the save button doesn't work. The discord bot is still online and responds if you put in the **status** command, but it only shows what was saved before the most recent update since you can't save new configuration.
  
**Hope this gets resolved in the next update <3**

![image](https://user-images.githubusercontent.com/65740751/147892051-24832dbd-b32c-4b4e-b17c-8c9270b5acb5.png)

**Comment by ghost** [comment]
Please see this info [here](https://github.com/tabarra/txAdmin/issues/551).

Issue can be closed.
