### ISSUE TITLE
[BUG] <Nametag>

### ISSUE THREAD

**Issue by Udolfoo** [citizenfx/txAdmin#555]
**txAdmin/FXServer versions:**
FXServer-master v1.0.0.5156 linux / txAdmin Version: 4.11.0
  
**Describe the bug**
Nametag doesnt show Name on other Players just Healthbar

**Screenshots**
[
![image](https://user-images.githubusercontent.com/281524/148105215-6957373c-2005-42ae-a3d6-20a773b29d0c.png)
](url)

**Comment by TasoOneAsia** [comment]
No changes to this section of the code have been made recently. Are you using the new game build?

**Comment by Udolfoo** [comment]
Yes FXServer-master v1.0.0.5156 linux

**Comment by TasoOneAsia** [comment]
I meant specifically the latest GTAO build, not FiveM/FXServer.

**Comment by Udolfoo** [comment]
Yes ive got the last update on rockstar games anyone else got also this Problem

**Comment by douth-c-archive** [comment]
Writing on behalf of "Goblina♠#2914" via txAdmin guild.

This has been reported again [here](https://cdn.discordapp.com/attachments/589106731376836608/942139410126893076/unknown.png).

Details: v4.12.1 atop FXServer 5327 
Details: Standalone, no framework.

Not much more information provided.

**Comment by tabarra** [comment]
Since we are using the built in tags, i arrived to the conclusion weirdness surrounding it is usually another resource interfering.
