### ISSUE TITLE
[Feature]: Registering slash commands

### ISSUE THREAD

**Issue by Andrea-98** [citizenfx/txAdmin#558]
### Scope

Web

### Feature Description

Registering slash commands of discord bot and update at last version of discord.js

### Additional Info

visit: https://discordjs.guide/interactions/registering-slash-commands.html

**Comment by tabarra** [comment]
We can't update discord.js.  
We may end up changing to https://www.npmjs.com/package/eris

**Comment by tabarra** [comment]
Done.
