### ISSUE TITLE
[BUG] Everyone see the "noclip" storm when you use noclip by the player menu

### ISSUE THREAD

**Issue by Neo1030** [citizenfx/txAdmin#559]
Sometimes, when you use the noclip menu, the storm appears for all the player.

**Comment by TheNeo2k** [comment]
I believe this is intended? better than appearing out of thin air....

**Comment by tabarra** [comment]
Well, if it's "sometimes" then it's a bug since it was supposed to happen every time.  
The particle effect on playermode change was mostly done to help prevent admin abuse like when an admin gives himself godmode right before a pvp fight.  
So others being able to see it was by design, as everybody around would see that the admin changed his playermode right before or during the fight.

**Comment by carlos55ml** [comment]
I think they mean everyone gets the effect on them.

**Comment by TheNeo2k** [comment]
So i've been testing on my live environment on 
Artifact 5181 
manually updated to latest release of txadmin. 
sv_enforceGameBuild 2545

Works as intended.

**Comment by tabarra** [comment]
Thanks Neo2k, i'll close Neo1k issue.

**Comment by Neo1030** [comment]
Sorry for my late response.
The problem I have noticed is that if I switch to noclip, all players on the server see a flash on themself.
if I'm at the airport and i switch in noclip mode, players in Paleto bay, or anywhere on the map, see lightning on themself.
I understood the interest of the storm, Neo2k, is it correct with you, after your tests?

**Comment by tabarra** [comment]
@Neo1030 Can you record a video of that?
Also feel free to join our discord: https://discord.gg/txadmin

**Comment by Neo1030** [comment]
I'm already on discord
We will do some tests this evenning, i will show you a video tonight

**Comment by TheNeo2k** [comment]
What was the result of this? So far I've had no issues using this feature?

**Comment by GeerdoDaGr8** [comment]
https://clips.twitch.tv/ExcitedQuaintButterTebowing-YTp9EcwD-XD0WPq2
I am still having this issue and I am on thge latest release

**Comment by TheNeo2k** [comment]
No denying that issue..... 
Does not seem to happen for us... onesync issue?

**Comment by GeerdoDaGr8** [comment]
> No denying that issue..... Does not seem to happen for us... onesync issue?

Im sure it is a one sync issue but it would be nice if it could and option to be toggled off so it doesnt happen

**Comment by Neo1030** [comment]
Great, you catch it in video!
3 peoples says they see the storm on my server, but don't catch it in video!
Sorry Neo2K, i was unable to give you the video sooner... can't reproduce the problem
