### ISSUE TITLE
[FEATURE] Customize the announcement notification placement

### ISSUE THREAD

**Issue by L4wlz** [citizenfx/txAdmin#561]
**txAdmin/FXServer versions:**
v1.0.0.5208
  
**Describe the bug**
We have a watermark placed at center top, same location where announcements popsup.. 
The problem is this.. every announcement send from the webpage txadmin, is placed in the background of my watermark. 
But if I use /txadmin in game and send an announcement from that it will be on the top.. so my watermark is behind the announcement. After that I can go back to the webpage and test announcement and then it is also on the top and that is the same thing for server restarting announcement.

It is important to start testing the announcement from txadmin webpage.

**To Reproduce**
1. Go to your txadmin page, send an announcement and see that the watermark is on the top.
2. Go into your server write /txadmin and send the announcement from that and see that announcement is placed on the top.
3. Go back to you txadmin and then test the announcements again, and that they are now placed on the top.

**Expected behavior**
In my opinion the announcement should be on the top no matter what.. Because it is an announcement and could be important information.. 

**Screenshots**
When sending the announcement from TXAdmin as the first step
[Example 1](https://imgur.com/a/pcGW4Lr)
When sending the announcement as the second one from /txadmin
[Example 2](https://imgur.com/ykKbFAh)
When going back to TXAdmin webpage and send a new annoucement
[Example 3](https://imgur.com/txjXa1E)

**Comment by xorzo1** [comment]
Why do you not just move the watermark to the corner or something?

**Comment by L4wlz** [comment]
We have other stuff placed there :( and we can not just move that part arround..

**Comment by GoatG33k** [comment]
@L4wlz, I think it might be more constructive to convert this bug report into a feature request.

Adding a simple option in the settings to specify the location of the announcement would be simple to implement, and also give servers the freedom to choose/customize.

**Comment by douth-c-archive** [comment]
I agree. This can be more of a addon feature, rather than just something txAdmin "fixes". I've seen the recommendation to change locations before, so it'll probably be looked at.

The enhancement label can be added, unless my cache hasn't updated @GoatG33k.

**Comment by L4wlz** [comment]
Awesome. Thanks.
Get the oppotunity to choose location will off cause be the best solution and make sense.
