### ISSUE TITLE
[BUG] txAdmin Bot Broken on v4.11

### ISSUE THREAD

**Issue by Georgie15** [citizenfx/txAdmin#565]
**txAdmin/FXServer versions:**
4.11.0 txAdmin
  
**Describe the bug**
The discord bot no longer will allow you to save settings in the txAdmin website and bot is offline and not working.

**To Reproduce**
Update to the latest 4.11.0 version of txAdmin

**Expected behavior**
The bot to respond to /status or whatever commands set.

**Comment by NonStopGamer** [comment]
So update to v4.12

**Comment by Georgie15** [comment]
> So update to v4.12

Updated to the most recent FiveM artifacts and was still stuck on v4.11.0

**Comment by douth-c-archive** [comment]
Artifact do not include the latest version of txAdmin. This should be fixed soon; Bug report can be closed. Join our Guild (discord.gg/txAdmin) for further details on manually replacing `monitor`.

Nepty
