### ISSUE TITLE
[BUG] Unable to enable IPV6 for fxserver

### ISSUE THREAD

**Issue by Dennis-NL** [citizenfx/txAdmin#568]
**txAdmin/FXServer versions:**
4.11.0
  
**Describe the bug**
I cannot enable IPV6 as i get the error "You MUST have at least one endpoint_add_tcp in your config"

**To Reproduce**
Change **endpoint_add_tcp "0.0.0.0:30120"** and **endpoint_add_udp "0.0.0.0:30120"** to **endpoint_add_tcp "[::]:30120"** and **endpoint_add_udp "[::]:30120"**

FXserver needs [::] as the ip to be able to use IPV6. 0.0.0.0 will not work

![Screenshot_5](https://user-images.githubusercontent.com/43215753/150679197-5310e5c3-4fb4-4604-9a2a-ad4e62c580ff.png)

**Comment by tabarra** [comment]
Thanks for the report.  
This issue has been solved and will be available as soon as v4.15 is released.
