### ISSUE TITLE
windows high cpu use

### ISSUE THREAD

**Issue by DNDdjay** [citizenfx/txAdmin#57]
https://gyazo.com/d95231a24e1b1b93d3ff328c87b60728
https://gyazo.com/0726530281dd192bc4342306fb829b1b

**Comment by DNDdjay** [comment]
https://gyazo.com/6cbaf07c78e0bafaec5eb69079c473d7

**Comment by DNDdjay** [comment]
when i turn on the txadmin and logon too the console then its get my server slow with the high cpu use and high ping over 1600 ms and i have no problem with the internet

**Comment by DNDdjay** [comment]
https://gyazo.com/0393e9ee196e58d1768a2c00b6c948b0

**Comment by tabarra** [comment]
Dude, this is not discord.
