### ISSUE TITLE
[BUG] Cfx.re login use forum id instead of username

### ISSUE THREAD

**Issue by TheIndra55** [citizenfx/txAdmin#571]
**txAdmin/FXServer versions:**
 4.11.0 / 5273
  
**Describe the bug**
Currently the citizenfx provider login uses the current forum username as id instead of the real forum user id, thus changing your username on the forums will result in no longer being able to login

This issue is mentioned a lot in moderation inbox after people had their username changed

**To Reproduce**
N/A

**Expected behavior**
The forum user id will be used instead of the username and the user can still login even though their username is different

**Screenshots**
![image](https://user-images.githubusercontent.com/15322107/151580446-6190468c-c497-46af-9c50-65161f846380.png)

**Additional context**
N/A

**Comment by frazz1234** [comment]
Me too..

**Comment by tabarra** [comment]
Issue noted, thanks for informing.

**Comment by Doxylamin** [comment]
> Issue noted, thanks for informing.

FYI: You can resolve `fivem:` identifiers (which are essentially the forum IDs) to their respective username using https://policy-live.fivem.net/api/getUserInfo/:userid

e.g. `fivem:89762` -> https://policy-live.fivem.net/api/getUserInfo/89762 -> result.username

**Comment by tabarra** [comment]
@Doxylamin Yup, that's what I'm using.  
https://github.com/tabarra/txAdmin/blob/master/src/webroutes/adminManager/actions.js#L93

**Comment by tabarra** [comment]
Done.
