### ISSUE TITLE
[BUG] Javascript Error when server crashes

### ISSUE THREAD

**Issue by Tallerik** [citizenfx/txAdmin#575]
**txAdmin/FXServer versions:**
 v4.12.0 atop FXServer 5181 
  
**Describe the bug**
I'm not completely sure what happens there. Every time the Gameserver crashes, it prints a JavaScript memory related error to the console. I'm not sure if that error raises because of the crash or if the server crashes because of the error.

```
<--- Last few GCs --->

[694322:0x7f78916625f0] 14456488 ms: Scavenge 1152.0 (1427.8) -> 1151.6 (1436.4) MB, 2.6 / 0.0 ms  (average mu = 1.000, current mu = 1.000) allocation failure 
[694322:0x7f78916625f0] 14456506 ms: Scavenge 1157.0 (1436.4) -> 1157.0 (1436.8) MB, 3.2 / 0.0 ms  (average mu = 1.000, current mu = 1.000) allocation failure 
[694322:0x7f78916625f0] 14456512 ms: Scavenge 1157.2 (1436.8) -> 1156.0 (1454.4) MB, 4.0 / 0.0 ms  (average mu = 1.000, current mu = 1.000) allocation failure 


<--- JS stacktrace --->

V8 error at Reached heap limit: Allocation failed - JavaScript heap out of memory[                 Any] Error: V8 error at Reached heap limit: Allocation failed - JavaScript heap out of memory
> quit "Server Restart (Crash erkannt)."
```
("Crash erkannt" is german for "crash detected")

**To Reproduce**
Don't really know if there's a pattern for this. I just noticed a raising amount of crashes since a few days and this is the error I found in the fxserver.log

**Expected behavior**
The server not to crash **or** the error not to raise when the server crashes

**Additional context**
`lsb_release -a`
```
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 20.04.3 LTS
Release:        20.04
Codename:       focal
```
`free -h`
```
Mem:           23Gi       2.7Gi        10Gi        12Mi       9.8Gi        20Gi
Swap:         2.0Gi          0B       2.0Gi
```

**Comment by tabarra** [comment]
This is an issue with your fivem server, not txadmin.  
Probably some node resource leaking memory.
