### ISSUE TITLE
[Feature]: Edit Bans

### ISSUE THREAD

**Issue by PC1up** [citizenfx/txAdmin#578]
### Scope

Web

### Feature Description

I want to have the ability to edit existing bans (basically edit reason & duration) so you don't have to revoke the ban and create a new one because this really fucks up the players history.

### Use Case

Imma just use an example from my server. A player got banned because he has an custom crosshair enabled. He appealed and we agreed to reduce his ban from 2 days to one. In that case a function like that would be very helpful.

**Comment by douth-c-archive** [comment]
+1 - I can see this being somewhat useful when needed.

**Comment by ItsLynox** [comment]
+1 - I understand how this would be so good. In the meantime you could just revoke the ban and re-ban with updated time.

**Comment by tabarra** [comment]
How could this be tracked?  
Like, if a ban is changed, you would need to know who edited, what changed, when it was changed, and what was the reason.  
This sounds like a nightmare both to handle in the database and to show in the interface... but doable.  
  
Another question: would be okay to block editing expired and revoked bans?  
  
**ps.: if anyone has any input, _right now_ is the time to say as I'm rewriting the database.**

**Comment by PC1up** [comment]
> Another question: would be okay to block editing expired and revoked bans?

Of course, it's just about editing active bans so you don't always have to revoke the ban and create another one since this really fucks up the player's history

**Comment by tabarra** [comment]
I decided against this feature, due to:
- Nobody else asked for it;
- The database is already more complicated than it looks, I don't want to add this complication as well;
- Same for the UI, space is tight for information on the history tab and players page;
- "editing history" is always kinda icky for me;
- Not even discord has this option, so it's probably fine...
