### ISSUE TITLE
Cant disable conservative mode

### ISSUE THREAD

**Issue by robertne13** [citizenfx/txAdmin#58]
partial crashes detected and we cant disable the option in settings

**Comment by NoobKeksTV** [comment]
why should this be an issue? The Feature is there so that ur Server Auto-Restarts if crashed.

**Comment by tabarra** [comment]
That's pretty much by design.  
Why would you not want the server to restart after a partial crash?  
When that happens the server stop working correctly and new players cant join.


We even wait 5 minutes before restarting.

**Comment by NoobKeksTV** [comment]
stop repeating after me @tabarra. I'll ban u! Be warned! (ly)

**Comment by robertne13** [comment]
O hace a 80 slot esx server workshop great 12 ha started by tu server.bin runs great 12hsnon Linux pterodactyl panel runs great on tcadmin 2.0 Windows + 12 hours anda on tcadmin i can't ver working great more than 4 hours i hace doble Xeon Windows server 2019 with 96gb rambso this Is nota the problema and when ir runs standalone works perfect. O hace dime protección Anti esos that make dime micro cita on playera when i hace bien atacked i Think that Is the problem if i can ver a dump off partido crash with IP i can check with Anti ddos or if i can disable i could try  if the problem Is the protection

**Comment by NoobKeksTV** [comment]
How about speaking englisch?
And full sentences so anyone can understand you?

**Comment by w33ts** [comment]
> I have a 80 slot esx server works great 12 hs started by runserver.bin runs great 12hs on Linux pterodactyl panel runs great on tcadmin 2.0 Windows + 12 hours i can't get working great more than 4 hours i have doble Xeon Windows server 2019 with 96gb ram so this Is not a the problem and when ir runs standalone works perfect. I have a ddos protection Anti ddos make micro cuts on some players when i have been atacked i Think that Is the problem if i can see a dump off when crash with IP i can check with Anti ddos or if i can disable partial crash i could try if the problem Is the protection by the way muy protection Anti ddos works great with attacks 50gbps so i'll never change it

Operator error. Learn systems administration.

**Comment by robertne13** [comment]
I have an 80-slot server with an average of 64 daily users, the server if I start it from runserver.bat works perfect until 12 hours, if I start it with tcadmin too, the problem is that with txadmin it works 4 hours maximum and partially crashes crash, I think it is because of the protection that makes small micro cuts when we are under attack , I wanted to see if this function can be deactivated even if it is editing the src files thanks. sorry for my English.

**Comment by tabarra** [comment]
Highly doubt that's the reason, for a partial crash you need to have the HTTP endpoint offline for 300 seconds (5 minutes).  
If you manage to get more information on this subject, make sure to tell us.

**Comment by LevineRoss** [comment]
Restarting this thread - Same issue we just had.
