### ISSUE TITLE
[Feature]: Diacritical font

### ISSUE THREAD

**Issue by Fanttomas** [citizenfx/txAdmin#580]
### Scope

In-Game Menu

### Feature Description

Add an diacritical font when you turn on id. In the txadmin menu.

### Additional Info

![image](https://user-images.githubusercontent.com/97748713/153712728-0978d7eb-64de-4b0e-96b3-014d4400fbe8.png)

**Comment by tabarra** [comment]
I'm pretty sure we are locked to the game default font since we are using a native to display the player tag.  
Does that chat get squared in gta online as well?  
https://github.com/tabarra/txAdmin/blob/master/scripts/menu/client/cl_player_ids.lua#L44

**Comment by Fanttomas** [comment]
You can't write surety or diacritics there: D

**Comment by Fanttomas** [comment]
But speaking of those problems :D Sometimes it happens that when I press the backspace in spectate mode I get a black screen :(

**Comment by Fanttomas** [comment]
infinite black screen

**Comment by tabarra** [comment]
Well, so I'll classify this as a "game bug".  
Regarding the black screen, we have a dedicated issue for that.
