### ISSUE TITLE
[Feature]: have and option to select which wild attack

### ISSUE THREAD

**Issue by didar-dev** [citizenfx/txAdmin#581]
### Scope

In-Game Menu

### Feature Description

have an option to select which wild  attack
I think its better so I can always send the monkey

**Comment by xorzo1** [comment]
Why would they get so in depth for a troll option?

**Comment by didar-dev** [comment]
> Why would they get so in depth for a troll option?

why not?

**Comment by tabarra** [comment]
> why not?

Mainly because every second we spend on troll action is a second less we spend on literally anything else.

**Comment by douth-c-archive** [comment]
Seems like a useless feature to spend time working on.

**Comment by TasoOneAsia** [comment]
If this is a common feature request, we can reconsider *or* somebody can make a PR with these features added.
