### ISSUE TITLE
[BUG | FEATURE] Shutting down the Server through "quit" results in a restart

### ISSUE THREAD

**Issue by NecronomiconCoding** [citizenfx/txAdmin#582]
**txAdmin/FXServer versions:**
v4.12.1
  
**Describe the bug**
- When running ExecuteCommand("quit") inside a resource to shut down the server, txAdmin thinks the server has crashed. 

**Expected behavior**
- Either allow user to turn off the auto restarter, or add a shutdown event, so resources have the ability to shutdown the server - server sided.

**Comment by tabarra** [comment]
This can only be solved through an API.  
Please contribute to https://github.com/tabarra/txAdmin/issues/442
