### ISSUE TITLE
[BUG] Fall to ground when you are in noclip

### ISSUE THREAD

**Issue by jolie-croquette** [citizenfx/txAdmin#587]
**txAdmin/FXServer versions:**
v4.13.0 atop FXServer 5365
  
**Describe the bug**
When I put myself in noclip my character falls to the ground and the people around hear the fall of my character

**To Reproduce**
1. Go to 'txadmin menu ingame'
2. Click on 'noclip'
4. Fly near the floor
4. You will hear your character fall to the ground
(You can test it with another person who will have the name activated. She will hear the person fall and see them fall with the names above the head)

**Expected behavior**
To not fall to the ground when you are in noclip cause everybody can hear you

**Comment by tabarra** [comment]
Couldn't reproduce.  
Check if you are running some anticheat that forces `SetEntityCollision`, `FreezeEntityPosition` or `NetworkSetEntityInvisibleToNetwork`.

**Comment by tabarra** [comment]
Closed due to inactivity.
