### ISSUE TITLE
[BUG] Recipe Doesnt Deploy Properly

### ISSUE THREAD

**Issue by BeyondHawkeye** [citizenfx/txAdmin#597]
Latest Version downloaded today (3/8/2022)
  
The bug is legit as it goes to deploy the recipe, it just fails basically right away. I have followed video guides as well as had a friend who has done this before help me. I see that it may be some sort of permission issue, but im not quite sure what to do to solve it.

To Reproduce
1. Setup local hosted server using XAMPP
2. Go to deploy recipe
3. Fails task1

I expected it to just work, but for some reason it just wont deploy the recipe right.

![image](https://user-images.githubusercontent.com/101167584/157179950-042d71e4-465d-4c34-84cd-d80a38bd5e24.png)

**Comment by tabarra** [comment]
Thanks for posting this issue.  
This is not the latest version, and a new one will be available tomorrow to help us diagnose this issue.
