### ISSUE TITLE
[BUG] <QBCore Framework Install Problem>

### ISSUE THREAD

**Issue by ghost** [citizenfx/txAdmin#599]
**txAdmin/FXServer versions:**
txAdmin version: 4.13.1
FXServer build: 5367
  
[task89:download_github] failed!
Message: getaddrinfo ENOTFOUND api.github.com
Options: 
{
  "action": "download_github",
  "dest": "./resources/[qb]/qb-clothing",
  "ref": "main",
  "src": "https://github.com/qbcore-framework/qb-clothing"
}
Every time I try to install qbcore I get an error when I remove the task from the thing it gives me another and so on so forth I just need to install qbcore and been having a headace the entire time.

**To Reproduce**
1. Install qbcore from the popular template list
2. I used phpmyadmin for the database
3. wait for it to install it will get a little bit but then show the error above may be for different addon

If you would like to try it on my vps to see for your self contact me on discord HeroBryant2014#0001

**Comment by tabarra** [comment]
This is not an txAdmin bug.  
Clearly your host is not being able to resolve this (valid) domain.  
Maybe you are using a VPN or some weird DNS provider.  
If you want, change your DNS servers to 1.1.1.1 or 8.8.8.8
