### ISSUE TITLE
FXServer.exe stopped working

### ISSUE THREAD

**Issue by Javier-Diez** [citizenfx/txAdmin#6]
When the terminal stops working with the following pop-up which only lets you click "accept" the server spams the discord log and doesn't restart. It stays unoperative until someone manually clicks "accept" in the popup.

**Comment by tabarra** [comment]
Could you provide us any screenshot or log to help us troubleshoot this?

**Comment by Javier-Diez** [comment]
I closed the window but it was this with instead of "Microsoft Explorer" "FXServer" [](https://images.drivereasy.com/wp-content/uploads/2016/12/img_585753d6e1329.jpg)

**Comment by Javier-Diez** [comment]
I closed the window but it was this with 

> FXServer

 instead of 

> Microsoft Explorer

[Photo](https://images.drivereasy.com/wp-content/uploads/2016/12/img_585753d6e1329.jpg)

**Comment by tabarra** [comment]
While the prompt is open, can you still navigate the web panel?  
If so, then probably FXAdmin can still detect the failure and restart the server.

**Comment by Javier-Diez** [comment]
It can't restart the server, it doesn't work and yes I can still access the panel

**Comment by tabarra** [comment]
Try the newest version  
`git checkout 5b16b8effa77dfd0bb9f79b14e91404cfb058328`

**Comment by Javier-Diez** [comment]
I have v0.9.0

**Comment by tabarra** [comment]
The version I said is newer, It's in the development branch

**Comment by tabarra** [comment]
I'll close this issue.  
If there is any new information make sure to post here.
