### ISSUE TITLE
Issues with restarting or stopping/starting the server

### ISSUE THREAD

**Issue by VirtualJunky** [citizenfx/txAdmin#60]
When first launched on fresh boot of Windows, server starts up no problem and functions. Once the server is restarted, or stopped then started, we get this error in console during startup:

Started resource txAdminClient
Listening on socket failed - libuv error address already in use.
net-tcp-server failed to create server: couldn't listenCould not bind MultiplexTcpServer to 0.0.0.0:30120.

It's like it's not unbinding the IP or port when shutting down. Running on fresh install of Windows Server 2012 R2, fully updated.

**Comment by tabarra** [comment]
txAdmin doesn't handle any port other than 40120 (or the one you configured).
Also, your windows is pretty old, on those the server doesn't start correctly so might not be getting stopped correctly.  
  
Please update your Windows Server to version 2016 (or above) and tell me if it works.  
For now I'm closing this issue.  
Also, feel free to join our discord in case you still need support.
