### ISSUE TITLE
[BUG] Menu Identifier error

### ISSUE THREAD

**Issue by Richzombie** [citizenfx/txAdmin#600]
**txAdmin/FXServer versions: 5399**
You can see that at the bottom of the txAdmin page, or in the terminal as soon as you start fxserver.  
  
**Describe the bug**
When writing the /tx command in the server I get the error that there is no admin with these identifiers, even though its added in the txadmin panel correcty, it also throws an error in F8

**To Reproduce**
1. Host a server on linux ( where we tested this, windows localhost didnt seem to give issues, however i doubt thats the case)
2. Add your identifiers as Admin
3. join the game and write /tx
4. You get the warning and an error message in F8

**Expected behavior**
Expected behaviour is no error messages and correct recognition of identifiers so we can access the admin menu

**Screenshots**
![unknown](https://user-images.githubusercontent.com/101681002/158495971-e0e1f87e-e998-4d77-8e11-27e13a27e2dd.png)

**Additional context**
We're hosting on Linux dedi instead of a Windows machine

**Comment by tabarra** [comment]
This will only happen when the auth request doesn't come from "localhost".  
Usually an issue with GSPs that are not zap hosting.  
Please join our discord to help you troubleshoot this, but i don't think we can classify this as an bug.
