### ISSUE TITLE
[BUG] Player tags show only HP, but not the name or ID.

### ISSUE THREAD

**Issue by tabarra** [citizenfx/txAdmin#602]
**txAdmin/FXServer versions:**
tx: v4.13.3
fxs: 5411
  
**Describe the bug**
Player tags show only HP, but not the name or ID.

**To Reproduce**

**Screenshots**
![image](https://user-images.githubusercontent.com/1808295/159123358-e53e0444-aa2a-4fb0-a342-7de749b636ca.png)

**Additional context**
Posted by `@DerPeter77#9543` on discord.  
Report states this happened on normal player id view instead of on spectate mode.  
Server is `infinity with 128 slots`.

**Comment by ghost** [comment]
[  script:es_extended] [WARNING] Server callback "relisoft_tag:getAdminsPlayers" does not exist. Please Check The Server File for Errors!
This is in the console.

**Comment by DerPeter77** [comment]
I have now the solution: you have to download relisoft nametags and put it in the es_extended folder and name it: relisoft_tag:getAdminsPlayers

**Comment by tabarra** [comment]
This esx thing is likely not related.

**Comment by ghost** [comment]
I tested now everything and if I restart es_extended in game then it works but only then and I can`t restart every time es_extended in game

**Comment by PC1up** [comment]
Make sure you don't have any other nametag scripts installed. @DerPeter77

**Comment by tabarra** [comment]
@PC1up Yeah i'm pretty sure you are correct, this is another resource hiding the player IDs.  
Furthermore, this is stale so I'm closing it.
