### ISSUE TITLE
[Feature]: Chat Command to ban someone

### ISSUE THREAD

**Issue by PC1up** [citizenfx/txAdmin#604]
### Scope

In-Game Menu

### Feature Description

 Pretty simple, just a chat command to ban someone quickly (e.g. modders). Just, for example, /txban [ID] [Reason] and the guy gets banned permanently. Cuz if you want to ban someone temporarily you most probably have the time to open up the menu and smth like that.

### Use Case

As I already said, this would be pretty useful if theres a modder on ur server and u have to ban him quickly but have to wait until the txadmin menu shows up, etc.

**Comment by tabarra** [comment]
I can see this being useful, but code duplication would be an issue.  
Also we have a lot of features, and having a `/tx***` for every command would be annoying.  
The compromise is that you can type `/tx <id>` and the ban is just one reason and two clicks away.
