### ISSUE TITLE
[BUG] Warn localization not working if menu is disabled

### ISSUE THREAD

**Issue by manzarek123** [citizenfx/txAdmin#606]
**txAdmin/FXServer versions:**
4.13.3/5429  
  
**Describe the bug**
Localization is not working for Warns when menu is disabled in TxAdmin config

**To Reproduce**
1. Set Langage to French in Settings->Global 
2. Enable the Menu in  Settings->Menu
3. Restart Server
4. Warn a player => NUI Warn menu is in French
5. Disable the Menu in  Settings->Menu
6. Restart Server
7. Warn a player => NUI Warn menu is in English

**Expected behavior**
Warns to be in the correct langage with Menu Disabled

**Comment by tabarra** [comment]
Confirmed.  
Related to #608.

**Comment by TasoOneAsia** [comment]
The bug can most likely be attributed to improper ServerCtx event listener logic for clients *when* the menu is disabled. During local testing with the menu disabled, clients never receive the "setServerCtx" event upon update of web settings. ServerCtx is updated within GlobalState but the event is never properly dispatched to clients, as we never populate the TX_ADMINS table when the menu is disabled.

[Here ](https://github.com/tabarra/txAdmin/blob/af77cca07bcd9ba249640b440693988f10e2d8d0/scripts/menu/server/sv_base.lua#L136-L142) is where its blowing up

In fact, after glancing over some of the code, does localization even work in NUI for servers that don't enable OneSync?

**Comment by tabarra** [comment]
Confirmed that this is still a thing in v5, even though #608 was fixed some time ago :(

**Comment by tabarra** [comment]
Issue finally fixed.  
Will be available on the next update.
