### ISSUE TITLE
[BUG] Menu translation only works after tab change

### ISSUE THREAD

**Issue by tabarra** [citizenfx/txAdmin#608]
**txAdmin/FXServer versions:**
v4.13.3
  
**Describe the bug**
Whenever you open the menu, it will always be english, until you press tab.  
This is surely related to serverCtx sync that changed a few versions ago, since it is already in the dependencies of `menu\src\components\MainPage\MainPageList.tsx`.

**Comment by TasoOneAsia** [comment]
Cannot reproduce bug on local environment. When updating Locale from settings page in Web UI, the Menu and subsequent locale phrases are immediately updated upon receival of "setServerCtx" message event.

**Comment by tabarra** [comment]
Oh that's 100% a game thing, related to serverCtx updates.  
Since forever reviewing the serverctx thing has been on my list - which will happen with the review of the two debug variables, and prints.

**Comment by TasoOneAsia** [comment]
> Oh that's 100% a game thing, related to serverCtx updates.

hm weird, serverCtx updates through both GlobalState bag and through Get-Set serverCtx event fallback were functioning fine when I was testing.

**Comment by tabarra** [comment]
Confirmed that this has been fixed.  
IDK which version fixed it though.
