### ISSUE TITLE
[BUG] Task Failed

### ISSUE THREAD

**Issue by W0lv3sxD** [citizenfx/txAdmin#609]
Versions tx/FiveM
4.13.3/5402
  
Hey,

Running any Recipe leads to an error. I dont know how to fix that. The website that its trying to donwload from is working.

![Screenshot 2022-03-25 220059](https://user-images.githubusercontent.com/93610323/160254324-402b87ca-bf22-4711-8f90-8d901a02ec42.png)

**Comment by tabarra** [comment]
This is very very likely due to this issue: https://github.com/axios/axios/issues/4536  
I'll close this issue because it seems like I already have a solution for it (replace `axios` with `got`).  
Thanks for the report though.
