### ISSUE TITLE
Translating

### ISSUE THREAD

**Issue by Sayrer0** [citizenfx/txAdmin#61]
How could I change the messages ingame when the server is gonna restart? for example

**Comment by tabarra** [comment]
To change the language of your Chat/Discord messages (eg restart warnings) go to `Settings > Global > Language`.  
If your language is not available, create a `locale/custom.json` file based on the English file (`en.json`). Then go to the settings and select the "Custom" language option.  
**Editing any other language file except for `custom.json` will break your txAdmin!**  
  
We strongly advise you to **NOT** try to edit any other files by yourself.  
This **WILL** lock you in the current version of txAdmin.
