### ISSUE TITLE
[Feature]: Export PlayerHasTxPermission

### ISSUE THREAD

**Issue by Nova-px** [citizenfx/txAdmin#611]
### Scope

Developer API

### Feature Description

Add the PlayerHasTxPermission function as an export to check if a player has permissions in another resources

### Use Case

As an example: Checking if a player has permissions to spectate someone for anticheats

### Proposed Solution

Add that to the fxmanifest.lua

`exports {
    "PlayerHasTxPermission"
}`

**Comment by tabarra** [comment]
Duplicated of #442, do you mind posting there?
