### ISSUE TITLE
[Feature]: Filter Started and Non-started resources

### ISSUE THREAD

**Issue by P4R4NORM4L** [citizenfx/txAdmin#613]
### Scope

Web

### Feature Description

Have a button to display started or non started resources.

### Use Case

Some of us have a lot of resources, and when we restart a resource... some resources stop because of dependencies, so a quick way to bring them back online would be to have those buttons so we can toggle them back online. Also maybe not refresh the page once we click on start. 

### Proposed Solution

For the page refresh aspect of it, maybe using AJAX, but i'm not a web dev so I wouldn't know.

**Comment by douth-c-archive** [comment]
Could you provide a example?

**Comment by P4R4NORM4L** [comment]
yeah I can do that

**Comment by P4R4NORM4L** [comment]
![image](https://user-images.githubusercontent.com/17122685/163253885-2d72778d-3d38-4171-b994-fe0c3bdb9b63.png)

**Comment by P4R4NORM4L** [comment]
Hopefully this can help !

**Comment by douth-c-archive** [comment]
thanks.
