### ISSUE TITLE
[BUG] 0.0.0.0 wrongly needed

### ISSUE THREAD

**Issue by MathiAs2Pique** [citizenfx/txAdmin#619]
**txAdmin/FXServer versions:** FXServer build 5483
  
**Describe the bug**
txAdmin requires a 0.0.0.0 endpoint when it's not needed (I can start my server without txAdmin with my actual config, but it throws me this error when I try to launch it from txAdmin : 
`You MUST have one endpoint_add_tcp with IP 0.0.0.0 in your config`

**To Reproduce**
1. Edit your server.cfg
2. Put like endpoint_add_tcp "your_server_ip:30120"
3. Try to launch the server

**Expected behavior**
The server should start itself.

**Comment by tabarra** [comment]
Please search for `txAdminInterface` on the github issues.
