### ISSUE TITLE
[Feature]: Please make us able to change the message the bot sends on restart.

### ISSUE THREAD

**Issue by Ilaieri** [citizenfx/txAdmin#622]
### Scope

Web

### Feature Description

Please make us able to change the message the discord bot sends on restart and on server start.

### Use Case

I wanted to ping @everyone when the server started up but couldn't

### Proposed Solution

Make us able to edit the message

**Comment by tabarra** [comment]
Hey there.  
1. you can totally change the bot message, just use a custom locale (it's in the docs);
2. the bot code explicitly blocks mention of `@everyone` and `@here`;
3. this is a real real bad idea to use your `@everyone` like that. People don't like getting pinged for superfluous things.
