### ISSUE TITLE
[Feature] 2FA 

### ISSUE THREAD

**Issue by FrogCF** [citizenfx/txAdmin#626]
### Scope

Web

### Feature Description

Hi, 

Please add  two-factor authentication to the control-panels in-sure security always remain safe?

**Comment by aidenzybell** [comment]
It is self-hosted, so I don't think 2FA would even be an option here (or too complicated to even consider), but it also isn't needed because... it is self-hosted and also an admin panel for a game server that really doesn't have anything *super* sensitive like personal information on it.

**Comment by tabarra** [comment]
Can you please provide a realistic scenario where having passwords+2fa is safe, but only password would be unsafe?

**Comment by FrogCF** [comment]
Hi, 

Thank you for your message as you know Google always blocking open-ssl connections correct or flagging up you have such a benefit here use let's encrypt we could us sub-domain names connecting to our control panels and add extract security to the control panels with 2FA adding more security and giving person better comfort that their control panels are protected you don't have any brute-force so in a brute-force attack the attacker would eventually guessing the password correct this could upset a lot of server owners or if they got in the account with master permissions they could easily wipe server offline within seconds. So with 2FA as added protection wouldn't matter if they guessed the password right as still wouldn't be able again to access to the server if you didn't add 2FA add some sort of brute-force your control panel is lacking security.

**Comment by FrogCF** [comment]
> It is self-hosted, so I don't think 2FA would even be an option here (or too complicated to even consider), but it also isn't needed because... it is self-hosted and also an admin panel for a game server that really doesn't have anything _super_ sensitive like personal information on it.

Please, read my message might understand you're saying gaming control panel where most people have this open to port so I'm affair still could have an attack and if they gain access to the right account with master permissions then would wipe the server within seconds of a single click of a button how much of pain that would re-uploading or getting things back online when have a busy city so think about it.

**Comment by tabarra** [comment]
Sorry, but I found your answer incoherent.
- SSL is not a feature anymore in txadmin and you can add it via a reverse proxy (ex nginx, caddy or cloudflare);
- txAdmin absolutely does have brute force protection, in a month any IP can try at most 28800 passwords, unless your password is `admin123` they won't get in through brute forcing. Also your console will be spammed with the IP of the attacker so you can easily block it.
- Given that the scenario you proposed is borderline invalid, is there any other scenario where it would be the difference between be hacked or not?

I do recognize the value of 2FA, but the txAdmin scenario is quite special, as most servers owners share their ftp/rdp/ssh with other admins, so they would be able to check the TOTP secret.  
There are ways to mitigate it, but honestly just not worth the amount of interface changed we would need to do as well as the increased support time.  
For now I'm closing this issue, but may revisit it in the future or if any compelling argument comes up.
