### ISSUE TITLE
[BUG] WHEN U DIE AND HEAL with TX u GET DRUNK/DRUG AFTER HEAL<CamEffect>

### ISSUE THREAD

**Issue by Gameadictive** [citizenfx/txAdmin#627]
Im sure you know what im talking about.

You die, use the heal <id> then u still in floor and it comes a drug or drunk cam effect.

How to solve this?

**Comment by tabarra** [comment]
Did not follow the bug report template.  
And if you do so, please provide a video.

**Comment by douth-c-archive** [comment]
!1!11!!!!11!11!

**Comment by Emilandersson18** [comment]
hay
