### ISSUE TITLE
Ram/CPU usage (serverside) per plugin 

### ISSUE THREAD

**Issue by CruelAlpha** [citizenfx/txAdmin#63]
Hey,
I have been recently using etw traces to check performance on backend,

Is there any possibility to add any type of backend monitoring that show plugins that are running on the server and cpu msec/ram usage overtime (graphs)

Could be extremely helpful to track down troublesome plugins aswell check how each plugin reacts with different levels of traffic

**Comment by tabarra** [comment]
Currently all methods for us to do this is extremely hacky at best.  
We are integrating with FiveM tho, so who knows in the future.  
  
Edit: for now I'm closing this issue.

**Comment by NoobKeksTV** [comment]
U could use the Profiler. It shows which Plugins are running & causing which amount of lag. It can both be running on the Server & Client side but depends on having Google chrome installed (i dont know if firefox has the developer features needed)

https://forum.cfx.re/t/how-to-use-the-profiler-command-to-identify-problematic-scripts/809058?__cf_chl_captcha_tk__=0bdfc6dbc7b54be3ad4cd9ae36c394204fd277b8-1579192038-0-AZf_hfRu4XsAlAiljiuQlc0aqgOtj2dL_65VKltwLGBoLVdj5Ym-R81eZROv6QD8oyKeDzUlDFO5Tz3A-Igs6v_8C7ou6SkRyFzGbPGAV22VLWZco2yDQhOOdbBAYI47v-KIwO-umS7JlulQ6lAf-C1ueAXS0go3Lc9zaO-j7Tm1eUMtX2LXzpezT2CxoZ3TD7A9TCeFXmuOPdcZz_ZeBZY2o6mxJm9fTWlWX_hPjvbCXhqQcewJRPPzZCwirizRJ7YSBUlp37CSrrCqj-8glQFY7Ispo6DxPKgby2LzlgnYxM92FYsswBWHKn8gYeSJWK9WKKm4MG9LzijJumZ7gTsE7meZLMMLvUe7XeDEDYp2gk9siCJ15ALrXJe02bME7hItBBrfOZnp5SvtbLMqR19JBT8PiBfMDrzmf5dU-KTBHhsVAWQhif9Q3XjlWV-9c_YOHgtRq0vEGgBBqpisP6Q
