### ISSUE TITLE
[FEATURE]: "Skip next restart" button

### ISSUE THREAD

**Issue by PC1up** [citizenfx/txAdmin#632]
### Scope

Web

### Feature Description

Not necessary nor urgent, but kinda helpful. Just a button that skips the next upcoming restart (but only once) so one example:
Regular restarts at 3am, 6am, 12am and 6pm. You want to skip the 12am restart once so you click the button, it gets skipped but will be in effect automatically for the next 12am restart. As I said not necessary nor urgent, but helpful. I aint gonna be sad if this gets rejected.

### Use Case

e.g if you just did some maintenance work on your server and restarted it and you just dont want the users to experience more restarts then necessary, of course you could also just kick the restart out and place it in manually but i personally often forget it.

### Proposed Solution

i have absolutely no clue

### Additional Info

![image](https://user-images.githubusercontent.com/63553505/169337584-174845e9-c967-4eb9-8134-271c4d1bbbc1.png)
could be put somewhere here at the dashboard but im not picky

**Comment by tabarra** [comment]
Done in 0e268b6a7165d7ac2416d1d6e5871c7a8b6ca5e5
