### ISSUE TITLE
[BUG] Spectate bug

### ISSUE THREAD

**Issue by TheS1lenT619** [citizenfx/txAdmin#633]
**txAdmin/FXServer versions:**
5579
  
**Describe the bug**
When i try to spectate someone.. Everything is okay! But when i try to stop spectate someone i'm teleported under the map(and under the player which i tried to spectate) and i cannot move. You can check the video which is down.

**Expected behavior**
I expected when i press the button "Spectate" second time and i to be on my last position and not to be in noclip mode.

**Screenshots**
Check this video for more details  - https://imgur.com/vUd3LlH

**Additional context**
I'm using Linux OS.

I'm sorry for bad english guys

**Comment by tabarra** [comment]
But why you trying to exit spectate by pressing the spectate button again?
![image](https://user-images.githubusercontent.com/1808295/169414404-d79eab89-b9df-4c24-ac23-aac1349c1273.png)

**Comment by TheS1lenT619** [comment]
> 

Wow! Where was my eyes?! Okay.. It's not a bug! Just i'm blind!
