### ISSUE TITLE
[FEATURE]: Notification exports

### ISSUE THREAD

**Issue by Kaparrs** [citizenfx/txAdmin#645]
### Scope

Developer API

### Feature Description

Add exports for the notification system that is used for errors (Shown below) 
![image](https://user-images.githubusercontent.com/71441748/174759393-6356c4c3-7deb-4388-856a-da78b69636da.png)

### Use Case

Utilise this feature in scripts, for example: Simple notifications for players getting cash

### Proposed Solution

Add NUIMessages in client side and then add them into exports with several properties, I would have to check out the original source for the notification system: https://github.com/iamhosseindhv/notistack for the properties available.

### Additional Info

I think there are already made functions in the source, so could just use that, not sure how tho...

**Comment by TasoOneAsia** [comment]
Hi @JajarGaming

This would be a possible candidate for the txAdmin export API, it would be better to congregate thoughts and suggestions under #442.

I will say though, that having exports available for these internal notifications seems outside of scope for inclusion in a public API. txAdmin isn't a notification script, and users shouldn't be relying on txAdmin for that purpose.
