### ISSUE TITLE
[BUG] Rate limit Youtube video unavailable 

### ISSUE THREAD

**Issue by borisnliscool** [citizenfx/txAdmin#652]
**txAdmin/FXServer versions:**
4.15.1
  
**Describe the bug**
Really self-explanatory, the youtube video just doesn't load. (see screenshot)

**To Reproduce**
1. Go to the login page
2. Fail login attempts until you're being rate limited

**Expected behavior**
The youtube video to be played.

**Screenshots**
<img src="https://i.imgur.com/Ojj70l6.png">

**Additional context**
Browser is chromium-based, tried with and without vpn, both same issue. (must say this is about as low priority as you can get)

I think this happens with some Youtube videos that have over a certain view count.

**Comment by tabarra** [comment]
Are you using a domain name to access it?  
If so, youtube sometimes limits it.  
  
Can you open devtools and see the error message?

**Comment by borisnliscool** [comment]
There's no error message in the devtools for me, also not using a domain name. Disabling ad-blocker also has no effect.

**Comment by tabarra** [comment]
Well... wontfix, sorry.
