### ISSUE TITLE
[BUG] heal

### ISSUE THREAD

**Issue by InfoBlock** [citizenfx/txAdmin#654]
**txAdmin/FXServer versions:**
v4.14.2 atop FXServer 5652
  
**Describe the bug**
Healing yourself or the whole Server isn’t possible as the Heal Option on the Ingame Menu does nothing 

**To Reproduce**
Use the In-Game Menu and try healing yourself with the heal option

**Expected behavior**
You get full health 

**Screenshots**

**Additional context**
Add any other context about the problem here, like for example if it's a server issue, which OS is fxserver hosted on.

**Comment by tabarra** [comment]
Do you have any more information?  
Works for everybody else... you might be using s framework or anticheat that is not dealing well with the txAdmin heal event.
