### ISSUE TITLE
[FEATURE]: Support download git hub for private repository

### ISSUE THREAD

**Issue by caothienlong** [citizenfx/txAdmin#655]
### Scope

Web

### Feature Description

download_git_hub will also support download private repository. The url of repository would include Git Token such as below

git clone https://oauth-key-goes-here@github.com/username/repo.git

Thank you

**Comment by tabarra** [comment]
Thanks for the suggestion.  
I actually missed, but this one is dup of #349, which is still planned but not scheduled to be implemented.
