### ISSUE TITLE
[BUG] Restart announce buggy

### ISSUE THREAD

**Issue by BenMagNiemanden** [citizenfx/txAdmin#658]
**txAdmin/FXServer versions:**
txAdmin: 4.15.1 FXServer: 5686
  
**Describe the bug**
Whenever you restart the server, instead of displaying the name of the person who executed the command, it simply displays (admin request).

**Expected behavior**
The name of the admin who executed the command should be displayed

**Screenshots**
![image](https://user-images.githubusercontent.com/68700023/181535072-94d95833-0cce-4dc3-9218-1a4dee6bf29c.png)

**Comment by yozi00** [comment]
ffzfzfzfzfz
