### ISSUE TITLE
[BUG] The Clear Console Button does not Clear The Console Log

### ISSUE THREAD

**Issue by Tamer173** [citizenfx/txAdmin#667]
**txAdmin/FXServer versions:**
You can see that at the bottom of the txAdmin page, or in the terminal as soon as you start fxserver.  
  
**Describe the bug**

When Pressed The Clear Console Button it does not Clear The Console Log on Web !

**To Reproduce**

**Expected behavior**
Clear the Console
**Screenshots**

**Additional context**0
Here is the Video See The Problem :

https://user-images.githubusercontent.com/105336574/187025891-9241d88b-d2df-4bb7-ad05-10f1fa45fd79.mp4

Add any other context about the problem here, like for example if it's a server issue, which OS is fxserver hosted on.

**Comment by PC1up** [comment]
The txAdmin version clearly says "outdated" next to it. Update txAdmin and try again
EDIT: Note that the newest fxServer version does NOT mean that the newest txAdmin version is within that fxserver version!

**Comment by Tamer173** [comment]
> The txAdmin version clearly says "outdated" next to it. Update txAdmin and try again EDIT: Note that the newest fxServer version does NOT mean that the newest txAdmin version is within that fxserver version!

I have updated it to the latest release but the issue is that same see the video Below!

https://user-images.githubusercontent.com/105336574/187073813-b858914e-fd01-43b0-9b38-13764f3d1665.mp4

**Comment by PC1up** [comment]
Alright, yeah thats where my troubleshooting skills end.
Hint: Close the leaking websites before posting any screenshots/video recordings of your browser

**Comment by Tamer173** [comment]
> Alright, yeah thats where my troubleshooting skills end. Hint: Close the leaking websites before posting any screenshots/video recordings of your browser

i am lazy to edit the VIDEOO !!!!!!!

next time i will lol

**Comment by tabarra** [comment]
Could not reproduce the error on Chrome, Opera, Vivaldi or Edge.  
Maybe that's caused by one of the 99 extensions you have in Chrome?  
  
Try on another browser and please report back.

**Comment by Tamer173** [comment]
> Could not reproduce the error on Chrome, Opera, Vivaldi or Edge. Maybe that's caused by one of the 99 extensions you have in Chrome?
> 
> Try on another browser and please report back.

I tried it on the updated fresh chrome verision without any Extension and it still not works but works on every other Browsers, Thats all i have to say!

**Comment by tabarra** [comment]
Well, since:
- this is a minor issue;
- easy workaround (just use other browser);
- you are the first to report this issue (implying it's uncommon);
- this page will be entirely redone within a few months, so i don't want to put more time fixing it.

I reckon it's fine for me to just close this issue as a "won't fix".  
Sorry you are experiencing this issue, but soon enough this won't be a problem anymore
