### ISSUE TITLE
[BUG] txAdminInterface inGame menu issue

### ISSUE THREAD

**Issue by fasterplayer** [citizenfx/txAdmin#668]
**txAdmin/FXServer versions:**
FXServer build: 5834
txAdmin version: 4.17.1
  
**Describe the bug**
When starting the server (With Pterodactyl in my case) and specifying a txAdminInterface with `+set txAdminInterface SERVER_IP`, the inGame menu doesn't work. It will always say `Your identifiers do not match any admin registered on txAdmin`. I've done a lot of testing before realising that this ConVar causes this issue. 

**To Reproduce**
1. Use on server startup `+set txAdminInterface SERVER_IP`
2. Get in game
3. Try opening the menu `/tx`

**Expected behavior**
Should be able to use the menu

**Screenshots**
![image](https://user-images.githubusercontent.com/48169441/187058304-614653f2-55d5-48eb-b2d0-f5b44aa9cd80.png)
![image](https://user-images.githubusercontent.com/48169441/187058383-b207ae7f-f94a-427c-b4fe-c0167eb2054e.png)

**Additional context**
The server is hosted on Pterodactyl. As we are using a tunnel for ddos protection, i need to specify an ip to force txAdmin to use the tunnel ip instead of the host ip.

**Comment by tabarra** [comment]
If the server is running inside ptero (so, a container) why even bother setting an interface? Leave it as 0.0.0.0 and let the container supervisor handle the binding to the public IP.  
Same goes for port, you can run fxserver in 30120 and txAdmin in port 40120 and the host will be the one to do the binding of which interface/port will be bound to the container at which port.  
  
BUT if for some weird reason this is not enough for you, set `webServer.disableNuiSourceCheck` to `true` in your txAdmin config file (then restart tx, of course).

**Comment by fasterplayer** [comment]
Like i mentionned in my post, i need to specify the interface ip as it will bind with the host ip which is not what i need. If i could just specify the tx url when starting a server, that would work too. But i don't see any options to do so. So leaving it as 0.0.0.0 will show the host ip in the console instead of the tunnel ip. This is why i need to specify it.

The bug i have is that when i specify a adminInterface ip, the inGame menu won't work. I see you suggest setting `webServer.disableNuiSourceCheck` to `true` but this is hard to automatically to on a pterodactyl panel. Why is the inGame menu not working when using this feature?
