### ISSUE TITLE
server IP issue

### ISSUE THREAD

**Issue by Madzahttr** [citizenfx/txAdmin#67]
Any reason for not allowing anything other than 0.0.0.0 for the server IP? this makes it impossible to run multiple servers on multiple IPs.

"FXServer config error: You MUST have a TCP endpoint with interface 0.0.0.0"

**Comment by CodeMeZone** [comment]
I've been trying to find out how to do this also, on discord all they been saying is " add a new endpoint tcp with ip 127.0.0.1"

**Comment by tabarra** [comment]
You

**Comment by tabarra** [comment]
You need an endpoint listening in the loopback interface, otherwise the monitor wont be able to reach it.  
Although you can keep using your public ip `endpoint_add` commands, you will need to add a new endpoint in the localhost interface.  
As per code:  
  
```js
let validTCPEndpoint = matches.find((match) => {
    return (match.type.toLowerCase() === 'tcp' && (match.interface === '0.0.0.0' || match.interface === '127.0.0.1'))
})
if(!validTCPEndpoint) throw new Error("You MUST have a TCP endpoint with interface 0.0.0.0");
```  
  
> Note: I'm fully aware the error message doesn't tell you about this `127.0.0.1` exception, but I didn't wanted to confuse people that already have great difficulties understanding that error message.
