### ISSUE TITLE
[BUG] Teleport to a user gives me this : teleported to player [??] unknown

### ISSUE THREAD

**Issue by L4wlz** [citizenfx/txAdmin#670]
**txAdmin/FXServer versions:**
v4.17.1 atop FXServer 5837
  
**Describe the bug**
When i teleport to a person in game, it does not log who i teleported to ? 
Check screenshot

**To Reproduce**
Just teleport to a person and check your logs

**Expected behavior**
It should give me the name of that person i teleported to and  not this : **[??] unknown**

**Screenshots**
![image](https://user-images.githubusercontent.com/62191448/187268856-4923f9bd-9217-48cb-bfac-1d0466e7dcbd.png)

**Additional context**
Add any other context about the problem here, like for example if it's a server issue, which OS is fxserver hosted on.

**Comment by tabarra** [comment]
do you have onesync on?

**Comment by L4wlz** [comment]
Yes i have

**Comment by ChickenDipper1** [comment]
I have this too, is there any fix. Does it not support onesync?

Thanks.

**Comment by tabarra** [comment]
Found the issue, full blame on @TasoOneAsia 🤣 
https://github.com/tabarra/txAdmin/commit/4f87caa1a01695b738efd4b9435f8d1fe77ab520  
  
Easy enough to fix it though, will include it in the v5.0.0 release.
