### ISSUE TITLE
[FEATURE]: adjust server restart timer

### ISSUE THREAD

**Issue by Hamartenn** [citizenfx/txAdmin#671]
### Scope

Developer API

### Feature Description

Can you add a way to adjust the amount of time it takes for your server to restart before it automatically does it for you I think currently it's set at 60 seconds.

**Comment by tabarra** [comment]
I suppose you mean server boot time, right?  
This is already a thing, but may be bugged for some people.  
I'll mark this as closed because it will be solved next update in a few days.
