### ISSUE TITLE
[FEATURE]: Custom event for revoked warns

### ISSUE THREAD

**Issue by iamshoXy** [citizenfx/txAdmin#673]
### Scope

Web

### Feature Description

Since there is `txAdmin:events:playerWarned` I would like an event for revoked warnings.
For example: `txAdmin:events:revokedPlayerWarn`

### Use Case

Can be useful for logs (e.g. Discord webhooks)

**Comment by PC1up** [comment]
Well there is an [PR](https://github.com/tabarra/txAdmin/pull/612) for that one. I don't know whats up with that one but there is one 🤷

**Comment by PC1up** [comment]
(only thing is that this PR doesn't specify the type of action that has been revoked; just the actionid)

**Comment by tabarra** [comment]
I will add an `actionRevoked` in the next few weeks that will contain the type of the action being revoked.

**Comment by tabarra** [comment]
Done, the event `txAdmin:events:actionRevoked` will look like this:  
![image](https://user-images.githubusercontent.com/1808295/196197721-28ef1385-c08a-4f2e-bad4-ade26beaa983.png)
