### ISSUE TITLE
[BUG] Distance shown as ??

### ISSUE THREAD

**Issue by SneakyAF** [citizenfx/txAdmin#679]
**txAdmin/FXServer versions:**
4.17.1
  
**Describe the bug**
Distance to the player is shown as "??"

**To Reproduce**
1. Open up the TX with /tx command
2. Navigate to "Players" tab
3. Observe the distance to the player
4. See error - it is shown as "??"

**Expected behavior**
Correct number in meters shown

**Screenshots**
![image](https://user-images.githubusercontent.com/45791897/189587717-09f20161-0599-4a88-83d4-f719f622c487.png)

**Additional context**
Sometimes the issue fixes itself, not quire sure when or how. Any ideas of what is happening?.

**Comment by tabarra** [comment]
Your server is onesync infinity, that's how it works due to performance.  
Your client doesn't get info from players above 424m or something like that.

**Comment by SneakyAF** [comment]
Thank you @tabarra , that makes sense because I've just recently made it to use Infinity. Thank you for the answer!

**Comment by VIRUXE** [comment]
> Your server is onesync infinity, that's how it works due to performance. Your client doesn't get info from players above 424m or something like that.

In terms of UX, wouldn't it be better to just blank out the string?
