### ISSUE TITLE
Server restarts no longer announced

### ISSUE THREAD

**Issue by Bobertsawesome** [citizenfx/txAdmin#68]
Both of our planned restarts are no longer getting their in-game announcement before a said restart. No specific errors or anything at all. All server settings look perfectly ok, I have double verified.

**Comment by tabarra** [comment]
- txAdmin haven't updated in some time, and the last change to this part of code was a long time ago;
- cfx-server-data/chat also haven't updated in a long time;
- nobody else is complaining about this;  
  
Therefore, its probably an issue in your side.

**Comment by Bobertsawesome** [comment]
How is it triggering with the server? 

This issue has been around but on the back burner for a while, but I'm getting around to trying and figure it out now.

**Comment by tabarra** [comment]
Precisely the way it says in the FiveM Documentation.  
```lua
TriggerClientEvent("chat:addMessage", -1, {
    args = {
        "(Broadcast) "..args[1],
        args[2],
    },
    color = {255, 0, 0}
})
```
