### ISSUE TITLE
[FEATURE]: Add export to give / remove admin rights

### ISSUE THREAD

**Issue by CeebDev** [citizenfx/txAdmin#681]
### Scope

Developer API

### Feature Description

Add a export to give admin right to a user
Add a export to remove admin right to a user

### Use Case

When using multichar script :
- I want my moderator have admin right only on their admin character
- I dont want my mods use admin menu if they are with their RP character

### Proposed Solution

You can provide 2 export to add / remove temp admin with license identifier

**Comment by PC1up** [comment]
I see a pretty big security issue there. Someone could easily use lua executors to, well, execute the export and give themselves admin permissions. Doubt that this is gonna be added.

**Comment by tabarra** [comment]
This is out of scope for txAdmin.  
An admin is an admin, he's not an admin just because he's not wearing admin clothes.
