### ISSUE TITLE
[FEATURE]: player controls in web interface

### ISSUE THREAD

**Issue by Hamartenn** [citizenfx/txAdmin#682]
### Scope

Web

### Feature Description

Have the ability to freeze, kill, or troll within the web interface so you don't have to be in the city.

**Comment by tabarra** [comment]
I'm not sure about that.  
But i'll leave the PR open to see if more people have anything to say about it.

**Comment by VIRUXE** [comment]
Unless there's going to be a two-way communication channel with the person this affects I say there is no need for this.

**Comment by tabarra** [comment]
I feel like this is somewhat out of scope.
