### ISSUE TITLE
[FEATURE]: Players - Last Login

### ISSUE THREAD

**Issue by Legacy-TacticalGamingInteractive** [citizenfx/txAdmin#689]
### Scope

Web

### Feature Description

Ability to also see when someone last played on the server in the Player tab on the Web interface rather than only total time played on the server. Unless it would use too much resources?

### Use Case

Admins can see activity levels of players. Especially those in high up positions. To ensure they are active often.

**Comment by PC1up** [comment]
+1
Also useful for staff management to monitor their staffs activity

**Comment by tabarra** [comment]
Alright, will be done in the v5.0.0 update to be released in a few weeks.

**Comment by Legacy-TacticalGamingInteractive** [comment]
![image](https://user-images.githubusercontent.com/25211271/203657366-d008c9e7-73d8-4f32-95e3-34f58c663dae.png)


Is it added in yet because I don't see it here yet? @tabarra

**Comment by tabarra** [comment]
@Legacy-TacticalGamingInteractive Update not yet released. Wait a few more days.
