### ISSUE TITLE
[BUG] Playerlist does not show cl2 or players with matching licenses

### ISSUE THREAD

**Issue by st860923** [citizenfx/txAdmin#690]
**txAdmin/FXServer versions:**
v4.18.1
  
**Describe the bug**
when same player join server with 2 client (aka "cl2")

**To Reproduce**
1. connect with client A (fivem://connect/localhost:30120) [change your endpoint]
2. connect with client B (fivem://connect/localhost:30120?cl2) 
3. The player in main page playerlist only display once.

**Expected behavior**
showing 2 player with different server id and same player name.

**Screenshots**
![image](https://user-images.githubusercontent.com/68638808/192740850-c8bafc96-51f3-4f29-8035-09562a7c460b.png)
![image](https://user-images.githubusercontent.com/68638808/192740156-924a459e-e6a2-4905-80c3-88a44fe60976.png)

**useful info**
https://github.com/tabarra/txAdmin/blob/ec3946a97c42bef9ab169bbc73f15c02d8e32101/core/components/PlayerController/index.js#L617
when same player open twice with cl2, they will have same license id.
This is rare case

**Comment by tabarra** [comment]
The next update will sove this =]

**Comment by PappaNiels** [comment]
To add to this, there is something simular regarding the cl2 launch command for the ingame ui. The ingame ui will show an error when you want to get the identifiers of the second client. Keep in mind that this was tested on v4.17.1.  So if fixed blame Yorick (was in vc with me when it happened).

Error: 
![image](https://user-images.githubusercontent.com/80054446/192892478-ca2c2d88-7633-44ae-9d13-b04c1259a57f.png)

**Comment by tabarra** [comment]
Solved.  
The v5 update will be available with a fix by the end of the month.
