### ISSUE TITLE
[BUG] esx_identity menu (of legacy) dont open with txadmin actived...

### ISSUE THREAD

**Issue by JonathanDiez** [citizenfx/txAdmin#692]
**txAdmin/FXServer versions:**
v4.18.1 atop FXServer 5890
  
**Describe the bug**
The esx_identity menu does not open when txadmin is activated but I know it works because if txadmin is deactivated it opens, also when txadmin is activated it is not that nothing comes out, things come out of the identity like the characteristic blurred background, but the menu (which is what important) No.

**To Reproduce**
1. Active TXADMIN
2. Try register a new character

**Expected behavior**
Activate TXADMIN (with the .txt that is created in the folder that contains server and server-data) and at the same time be able to register with a new character without this problem.

**Additional context**
I did it 3 times and right now I can confirm that everything works on my server, the problem is when I activate TXADMIN... If I activate the normal console nothing happens but when I activate the console generated by TXADMIN the resource esx_identity is not shown, at least not the menu (since other things like the blurred background that is from esx_identity) does show them...

The only thing that occurs to me is that the txadmin menu conflicts with the identity menu...

**Comment by JonathanDiez** [comment]
Sorry for my english u-u

**Comment by tabarra** [comment]
Uhhh I think this is something you need to talk to `esx_identity` maintainers.  
Very unlikely txAdmin is doing something "wrong".

**Comment by JonathanDiez** [comment]
Maybe, although esx_identity hasn't given me problems with any other scripts, but it's probably a sub-optimal configuration on the part of the esx framework... I'll talk to them...

**Comment by JonathanDiez** [comment]
> Uhhh I think this is something you need to talk to `esx_identity` maintainers. Very unlikely txAdmin is doing something "wrong".

I've tried several esx_identity and it keeps happening, until now this has never happened to me, are you sure it's an identity bug? I'm sorry for being so sure but I'm pretty desperate trying to solve it, I'm not if I want to continue with the server without TXADMIN since it's very useful...

Just in case it helps to identify the problem (or create a solution) when I run esx_identity again (ensure esx_identity) it shows me the menu without problems.

**Comment by tabarra** [comment]
txAdmin is literally part of fxserver, if a resource is not working then it's first and foremost the resources responsibility of making sure it is compatible with txAdmin.  
  
On the other hand, if a resource owner arrives at the conclusion that there is an issue in txAdmin preventing it from working, then the resource owner is more than welcome to talk to me or open an issue here in out github.  
Also worth mentioning that I am actually in contact with the maintainer of ESX, and they haven't told me anything... so not much I can do.
