### ISSUE TITLE
[FEATURE]: Preserve god mode when leaving no-clip

### ISSUE THREAD

**Issue by VIRUXE** [citizenfx/txAdmin#699]
### Scope

In-Game Menu

### Feature Description

Preserve God-mode selection after using No-Clip.

### Use Case

Right now if you set to be in god mode, enter no clip and then leave you will be set to normal mode. There are many times were I forget about this and end up in suicide.

**Comment by tabarra** [comment]
That's because player state has 3 options that you switch between them.  
Wouldn't make more sense to just prevent fall damage right after you leave noclip?  
  
I know the feeling. You leave noclip and the fall is just a tad bit too high 🤣

**Comment by VIRUXE** [comment]
Unfortunately it's not just about the fall damage. Like yesterday for example, I teleported to someone flying a plane. Thing, exploded for no reason. Bam, dead, even though I was in godmode prior to teleporting.

**Comment by TasoOneAsia** [comment]
> Unfortunately it's not just about the fall damage. Like yesterday for example, I teleported to someone flying a plane. Thing, exploded for no reason. Bam, dead, even though I was in godmode prior to teleporting.

This is most likely caused by the teleport process inducing a ped handle change, making the invincible state invalid. It could probably be fixed by handling for the specific player mode case in the TP process.

**Comment by PC1up** [comment]
Maybe just enable godmode for noclip as well so whenever you enter noclip player mode you also receive god mode

**Comment by TasoOneAsia** [comment]
@PC1up That is the current behavior

**Comment by TasoOneAsia** [comment]
@VIRUXE I can't manage to reproduce the teleport issue you were describing. While teleporting, the player remains invincible the entire time (as returned by GetPlayerInvincible_2). Do you have *exact* steps for a reproduction?

**Comment by VIRUXE** [comment]
Hi @TasoOneAsia , not at this time, no. Maybe it's been fixed.
I haven't used txAdmin since but if I do use it again I'll be sure to report back on this.

Since you cannot reproduce this maybe it's best if I just close it.
