### ISSUE TITLE
[BUG] Fatal Error Encountered - Player List (v5 beta)

### ISSUE THREAD

**Issue by PoorLatency** [citizenfx/txAdmin#705]
**txAdmin/FXServer versions:**
v5.0.0-beta1 
FXServer 6033
  
**Describe the bug**
Searching a player(s) name via /tx returns an error.

**To Reproduce**
1. Open /tx
2. Enter a username in the search bar you want to search.
3. The error appears rather than displaying the person in the playerlist.

**Expected behavior**
The persons name should show up in the playerlist.

**Screenshots**
![Error 1](https://i.imgur.com/Y4DNFk3.png)

**Additional context**
None

**Comment by TasoOneAsia** [comment]
Oddly, I can't replicate this. How many players were on the server at the time?

**Comment by PoorLatency** [comment]
> Oddly, I can't replicate this. How many players were on the server at the time?

140/200.

**Comment by tabarra** [comment]
I am pretty sure you updated the files and restarted the server but not txAdmin itself, so the resource is on v5, but tx is still in older versions.  
Just check at the bottom of the txAdmin page and see which version it says.

**Comment by PoorLatency** [comment]
> I am pretty sure you updated the files and restarted the server but not txAdmin itself, so the resource is on v5, but tx is still in older versions. Just check at the bottom of the txAdmin page and see which version it says.

v5.0.0-beta1 atop FXServer 6033

**Comment by PoorLatency** [comment]
Example:
![Error 1](https://cdn.discordapp.com/attachments/743251133509926993/1043332717921714197/Screenshot_1093.png)
![Error 2](https://i.imgur.com/Ile6y8y.png)

Is it something todo with the conversion of my database to the latest version? If so, there anyway to send you it privately?

**Comment by tabarra** [comment]
The issue is caused when some player does not have the name parameter set.  
I've fixed the error, but still have no idea what could cause that scenario to happen.  
I just released beta 4, if this issue persist please reopen the issue!
