### ISSUE TITLE
[BUG] FXServer is not responding. (connect ECONNREFUSED 127.0.0.1:30120)

### ISSUE THREAD

**Issue by detekkted** [citizenfx/txAdmin#706]
**txAdmin/FXServer versions:**
v4.18.1 / 6039
  
**Describe the bug**
FXServer not launching through TxAdmin

**To Reproduce**
1. run the run.sh file

**Expected behavior**
FXServer should start properly like when using `cd ~/FXServer/server-data && bash ~/FXServer/server/run.sh +exec server.cfg`
command.

**Screenshots**
[https://i.imgur.com/tS6GyVO.png](https://i.imgur.com/tS6GyVO.png)

**Additional context**
Host is a Strato Linux VPS utilizing 32GB of RAM and 8 vCores@2GHz
System OS: Ubuntu 22.04 LTS

**Comment by TasoAGC** [comment]
txAdmin will not launch when passing FXServer the launch arg "+exec"

**Comment by tabarra** [comment]
This happens to be a fxserver bug instead of txAdmin.  
Please report in the fivem forums.
