### ISSUE TITLE
Custom command logging

### ISSUE THREAD

**Issue by MrIvanPlays** [citizenfx/txAdmin#71]
I have ESX server. I wanna log the /dw (darkweb) command. I've added this into my server where I register the command:

```lua
	TriggerEvent('txaLogger:CommandExecuted', raw)
```

But it gets displayed like this https://img.mrivanplays.com/vrWjo0bSVj

Help?

**Comment by tabarra** [comment]
Well, how you expected to be displayed?  
The chat log entry is for chat messages that follow the default chat event, if you want to support your custom chat, you will have to code it yourself.
