### ISSUE TITLE
[BUG] "undefined" in perma ban reject message

### ISSUE THREAD

**Issue by PC1up** [citizenfx/txAdmin#714]
**txAdmin/FXServer versions:**
txAdmin v5.0.0-beta5 | fxServer 5848
  
**Describe the bug**
If a player is permanently banned and tries to join, the ban message reads:
```
You have been permanently banned from this server.
undefined Ban Date: Nov 26, 2022, 12:33:25 PM
[...]
```
everything after the ban date reads as it's supposed to be. (-> Screenshot below)

This issue does not occur with temporary bans

**To Reproduce**
1. Ban someone permanently
2. Let them try to rejoin
3. See "undefined" infront of "Ban Date"

**Expected behavior**
It's probably not supposed to be there. As I can see from the temp ban screen txAdmin might try to display the "Your ban will expire in  ..." thing which is not possible in perma bans.

**Screenshots**
![image](https://user-images.githubusercontent.com/63553505/204086742-d1034348-2842-46f1-8be4-ae9e241287c0.png)

**Additional context**
The same issue occurs with any other language selected, as seen in this screenshot with german selected:
![image](https://user-images.githubusercontent.com/63553505/204086829-21b95bd2-d616-4c3b-838f-3ed36e4ae7ee.png)

**Comment by tabarra** [comment]
Fixed, thanks.
