### ISSUE TITLE
Sometimes FXserver isn't closed / opened properly

### ISSUE THREAD

**Issue by CruelAlpha** [citizenfx/txAdmin#72]
Hi there,
I've had a few instances where TXadmin would restart the server (or we would call a restart) and the server doesn't end up coming back up, due to not closing FXserver properly before.
Is this something that was an issue in the past or known about?

**Comment by tabarra** [comment]
Yes, there have been issues with very old fxserver builds (below 1000) and Windows Server 2012.  
But can you elaborate more on the "closing FXserver properly" part?  
  
Also, if your server is too heavy, txAdmin might start a new one before the old dies completely and the TCP port might not have been released yet.

**Comment by CruelAlpha** [comment]
Hi there,
it happened again unfortunately during a scheduled automatic restart. 
I believe it's as you explained the port isn't released and never seems to be until restarting txadmin itself.
Here are some screenshots: 

![image](https://user-images.githubusercontent.com/29218750/74200166-4a283b00-4cba-11ea-9a31-9c273fb1558e.png)
The automatic restart
![image](https://user-images.githubusercontent.com/29218750/74200180-50b6b280-4cba-11ea-96fb-abc3cb9ef6bb.png)
Something got stuck loading here
![image](https://user-images.githubusercontent.com/29218750/74200191-57ddc080-4cba-11ea-88b6-08bebc1025bf.png)
After manually restarting, everything seems fine
![image](https://user-images.githubusercontent.com/29218750/74200211-65934600-4cba-11ea-9a3e-119b6339b160.png)
However, when trying to connect it shows as default fx server
![image](https://user-images.githubusercontent.com/29218750/74200238-80fe5100-4cba-11ea-9716-355bb532ca00.png)
When looking at the logs, txadminclient resource claims the port is still in use.

Is there a way around this from happening? As it seems like it neever really releases the port, possibly waiting till the port is cleared before the restart?

**Comment by tabarra** [comment]
Perhaps your server is a bit too heavy?  
Search for the `restartServer()` method inside `src/components/fxRunner/index.js` and change `await sleep(1250);` to something like 20000, this will wait 20 seconds before starting a new server.  
  
I'm closing this Issue, but if you have any information feel free to post here or in our discord server.

**Comment by CruelAlpha** [comment]
Hey,
With the new system how would I increase the sleep?
Cheers :)

**Comment by tabarra** [comment]
Update to txAdmin v2.  
Also, I'm right now coding something to at least help diagnose the problem.
