### ISSUE TITLE
[FEATURE]: restart cancel event

### ISSUE THREAD

**Issue by BaziForYou** [citizenfx/txAdmin#723]
### Scope

Developer API

### Feature Description

we now can cancel the restart time or put custom restart time but most scripts used a restart timer for closing and saving when someone does that and then cancel that script goes into problems because there is no way to find the restart time that got canceledscripts

### Proposed Solution

You can give restarts if like a number or random string then pass that to ``txAdmin:events:scheduledRestart`` in eventData so we store now current restart id as something like id 3 so then user cancel restart another event get trigger like ``txAdmin:events:cancelScheduledRestart`` and pass canceled restart id so the script can handle to don't do closing or saving prosses

**Comment by tabarra** [comment]
Done https://github.com/tabarra/txAdmin/commit/dd87516c527bcf01f14fe5420d450f9689150771
