### ISSUE TITLE
[txAdmin Crash] txAdmin forces Restart after Java Heap Space Error

### ISSUE THREAD

**Issue by xNikolai111** [citizenfx/txAdmin#724]
**txAdmin/FXServer versions:**
v4.18.1 atop FXServer 6004
  
**Describe the bug**
After a while, the Server crashes with the error code below. The crash only appears, when more than 40+ players are online. So we have the issue just in the primetime (at evening). The node-parameter for java heap space is at 64 GByte (for my knowledge, its senseless to give Java this size for heap space). But I´m a little bit helpless. I hope, anyone has a tip.

**Log**
<--- Last few GCs --->

[75541:0x7f23da56b1a0] 14235110 ms: Scavenge 12.4 (15.0) -> 12.0 (15.0) MB, 1.2 / 0.0 ms  (average mu = 1.000, current mu = 1.000) allocation failure 
[75541:0x7f23da56b1a0] 14245988 ms: Scavenge 12.4 (15.0) -> 12.0 (15.0) MB, 0.6 / 0.0 ms  (average mu = 1.000, current mu = 1.000) allocation failure 
[75541:0x7f23da56b1a0] 14255950 ms: Scavenge 12.4 (15.0) -> 12.0 (15.0) MB, 0.8 / 0.0 ms  (average mu = 1.000, current mu = 1.000) task 

<--- JS stacktrace --->

V8 error at Committing semi space failed.: Allocation failed - JavaScript heap out of memory> txaEvent "serverShuttingDown" "{＂delay＂:5000,＂author＂:＂txAdmin＂,＂message＂:＂Server Neustart (Crash erkannt).＂}"

**Additional context**
The server is running on an up-to-date debian system. The diagnostics aren´t conspicuous. The FXServer mem is round about 15 GByte at crash.

I hope someone can help us and has a clue. 

Kind Regards :)

**Comment by tabarra** [comment]
This is not a txAdmin issue, this is a "your server" issue.  
More specifically, look for resources with `.js` files, or use svgui (if on windows) to find which resource is leaking memory.  
Furthermore, you can use discord.gg/txadmin for support.
