### ISSUE TITLE
[FEATURE]: Slash Commands for Discord Bot

### ISSUE THREAD

**Issue by TheHolyFire** [citizenfx/txAdmin#731]
### Scope

Developer API

### Feature Description

Add a way to enable slash commands on the Discord Bot for Users to see easier what commands the Bot has

### Use Case

When a User wants to see what commands a Bot has they use / to find out

**Comment by amplyy** [comment]
Hey there this is planned to happen sometime next week.

**Comment by tabarra** [comment]
Done.

**Comment by TheHolyFire** [comment]
> Done.

Nice!
When will it be available for download?
