### ISSUE TITLE
[BUG] Home Hosted server runs but spams this message over and over, cannot connect to it either.

### ISSUE THREAD

**Issue by Guymcguy420** [citizenfx/txAdmin#737]
I use the most recent version of txadmin and I run a home hosted server. This message, "[      script:monitor] [txAdminClient] HeartBeat failed with code 0 and message: nil" spams in the console whenever I run the server, and I cannot join. I have already redeployed the server files and still no fix. All ports are open and 30120 is forwarded. Any help? I already talked with Tabarra so I was looking if anyone else had a fix.
[fxserver_1672525244.log](https://github.com/tabarra/txAdmin/files/10328080/fxserver_1672525244.log)

**Comment by Guymcguy420** [comment]
[      script:monitor] [txAdminClient] HeartBeat failed with code 0 and message: nil
[      script:monitor] [txAdminClient] HeartBeat failed with code 0 and message: nil
[      script:monitor] [txAdminClient] HeartBeat failed with code 0 and message: nil
[      script:monitor] [txAdminClient] HeartBeat failed with code 0 and message: nil
[      script:monitor] [txAdminClient] HeartBeat failed with code 0 and message: nil

**Comment by tabarra** [comment]
use discord for support, this is not a txadmin issue but a lan networking issue.
