### ISSUE TITLE
[FEATURE]: Whitelist enable/disable on scheduled times

### ISSUE THREAD

**Issue by NinjaLabs-Dev** [citizenfx/txAdmin#740]
### Scope

Web

### Feature Description

Add the ability to schedule whitelist times. Allow the user to select a start & end time. A schedule would allow a server to have specified whitelist times (e.g 8pm - 4am) without requiring a staff member with permission to be awake / remember to turn the whitelist off at 4am. 

### Use Case

Our server has specific whitelist times (8pm - 4am), and the allowlist is often left on after 4am due to staff sleeping. It would be nice to have this feature to enable a system like this to work without manual input.

### Proposed Solution

Add a schedule option within settings, allowing users to select multiple start & end times for allowlist, these would be applied and removed daily at the specified time.

**Comment by tabarra** [comment]
That's an interesting request, I can see it being valuable, but:  
1. I have no idea of the interest for this feature, so I urge other server owners that need it to react to this request with 👍 or comment below if needed.
2. Sounds like the kind of thing that might require lots of customization per server, like changing server name or starting/stopping resources. In this case might be better for me to provide an API so servers can write a small resource to take care of that themselves (#442).

**Comment by tabarra** [comment]
Due to the complexity of this task and lack of demand, I've decided that the best approach would be to allow scripts to change the server whitelist mode through the API, which would solve this need without all the added complexity.  
Therefore, I refer anyone that wants this to #442.
