### ISSUE TITLE
[BUG] Since Update to 5.1.0 Warning // exec configs cant read

### ISSUE THREAD

**Issue by LimnedMoon** [citizenfx/txAdmin#741]
**txAdmin/FXServer versions:**
6212 / 5.1.0  
**Describe the bug**
After Update to txAdmin 5.1.0 i got in sever ConsoleWarning "in server.cfg is unreadable or dont exist..."
its from ox_inventory the exec here:
exec @ox_inventory/config.cfg    --> this is since update "unreadable"
ensure ox_inventory

**To Reproduce**
1. exec something in server.cfg
2. start server...
3. look result is server console

**Expected behavior**
No issues like in 5.0.1

**Additional context**
Artifacts: 6212 / even tested with 6198 and latest stable (5848)
Server: Windows
old-txAdmin version without issues: 5.0.1
is the exec config readed then / changes there? YES (easy to test eg. with iventory size...)

**Comment by Xtrea2022** [comment]
Maybe you have to wait for the new Artifacts - Version (min 6225)

**Comment by Legacy-TacticalGamingInteractive** [comment]
I think its best to wait for artifacts updates rather than doing txadmin updates separately personally thats what I do as those artifacts will come with txadmin updated automatically usually within 24-48 hours of a new txadmin update

**Comment by tabarra** [comment]
Thanks for reporting.  
I published tx v5.1.1 (artifact 6228) to solve this issue.
