### ISSUE TITLE
[BUG] Discord stats not working

### ISSUE THREAD

**Issue by SubwooferNL** [citizenfx/txAdmin#743]
**txAdmin/FXServer versions:**
v5.1.1 atop FXServer 6228 
  
**Describe the bug**
since the last update my discord statics are not working anymore.
i need to do /status add in the discord channel but it says this
https://i.imgur.com/LE2ndsI.png
and in the logs it says this
https://i.imgur.com/jagqKIS.png
what can i do ?

**Screenshots**
https://i.imgur.com/LE2ndsI.png
https://i.imgur.com/jagqKIS.png

**Comment by tabarra** [comment]
You have two bots using the same token.  
And please do not use the github issues as support, we have a discord for that.

**Comment by SubwooferNL** [comment]
i was thinking this was an issue :S sorry for letting know
