### ISSUE TITLE
Random txAdmin server crashes

### ISSUE THREAD

**Issue by TheDjRider** [citizenfx/txAdmin#75]
Hello, 
im making new server now and use txAdmin for many thinks. But every day i saw some randomly crashs detected in discord-log:

> Stats:
Uptime: 8 days, 8 hours, 1 minute
Full Crashes: 2 - From ME byged scripts
Partial Crashes: 7

And after those Partial Crashes, some of maps that are added on my server didn't laod, need to restart server to load them properly.

**Comment by tabarra** [comment]
That sounds like an fxserver issue.  
txAdmin does not restart working servers.

**Comment by TheDjRider** [comment]
So zero scripts error in console, other game server work normally server normally.
Also, the same server with beta scripts (work on them) started on screen command work without 0 crashes ...

**Comment by tabarra** [comment]
Scripts can fail silently, can get into infinite loops, mysql queries might never reply and you don't release the thread... Many things can happen.  
And again:
> txAdmin does not restart working servers.
