### ISSUE TITLE
Issue when adding server config

### ISSUE THREAD

**Issue by lze3** [citizenfx/txAdmin#76]
![](https://lambda.sx/nDA.png)

As seen in the image above, it is saying that there are no `endpoint_add_*` commands being executed inside the config, which is false. This is just because I am passing `[::]` (IPv6) and not my local IPv4 address.

**Comment by tabarra** [comment]
Yeah, we currently use an regex that doesn't support IPv6, and since I have absolutely no idea what would break with this, for now I'm just gonna keep it this way unless people start asking for IPv6 support.
```regex
/^\s*endpoint_add_(\w+)\s+["']?([0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3})\:([0-9]{1,5})["']?.*$/gim
```
