### ISSUE TITLE
[BUG] TxAdmin detect random crash

### ISSUE THREAD

**Issue by AnarchyIsTheBestWay** [citizenfx/txAdmin#764]
**txAdmin/FXServer versions:**
txAdmin in on v5.2.0(the latest) and fxServer on 6247 (the latest)
  
**Describe the bug**
Randomly TxAdmin detect a crash on the server and restart the server. The problème is that I have no crash report in /alpine/opt/cfx-server/crashes/ .

**Expected behavior**
I'dd like to know if it's possible to turn off the automatic restart when txAdmin detect a "crash". Everytime the server restart when I have a lot of player ! 

**Screenshots**
![image](https://user-images.githubusercontent.com/40702245/216609801-b257f45d-ae9e-477d-98c6-ec183d831714.png)
![image](https://user-images.githubusercontent.com/40702245/216609911-7daa7cbf-7feb-47cd-9ee3-d35f1e85f59a.png)
Here you can see that the monitor restart the server and on other you can see that the server hang.

I'd like to add this: The fivem server is running on linux (debian)

I hope you could help me !
Have a nice day =)

**Comment by tabarra** [comment]
Hey there.  
1. that was not a crash, that was a hang, which means one or more threads not working correctly anymore;
2. a "crash" is way more complicated than looking for a new file in the crashes folder;
3. txadmin knows what it is doing, you should trust it.

With that said, i recommend you join discord.gg/txadmin for support, github really isn't the right place for it.

**Comment by AnarchyIsTheBestWay** [comment]
Hi @tabarra !!
I'm already on the discord server. I have ask the exactly same question, the only things someone as done it's this:
![image](https://user-images.githubusercontent.com/40702245/216634581-950b6e73-f06c-4eff-a1f1-8e9ea9a7e9c2.png)
So, this is why i'm asking question here, because random people come and says to me things I already know ^^

Now you says that maybe a threads is not working correctly, I just say ok, but how can I know witch one ? I have no log and not threads on my server I have had by myself.

I really need helps ...

Have a good day =)
