### ISSUE TITLE
tx admin wont update i cant update tx

### ISSUE THREAD

**Issue by Tylham33** [citizenfx/txAdmin#766]
**txAdmin/FXServer versions:**
You can see that at the bottom of the txAdmin page, or in the terminal as soon as you start fxserver.  
  
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Additional context**
Add any other context about the problem here, like for example if it's a server issue, which OS is fxserver hosted on.

**Comment by tabarra** [comment]
Clearly you don't seem to be able to follow instructions very easily.  
So please come to discord.gg/txAdmin for support, this is not the correct place for this.
