### ISSUE TITLE
[BUG] cant use most recent release

### ISSUE THREAD

**Issue by Krisb239** [citizenfx/txAdmin#768]
**txAdmin/FXServer versions:**
You can see that at the bottom of the txAdmin page, or in the terminal as soon as you start fxserver.  
fx server - 5894
txadmin 5.1.1
  
**Describe the bug**
While trying to update tx admin to the most recent version i get an error that states my players data base is on v3 and the most recent version of txadmin only supports v2.

I can get rid of the error if i drop my fx server version down. 
But then i get a flag on my server in the cfx launcher saying my artifacts are out of date.
**To Reproduce**
1. fx server 5894
2. tx admin most recent release
3. youll see error.

**Comment by tabarra** [comment]
if you get that message, it means you are not updated  
  
Also this is not a tx issue, please use our discord for support instead of github
