### ISSUE TITLE
[BUG] NoClip: Game crashes with Pool Full

### ISSUE THREAD

**Issue by SeaLife** [citizenfx/txAdmin#773]
**txAdmin/FXServer versions:**
v.5.2.0 (Issue is persistent since months)
  
**Describe the bug**
So we created a basic ESX Legacy Server 1.2 with _some_ custom maps and TxAdmin to reproduce this...
What we do: Noclipping with some custom maps, like 10 minutes.. Our game crashes with this error message:

```
<<unknown pool>> Pool Full, Size == 400
```

This issue persist over all our servers (Windows and Linux) including local test servers.

If we dont noclip at all, no crash appears. If we noclip through another noclip implementation like VB-AC (our Anti Cheat) not crash occures.

**To Reproduce**
Described my steps above..
1. Install ESX and some custom maps, should be irrelevant which maps, i guess
2. No Clip around (leave/enter noclip a bunch of time)
3. get the crash hopefully

The crash is not garantueed to occure while noclipping, but as soon as you noclipped you can get the crash eventually while playing.

**Expected behavior**
No Crash

**Screenshots**
I suppose no screenshot is required, but maybe i can ask a moderator of mine to record this.

**Additional context**
Host: Linux (dedicated), Windows (local computer), Windows (qemu-vm)
FXServer: 6279 (Windows), 6228 (Linux)
Installed Resources: ESX Legacy 1.2 and some dependencies + some maps like Gabz-maps

If more information is required or game-access to our pre-live server, i can provide that if required
_[for security reasons, no file access can be provided]_

**Comment by Mycroft-Studios** [comment]
This just means there is too many Maps Loaded at once , which can happen when u noclip too fast through an area with a lot of MLOs in.

**Comment by Mycroft-Studios** [comment]
Btw , there is no "ESX Legacy 1.2" . ESX Legacy is 1.4 - 1.9.2, anything lower is just ESX 1.2 or ESX 1.1 😉

**Comment by SeaLife** [comment]
> Btw , there is no "ESX Legacy 1.2" . ESX Legacy is 1.4 - 1.9.2, anything lower is just ESX 1.2 or ESX 1.1 😉

I forked the project on its 1.2.0 version and it say's "es_extended LEGACY" - but whatever, its not important for this issue.

> This just means there is too many Maps Loaded at once , which can happen when u noclip too fast through an area with a lot of MLOs in.

Yeah, i know. But with another NoClip implementation this is not happening (we only tested the one in VB-AC so far, which worked for over half an hour noclipping)

NoClip Code from VB-AC:
```lua
Citizen.CreateThread(function()
    Citizen.Wait(2500)
    TriggerServerEvent('SBmQ5ucMg4WGbpPHoSTl')
    Citizen.Wait(7500)
    while VB_AC.IsAdmin do
        Citizen.Wait(0)
        if isusingfuncs then
            if isnoclipping then
                local _ped = PlayerPedId()
                local _pcoords = GetEntityCoords(_ped)
                local _x = _pcoords.x
                local _y = _pcoords.y
                local _z = _pcoords.z
                local heading = GetGameplayCamRelativeHeading()+GetEntityHeading(PlayerPedId())
                local pitch = GetGameplayCamRelativePitch()
                local x = -math.sin(heading*math.pi/180.0)
                local y = math.cos(heading*math.pi/180.0)
                local z = math.sin(pitch*math.pi/180.0)
                local len = math.sqrt(x*x+y*y+z*z)
                if len ~= 0 then
                  x = x/len
                  y = y/len
                  z = z/len
                end
                local _camx = x
                local _camy = y
                local _camz = z
                if IsControlPressed(0, 32) then
                    _x = _x + noclipspeed * _camx
                    _y = _y + noclipspeed * _camy
                    _z = _z + noclipspeed * _camz
                elseif IsControlPressed(0, 33) then
                    _x = _x - noclipspeed * _camx
                    _y = _y - noclipspeed * _camy
                    _z = _z - noclipspeed * _camz
                end
                SetEntityVisible(_ped, false)
                SetEntityVelocity(_ped, 0.05,  0.05,  0.05)
                SetEntityCoordsNoOffset(_ped, _x, _y, _z, true, true, true) 
            end
            if isnoclippingveh then
                local _ped = GetVehiclePedIsIn(PlayerPedId(), false)
                local _pcoords = GetEntityCoords(_ped)
                local _x = _pcoords.x
                local _y = _pcoords.y
                local _z = _pcoords.z
                local heading = GetGameplayCamRelativeHeading()+GetEntityHeading(PlayerPedId())
                local pitch = GetGameplayCamRelativePitch()
                local x = -math.sin(heading*math.pi/180.0)
                local y = math.cos(heading*math.pi/180.0)
                local z = math.sin(pitch*math.pi/180.0)
                local len = math.sqrt(x*x+y*y+z*z)
                if len ~= 0 then
                  x = x/len
                  y = y/len
                  z = z/len
                end
                local _camx = x
                local _camy = y
                local _camz = z
                if IsControlPressed(0, 32) then
                    _x = _x + noclipveh * _camx
                    _y = _y + noclipveh * _camy
                    _z = _z + noclipveh * _camz
                elseif IsControlPressed(0, 33) then
                    _x = _x - noclipveh * _camx
                    _y = _y - noclipveh * _camy
                    _z = _z - noclipveh * _camz
                end
                SetEntityVisible(_ped, false)
                SetEntityVelocity(_ped, 0.05,  0.05,  0.05)
                SetEntityCoordsNoOffset(_ped, _x, _y, _z, true, true, true) 
            end
        end
    end
end)
```

**Comment by tabarra** [comment]
There is nothing i can do about it... vmenu's noclip also crashes.

**Comment by tabarra** [comment]
ps: I have asked the FiveM devs about it twice, and no solution.

**Comment by SeaLife** [comment]
Okay, thank you :)
