### ISSUE TITLE
[FEATURE]: Skip Scheduled Restart

### ISSUE THREAD

**Issue by Legacy-TacticalGamingInteractive** [citizenfx/txAdmin#774]
### Scope

Web

### Feature Description

Skip Upcoming Scheduled Restart button

### Use Case

Would be great as often times I will just skip a restart if its not needed at the time. But to do so I have to remove the times I entered then add them back afterwards. Would be cool to be able to Skip the next automatic restart.

### Proposed Solution

Add Skip Next Restart button

**Comment by tabarra** [comment]
Uhhh was this post written in 2021???  
This has been a feature for probably a year already.

**Comment by Legacy-TacticalGamingInteractive** [comment]
???

Where?
![image](https://user-images.githubusercontent.com/25211271/221367528-a2fbd5b0-7421-4646-bfa9-d6f07749f7a6.png)

**Comment by tabarra** [comment]
literally on the dashboard
