### ISSUE TITLE
[BUG] Duplicate options for scheduled restart warnings

### ISSUE THREAD

**Issue by DamonOnYT** [citizenfx/txAdmin#784]
**txAdmin/FXServer versions:**
TxAdmin v5.2.0 FX 6288 
  
**Describe the bug**
There are 2 hide scheduled restart buttons, the one in Restarter does not work and re-triggers the announcement

**To Reproduce**
1. Go to Restarter
2. Enable the button 

1. Go to Game
2. Enable Hide Scheduled Restart Warnimng

**Expected behavior**
Either both buttons work and sync, or one of the buttons are removed

**Screenshots**
![image](https://user-images.githubusercontent.com/20586245/226150512-5ab856c8-d3df-4a3a-84bc-9ba44cd6211c.png)
![image](https://user-images.githubusercontent.com/20586245/226150516-1d1abebf-aa94-4ba1-988e-1debb2f13539.png)

**Additional context**
N/A

**Comment by tabarra** [comment]
Ohh this have been solved on the dev branch already :)  
The one from the restarter page is a dud, not connected to any setting so it just doesn't save.  
I'll close this issue already, even without pushing the fix to prod just yet.
