### ISSUE TITLE
[BUG][txAdmin] Checking banlist/whitelist failed with invalid response: nil

### ISSUE THREAD

**Issue by alexsdevio** [citizenfx/txAdmin#786]
**txAdmin/FXServer versions:**
6284
  
**Describe the bug**
[      script:monitor] [txAdminClient] 
[      script:monitor] [txAdmin] Checking banlist/whitelist failed with code 408 and message: nil
[      script:monitor] [txAdminClient] 
[      script:monitor] [txAdmin] Checking banlist/whitelist failed with invalid response: nil
[      script:monitor] SCRIPT ERROR: @monitor/resource/sv_main.lua:355: attempt to index a nil value (local 'respObj')
[      script:monitor] > userCallback (@monitor/resource/sv_main.lua:355)
[      script:monitor] [txAdminClient] 
[      script:monitor] [txAdmin] Checking banlist/whitelist failed with code 408 and message: nil
[      script:monitor] [txAdminClient] 
[      script:monitor] [txAdmin] Checking banlist/whitelist failed with invalid response: nil
[      script:monitor] SCRIPT ERROR: @monitor/resource/sv_main.lua:355: attempt to index a nil value (local 'respObj')

**To Reproduce**
Server Restart,, many players can connect, many others not.
They have the connection screen.. seeing "checking banlist 0/10 1/10 ...... and after 10/10 "failed checking ban/whitelist"

**Expected behavior**

**Screenshots**
https://imgur.com/BRF200A.png

**Comment by tabarra** [comment]
Support provided for this user on discord.
