### ISSUE TITLE
[BUG] Disable Announcements not working

### ISSUE THREAD

**Issue by FelipePassig** [citizenfx/txAdmin#787]
**txAdmin/FXServer versions:**
v5.2.0
  
**Describe the bug**
even leaving the Disable Announcements option turned on, it does not save and continues sending messages on discord

**To Reproduce**
1. Go to 'Settings'
2. Click on 'Restarter'
3. Click on 'Disable Announcements'

**Comment by tabarra** [comment]
Duplicate of #784
