### ISSUE TITLE
Committing semi space failed. Allocation failed - JavaScript heap out of memory

### ISSUE THREAD

**Issue by CodeMeZone** [citizenfx/txAdmin#79]
Windows server 2019
64GB of ram

https://i.imgur.com/OrfZOle.png

Seems like it's an issue with steam-snitch, would you know any fixes for this?

**Comment by tabarra** [comment]
Probably not an issue with stream snitch per se, but actually with some memory leak somewhere and something in stream snitch was just the last drop.
