### ISSUE TITLE
[FEATURE]: Staff Menu like EasyAdmin

### ISSUE THREAD

**Issue by Willow-6855** [citizenfx/txAdmin#791]
### Scope

Web, In-Game Menu, Developer API

### Feature Description

Some form of staff system using discord roles like EasyAdmin/Discord Ace Perms, just built into txAdmin so servers can have less resources.

### Use Case

Being able to have a staff menu but not have to install and configure multiple scripts to set it all up.

### Proposed Solution

A staff menu that intergrates into the txAdmin discord bot and ingame txAdmin menu.

**Comment by tabarra** [comment]
Uhh... we have one

**Comment by tabarra** [comment]
type /tx in game to open it
