### ISSUE TITLE
[BUG] Wrong timezone and times differ between FXServer and txAdmin

### ISSUE THREAD

**Issue by jfastnacht** [citizenfx/txAdmin#794]
**txAdmin/FXServer versions:**
v5.2.0 atop FXServer 6364

**Describe the bug**
Since the upgrade of FXServer to 6364 (from 6288) we have some weird issues with timezones. We use the official Linux builds from https://runtime.fivem.net/artifacts/fivem/build_proot_linux/master/

The server is set to `Europe/Berlin`, `date` hands me the correct time as CEST (UTC+2) on the terminal.

We first noticed when the Restarter was showing the wrong restart time on the Dashboard. The restarter is set to `18:00`, below the schedules it says:

```
Server's timezone: CET
Your timezone: Europe/Berlin
```

It should be CEST in the first place, like I mentioned before, `date` hands me the correct time. But according to the Dashboard the server will restart at 20:00 CEST.

Some other findings for 16:26 CEST:
- Server Log shows 16:26
- System Logs show 14:26
- ingame clock shows 16:26

**To Reproduce**
(0. Use the Linux build from https://runtime.fivem.net/artifacts/fivem/build_proot_linux/master/ with https://github.com/spritsail/fivem)
1. Set your timezone to CEST.
2. Set your Restarter to 18:00.
3. Open up the Dashboard and see if it schedules the restart to the time specified.

**Expected behavior**
The configured timezone of the server should be considered.

**Screenshots**
Scheduler configuration, Dashboard and system time:
![image](https://user-images.githubusercontent.com/6183607/229360114-28c3aa42-84b5-4c9c-875a-dcb2dfb35a28.png)
![image](https://user-images.githubusercontent.com/6183607/229360124-80b94431-cb10-474b-91be-19320792bf08.png)
![image](https://user-images.githubusercontent.com/6183607/229360137-40180d40-d27b-4909-aaba-1f003a599840.png)

Ingame Clock at 16:26 CEST:
![image](https://user-images.githubusercontent.com/6183607/229360080-8844dda3-80d4-4d6c-a313-753e6ac2658c.png)

**Additional context**

* We had the time change in Germany a week ago, but haven't restarted the stack until yesterday during the update.
* We use Docker with `/etc/localtime` mounted into the container to make sure that all of our systems use the same timezone.

**Comment by tabarra** [comment]
After changing the host's timezone, you need to fully restart txAdmin so node can get the timezone from the host again.  
This is fully handled by fxserver's node instance and txAdmin has no control over it.

**Comment by jfastnacht** [comment]
What do you mean by "fully restart"? We throw away the container and start a new one with a freshly build image of the new version, so except for the mounted configuration it is like starting txAdmin on a new OS.

**Comment by jfastnacht** [comment]
We mount `/etc/localtime`, `/config` and `/txData` into the new container, that's the only thing left from the old instance of txAdmin.

**Comment by tabarra** [comment]
I don't know what to tell you except that this is fully handled by fxserver's node instance and txAdmin has no control over it.

**Comment by Mycroft-Studios** [comment]
In game clocks have nothing Todo with host time, Client time is completely different to server time

**Comment by jfastnacht** [comment]
> In game clocks have nothing Todo with host time, Client time is completely different to server time

Alright, thanks for the clarification. The information was provided to me, I'm doing mostly operations and I'm not deeply involved in the details of client and server behaviour.

I have checked "Server Log" as well and it seems that the socket is responding with timestamps and the conversion to CEST is done client-side. Although it may not be a bug of txAdmin, it still manifests itself in the txAdmin interface and causes confusion.

If this is not considered a bug in txAdmin, you can close this issue.

Thanks so far!
