### ISSUE TITLE
[FEATURE]: Event Handler Whitelisted Check

### ISSUE THREAD

**Issue by BadCodesGG** [citizenfx/txAdmin#797]
### Scope

Developer API

### Feature Description

I'd like to see an event handler that sends data of whether the player connecting is whitelisted or not. The dataset would feature a boolean value of the whitelist, player name and identifier.

### Use Case

Something along the lines of `txAdmin:events:isPlayerWhitelisted` which we'll be able to fetch that value in our resources (like a queue resource). This would be a huge QoL which could allow folks do different things upon the connecting of a player.

### Proposed Solution

In the `sv_main.lua` file under the `./resource` directory, after the HTTP request is finished, send the data through the event handler.

**Comment by tabarra** [comment]
This doesn't make any sense though.  
What is the specific use case you have in mind? Dropping the player out of the connecting queue?  
Because tx drops the player if he fails the whitelist validation (or ban checking).

**Comment by tabarra** [comment]
I'll close this, but feel free to add explanations if needed.
