### ISSUE TITLE
Crashing when restarting server

### ISSUE THREAD

**Issue by mirrox1337** [citizenfx/txAdmin#8]
Everytime I restart the server or autorestart

**Crash Log**
0 info it worked if it ends with ok
1 verbose cli [ 'C:\\Program Files\\nodejs\\node.exe',
1 verbose cli   'C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'start',
1 verbose cli   'server.json' ]
2 info using npm@6.9.0
3 info using node@v10.16.0
4 verbose run-script [ 'prestart', 'start', 'poststart' ]
5 info lifecycle fivem-fxadmin@0.9.5~prestart: fivem-fxadmin@0.9.5
6 info lifecycle fivem-fxadmin@0.9.5~start: fivem-fxadmin@0.9.5
7 verbose lifecycle fivem-fxadmin@0.9.5~start: unsafe-perm in lifecycle true
8 verbose lifecycle fivem-fxadmin@0.9.5~start: PATH: C:\Program Files\nodejs\node_modules\npm\node_modules\npm-lifecycle\node-gyp-bin;C:\fivem-fxadmin\node_modules\.bin;C:\Program Files (x86)\Common Files\Oracle\Java\javapath;C:\Windows\system32;C:\Windows;C:\Windows\System32\Wbem;C:\Windows\System32\WindowsPowerShell\v1.0\;C:\Program Files\nodejs\;;C:\Users\killer\AppData\Local\Programs\Microsoft VS Code\bin;C:\Users\killer\AppData\Roaming\npm
9 verbose lifecycle fivem-fxadmin@0.9.5~start: CWD: C:\fivem-fxadmin
10 silly lifecycle fivem-fxadmin@0.9.5~start: Args: [ '/d /s /c', 'node src/main.js "server.json"' ]
11 silly lifecycle fivem-fxadmin@0.9.5~start: Returned: code: 1  signal: null
12 info lifecycle fivem-fxadmin@0.9.5~start: Failed to exec start script
13 verbose stack Error: fivem-fxadmin@0.9.5 start: `node src/main.js "server.json"`
13 verbose stack Exit status 1
13 verbose stack     at EventEmitter.<anonymous> (C:\Program Files\nodejs\node_modules\npm\node_modules\npm-lifecycle\index.js:301:16)
13 verbose stack     at EventEmitter.emit (events.js:198:13)
13 verbose stack     at ChildProcess.<anonymous> (C:\Program Files\nodejs\node_modules\npm\node_modules\npm-lifecycle\lib\spawn.js:55:14)
13 verbose stack     at ChildProcess.emit (events.js:198:13)
13 verbose stack     at maybeClose (internal/child_process.js:982:16)
13 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:259:5)
14 verbose pkgid fivem-fxadmin@0.9.5
15 verbose cwd C:\fivem-fxadmin
16 verbose Windows_NT 6.1.7601
17 verbose argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "start" "server.json"
18 verbose node v10.16.0
19 verbose npm  v6.9.0
20 error code ELIFECYCLE
21 error errno 1
22 error fivem-fxadmin@0.9.5 start: `node src/main.js "server.json"`
22 error Exit status 1
23 error Failed at the fivem-fxadmin@0.9.5 start script.
23 error This is probably not a problem with npm. There is likely additional logging output above.
24 verbose exit [ 1, true ]

**Comment by tabarra** [comment]
Fixed on fa132338d6198134cca451d27b4ee79f78fff670.  
You can checkout the dev branch, or just await for the update to be pushed.  
Should do it in the next few hours.
