### ISSUE TITLE
[FEATURE]: Add a warn to disconnect people

### ISSUE THREAD

**Issue by userzfr** [citizenfx/txAdmin#802]
### Scope

Web, In-Game Menu

### Feature Description

Be able to put a warning to players who are disconnected

### Use Case

It would be good if we could add a warn to people disconnecting from the server because at the moment if I want to put a warn to a person and that the one who disconnects his sanction will not be given to him the only solution that remains to me is ban

### Proposed Solution

To be able to do like the baths added when the person is disconnected

**Comment by tabarra** [comment]
Noted, but duplicated of #522
