### ISSUE TITLE
[BUG] Cannot Cancel Restarts

### ISSUE THREAD

**Issue by CronusWaxxed** [citizenfx/txAdmin#803]
Currently not able to cancel restarts. When I hit cancel, it just proceeds to restart the server at the time it was supposed to restart instead of cancelling it.

**Comment by tabarra** [comment]
Please use the new issue default format, or seek our discord for support.

**Comment by CronusWaxxed** [comment]
I have typed in support general but I was timed out for @ you.

**Comment by CronusWaxxed** [comment]
txAdmin/FXServer versions: v5.2.0 atop FXServer 6386
  
Describe the bug:
Currently not able to cancel restarts. When I hit cancel, it just proceeds to restart the server at the time it was supposed to restart instead of cancelling it.

**To Reproduce**
Steps to reproduce the behavior:
1. Status Info
2. Click on 'Cancel' next o your restart time
3. No error, the server just restarts at the time scheduled anyways and does not cancel

Expected behavior:
The server should not restart when the restart has been cancelled

Screenshots: None

Additional context:
Need this resolved as soon as possible
