### ISSUE TITLE
[FEATURE]: Sync Discord Role to Admin Permissions

### ISSUE THREAD

**Issue by robert4049** [citizenfx/txAdmin#808]
### Scope

Web, In-Game Menu

### Feature Description

1.) Create Permission Groups
2.) Allow Permission for Group Mapping to Discord Roles
3.) Now admins are automatically given permissions 

### Use Case

Way easier management of admins and permissions

### Proposed Solution

Use existing whitelist abilities and apply that to this use case

**Comment by tabarra** [comment]
Thanks for the suggestion, but it's not gonna happen.  
txAdmin itself must be the single source of truth of all permissions.
