### ISSUE TITLE
Trend Hitch Time in graph over time.

### ISSUE THREAD

**Issue by Sudowojo** [citizenfx/txAdmin#81]
This would be extremely useful to be able to trend the hitch time in a graph over time.

**Comment by jooaooalmeida** [comment]
u can fork it and make the function yourself then open a pull request, or suggest it on discord tabarra might see it faster :p https://discord.gg/AR3CgB3

**Comment by tabarra** [comment]
Hitch is not that good as a measurement.  
Using the performance endpoint (`http://localhost:30120/perf/`) data would be way waaay better, but its complicated to do the bucketed histogram for it, so I don't know if I will ever do this.

**Comment by tabarra** [comment]
Actually, I'm creating a new issue for this.  
Thanks for the suggestion @awojnarek.
