### ISSUE TITLE
Server Restart,, many players can connect, many others not. They have the connection screen.. seeing "checking banlist 0/10 1/10 ...... and after 10/10 "failed checking ban/whitelist"

### ISSUE THREAD

**Issue by WoodaGalore** [citizenfx/txAdmin#817]
![2023-05-15](https://github.com/tabarra/txAdmin/assets/133717188/52f81b52-1818-4acd-a0ec-8a0900327d3e)
**txAdmin/FXServer versions:**
You can see that at the bottom of the txAdmin page, or in the terminal as soon as you start fxserver.  
  
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Additional context**
Add any other context about the problem here, like for example if it's a server issue, which OS is fxserver hosted on.

**Comment by tabarra** [comment]
please use discord for support  .
you didn't fill in the required issue template.  
the screenshot errors don't match the issue title.
