### ISSUE TITLE
[BUG] Inconsistent sessions, security

### ISSUE THREAD

**Issue by Spykespy** [citizenfx/txAdmin#823]
**txAdmin/FXServer versions:**
v6.0.0

Docker image on Ubuntu 22.04
  
**Describe the bug**
This is the situation we're experiencing. Person A is logged in on his account. A person B logs in from his account on a different computer. When person A refreshes his browser, he is suddenly logged in to the account of person B.

![wQF80Nes.gif](https://github.com/tabarra/txAdmin/assets/40208312/2866b0a2-d4fc-43c7-b0e6-5dc25b6b56a1)

This is an example of the bug. I'm logging in from my computer, and my colleague is just recording his screen and pressing F5.

**To Reproduce**
1. Go to the home page as a logged in user 
2. Have someone else log in from a different computer with a different account
3. Press ctrl+f5

**Comment by tabarra** [comment]
I tested and could not reproduce this issue.  
Please go to `txAdmin > Diagnostics Page > Diagnostics Report > Send Data` and click on the button to send the report, then post here the **REPORT ID**.  
And for more immediate help, maybe join discord.gg/txAdmin and ping me.

**Comment by tabarra** [comment]
Are you using any sort of proxy in front of txAdmin? That might be a proxy cache issue.

**Comment by tabarra** [comment]
Evidence of my test:

https://github.com/tabarra/txAdmin/assets/1808295/75dde437-e471-4ed4-99e2-af271b3cb312

**Comment by Spykespy** [comment]
I am running an nginx proxy, yes. It's a simple reverse web proxy with only asset caching enabled. I turned it off just to be sure, but this makes no difference. My report ID is HXE8BZ. If you'd like to ask more frequent questions, I can contact you in discord like you asked.

**Comment by tabarra** [comment]
Yeah better ping me on discord, because i don't see a reason why would this be a txadmin issue, and if only happens when it goes through your proxy that means it is probably an issue with your proxy.  
Also the report ID expired already, i need to check it as soon as it is sent.

**Comment by tabarra** [comment]
Since nobody else reported anything, and no new info came about this (github or discord), i'll close this issue as unconfirmed/stale.
