### ISSUE TITLE
[PLAYER ID NUM, AND NAME ABOVE HEAD] 

### ISSUE THREAD

**Issue by baylordevelopments** [citizenfx/txAdmin#824]
**txAdmin/FXServer versions:**
6.0.0
  
**Describe the bug**
i cant get rid of the names above players heads. any idea?

**To Reproduce**
everyone can see each others, cfx names, and it appears to be the style of TX names

**Expected behavior**
no names above head, while in server

**Screenshots**
https://cdn.discordapp.com/attachments/589106731376836608/1109999444600049775/image.png

**Additional context**
wondering if ive done something wrong and need to fix this issue, fast reaching out for help.

**Comment by tabarra** [comment]
These gamer tags are actually GTA Multiplayer Game Tags, so many resources can activate it.  
Since this doesn't have the health bar at the bottom, it confirms that it was not enabled by txAdmin.  
Please look around your resources for `SetMpGamerTagVisibility`.

**Comment by Mycroft-Studios** [comment]
note this is likely `playernames`, a Cfx default resource
