### ISSUE TITLE
[BUG] server thread hitch warning after update. [FIXED]

### ISSUE THREAD

**Issue by titoroki** [citizenfx/txAdmin#825]
Fixed after renaming the main server folder, installing tx admin again and moving my resources, my server .cfg and my logo to the new folder with se same name as the old.

**txAdmin/FXServer versions:**
New v6.0.0 atop FXServer 6461 update
**Describe the bug**
All was running perfect before updating the txAdmin to the new version, from the sudden I have this message spammed into the console:

[ citizen-server-impl] server thread hitch warning: timer interval of XXX milliseconds

**It really doesn't appear to affect the gameplay but looks like a red flag on the long time.**

**To Reproduce**

Start the server, none players are required for this to happen.

**Expected behavior**

This not showing up as the server is not on an high load.

**Screenshots**
From the profiler:

![image](https://github.com/tabarra/txAdmin/assets/46075676/399d39c0-1da0-41d5-8296-b9e1d9bbf763)

![image](https://github.com/tabarra/txAdmin/assets/46075676/1e569d12-973b-4c1d-93d3-bfe2ff3e2cb3)

**Additional context**

Hosted on my own workstation with a Xeon W3565 4Cores 8Threats @ 3.20GHz, 32GB DDR3 @ 1600 MHz

**Comment by tabarra** [comment]
well ifs its fixed then its fixed /shrug
