### ISSUE TITLE
[FEATURE]: Add the ability to also kill a player

### ISSUE THREAD

**Issue by fekydev** [citizenfx/txAdmin#829]
### Scope

In-Game Menu

### Feature Description

Having the option to kill a player, since there is already a heal option, would definitely be useful.

### Use Case

If we revive someone by mistake and other various situations (I hope I don't need to describe it more)

### Proposed Solution

Add the option to kill a player to Players in the in-game menu.
+ logs

**Comment by tabarra** [comment]
Thanks for the suggestion, but tx already covers this use case.  
Just use the troll options to set the player on fire... that's like killing but with style.
