### ISSUE TITLE
[FEATURE]: Add Kick into history of sanctions

### ISSUE THREAD

**Issue by Ninatasia** [citizenfx/txAdmin#831]
### Scope

Web, In-Game Menu

### Feature Description

Just like Warns and ban, it would be nice to have access to the list of kicks in a player's penalty history on the panel.

### Additional Info

It would go something like this:
![image](https://github.com/tabarra/txAdmin/assets/38760819/5e36286e-eafc-4ce8-8ef6-927642fe3b2b)

**Comment by tabarra** [comment]
Thanks for the suggestion, but i do not believe kicks should be used as punishment, as it is easy to confuse it from an actual administrative kick due to some bug, timeout or whatever.  
Please use warns and temporary bans for punishment.
