### ISSUE TITLE
[BUG] Player ID Distance convar is not working

### ISSUE THREAD

**Issue by morisftp** [citizenfx/txAdmin#832]
**txAdmin/FXServer versions:**
v6.0.0 atop FXServer 6457
  
**Describe the bug**
The txadmin convar to override the player-id distance is not working like it should

**To Reproduce**
1. Go to the txadmin website
2. Enter "+setr txAdmin-menuPlayerIdDistance 1000" in the start options or in the server.cfg
3. Go InGame
4. Enable Nametags and see that its not going to render nametags above 50 metres

**Expected behavior**
Normally the nametags should be able to render about like 300 metres, its limited cause of onesync
But somehow cheaters in fivem are still able to render players above 300 metres.
Another reason is, why i know this is working, another server i played on had this feature with like 1000 metres.

**Screenshots**
Cant do any screenshots, could do a video if u want

**Additional context**
Win10 Server, newest version, no updates available

**Comment by iSentrie** [comment]
why +?

**Comment by Mycroft-Studios** [comment]
>  like 300 metres,

424 in game units :)

**Comment by Mycroft-Studios** [comment]
and culling natives are now depreciated due to their unpredictable and experimental behaviour, so the client wouldn't be able to go above that anyway

**Comment by tabarra** [comment]
Issue confirmed, but its unrelated to player culling.  
Apparently the game itself hides tags above 180m, so looking at the docs i found the `SetMpGamerTagsVisibleDistance()` native... the issue is that even when setting it to 500.0 it apparently still hides the IDs above 225m.  
  
IDK what else can be done about it.

**Comment by morisftp** [comment]
As i said, i played on a server and they had it to like 1000m, you could literally see all the hundreds of players on the server

**Comment by morisftp** [comment]
> why +?

What do you mean with "why +"? Do you mean the convar?

**Comment by tabarra** [comment]
> i played on a server and they had it to like 1000m

Did the server use the gta multiplayer gamer tag?  
And please ignore the noise on the thread, focus on me lol

**Comment by morisftp** [comment]
Yes, the same as txadmin. A friend told me right now the server owner was using a own nametag script, but it looked like txadmin so its the same function

**Comment by tabarra** [comment]
Well, i don't know what the solution might be.  
I guess I'll leave this thread open for a while to see if someone has an idea, but if not i'll just close it and add to the docs that ~180m is the max distance.

**Comment by morisftp** [comment]
How can i use the native? Just use it SetMpGamerTagsVisibleDistance(1000) like this?

**Comment by morisftp** [comment]
btw, it would be a nice feature if you could add a "eye" beside the nametags if someone has nametags enabled. So other admins can see if someone is abusing their rights

**Comment by morisftp** [comment]
or maybe even a indicator which ingame rank someone has, like colorbased icons if someone is the server owner or admin, or just a supporter

**Comment by Mycroft-Studios** [comment]
> or maybe even a indicator which ingame rank someone has, like colorbased icons if someone is the server owner or admin, or just a supporter

Thats sadly not possible.
you would only be able to check if the player has access to all commands (general admin perms)

**Comment by morisftp** [comment]
> > or maybe even a indicator which ingame rank someone has, like colorbased icons if someone is the server owner or admin, or just a supporter
> 
> Thats sadly not possible. you would only be able to check if the player has access to all commands (general admin perms)

you're sure? i mean txadmin can check the discord roles

**Comment by Mycroft-Studios** [comment]
> > > or maybe even a indicator which ingame rank someone has, like colorbased icons if someone is the server owner or admin, or just a supporter
> > 
> > 
> > Thats sadly not possible. you would only be able to check if the player has access to all commands (general admin perms)
> 
> you're sure? i mean txadmin can check the discord roles

okay? by default Ace perms are not discord based, and probably shouldnt be tbh

**Comment by tabarra** [comment]
Uhhhhhhh guys can we please keep this GH issue on topic?  
Discord is a better place for discussions like this.

**Comment by tabarra** [comment]
> I guess I'll leave this thread open for a while to see if someone has an idea

As that didn't happen, I'll close this as "unfixable".
