### ISSUE TITLE
have a setting to change to https with txadmin as well as http.

### ISSUE THREAD

**Issue by Adrianmcmastergaming** [citizenfx/txAdmin#838]
### Scope

Web

### Feature Description

Would it be possible to have a setting within the txadmin console so we can use https or be able to link it to a website like I have one with https but cannot use it like we used to be able to with fivem instead of giving folks our public ip address. FiveM stopped this some time ago. I have a website with exact same name as the server but with .com and it has https with cloudflare so not sure if you will have this in the near future. The reason I ask this is a few browsers like google chrome are starting to become more secure and when I website is http you get a warning and sometimes cannot procced. I have had this happen once with txadmin. I looked the the txadmin script to see if I could see the web address were it sets localhost with http but could not find it.

**Comment by morisftp** [comment]
Yes i would like to see  that too

**Comment by tabarra** [comment]
Thanks for your suggestion.  
txAdmin used to support HTTPS but i decided to remove it, as handling TSL cannot be txadmin's responsibility.  
You need to set up a reverse proxy to do that, it's easy to do and can be done in multiple different ways.  
  
Furthermore, "linking txadmin to a website" doesn't exist.  
txAdmin accepts any connection no matter the which `Host` is set on the HTTP header, or from which interface the connection comes from (by default).  
If you want to "link to a website" you actually need to configure "the website" (domain, actually) to point to txAdmin.
