### ISSUE TITLE
[QUESTION]: Ban Hardware IDs

### ISSUE THREAD

**Issue by mouhavlad** [citizenfx/txAdmin#839]
### Scope

Web, Developer API

### Feature Description

Hello Can you explain to me how works the ban hardware IDs in the txadmin , I encountered a problem when I banned a player , 
a second player was banned with the hardware IDs,  when I checked I found 05 hardware lines that look alike for the 02 players , 
can you explain to me why because please , the second day tells me that he does not know the first banned player.
Thank you in advance for your answer

**Comment by tabarra** [comment]
So does he have 5 matching HWIDs to a banned player?  
I'm sorry, but i'm confident he is lying to you.  
  
https://en.wikipedia.org/wiki/Device_fingerprint
