### ISSUE TITLE
[BUG] type here a short description

### ISSUE THREAD

**Issue by mathexresources** [citizenfx/txAdmin#840]
**txAdmin/FXServer versions:**
txAdmin 6.0.0, FXServer 6519, 6520
  
**Describe the bug**
Noclip not keeping me in air, i keep hiting ground, taking fall damage and eventualy dying, also players can hear me falling so spectating big RP action with it is kinda imposible

**To Reproduce**
go to fivem
turn on noclip
fly on low or medium height above ground

**Expected behavior**
i expect the noclip to be fixed and not take fall damage

**Comment by tabarra** [comment]
You have another resource unfreezing the entity.  
This is not a tx issue.
