### ISSUE TITLE
[FEATURE]: Notification on server finished running

### ISSUE THREAD

**Issue by userzfr** [citizenfx/txAdmin#841]
### Scope

Web

### Feature Description

When the server has finished running make a sound on the browser as a notification.

**Comment by tabarra** [comment]
This is _technically_ easy to do, but I predict that a massive number of users would hate it, which means I would need to add some way to enable/disable it, which means i would have to do some UI work and a way to store that (cookies?!).  
Although I totally could see myself enjoying this feature, i think that's a no go for this request, unless a significant number of people ask for it.  
Thanks for the suggestion though :)
