### ISSUE TITLE
[FEATURE]: remove specific identifier from player bans

### ISSUE THREAD

**Issue by iSentrie** [citizenfx/txAdmin#842]
### Scope

Web, In-Game Menu

### Feature Description

Common issue, when players have been shared an account between each other (steam, rockstar, discord...), it adds up to "Previously Used Identifiers", which can lead to one specific player being banned and that transferred to whole chain of players involved in sharing accounts.

### Use Case

The basic idea is to create feature to remove specific identifiers **from applied ban data**.

**Comment by tabarra** [comment]
Sharing accounts is sketchy at best.  
If you want, you can revoke the ban and then apply just to the licenses you want through the identifier ban option in the players page.

**Comment by Mycroft-Studios** [comment]
Note that "account sharing" is usually how people get new license identifiers to ban evade. And these people often have 1000s of identifiers linked together

**Comment by iSentrie** [comment]
> Sharing accounts is sketchy at best. If you want, you can revoke the ban and then apply just to the licenses you want through the identifier ban option in the players page.

It's sketchy, but would be useful to have option to easily remove from specific ban - specific identifiers.
Revoking ban and reapplying ban would be even less secure, there is no token option.

**Comment by tabarra** [comment]
I don't like the idea of editing bans, at least not ban identifiers.  
I'm much more inclined in adding an option to delete players from the database, or maybe just wipe their identifiers (except license).  
But that is still a no go for this feature request, as there is the workaround that i just explained.
