### ISSUE TITLE
[BUG] txAdmin ingame menu and vRP2 side-by-side

### ISSUE THREAD

**Issue by nc-jeni** [citizenfx/txAdmin#844]
**txAdmin/FXServer versions:**
All
  
**Describe the bug**
Unable to install txAdmin ingame menu on a vRP2 server.

**To Reproduce**
Actually none, but the following has been tried
1. Rename resource to txAdmin
2. Copy txAdmin to resource folder
3. Refresh on server console with the command `refresh`. 
4. Trying to start the resource with command `start txAdmin`.
5. Response: 

```
Couldn't find resource txAdmin.
```

The folder does not contain a manifest file, and I guess that is the reason.
However, where is that resource file located to make it possible to start the resource,
or how should the resource be install?

Another try: 

1. Placing the txAdmin folder (this repo as is) in the resource folder hence it contains a manifest file in root.
2. Deleting package.json files
3. Executing `refresh`
4. Start the resource  `start txAdmin`
5. Response:

```
[         script:yarn] Error: [yarn] error An unexpected error occurred: "https://registry.yarnpkg.com/@mui/icons-material/-/icons-material-5.11.16.tgz: ESOCKETTIMEDOUT".
[         script:yarn]
[         script:yarn] [yarn] info If you think this is a bug, please open a bug report with the information provided in "C:\\Src\\fivem\\txDataVrpDunko\\CFXDefault_E9235B.base\\resources\\txAdmin\\yarn-error.log".
[         script:yarn] info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.
[         script:yarn]
[ citizen-server-impl] Building resource txAdmin failed.
[ citizen-server-impl] Error data: yarn failed!
```

The `/tx` and `/txadmin` command is visible in game via the chat, but nothing happens when executing the commands.

**Expected behavior**
A precise description of how it is installed on a vRP2 server, or stating that it is not supported if so.

**Additional context**
Windows 10/11

**Comment by tabarra** [comment]
txAdmin is not something that you install, it already comes with fxserver.  
Please check our readme:  https://github.com/tabarra/txAdmin#running-windowslinux

**Comment by nc-jeni** [comment]
> txAdmin is not something that you install, it already comes with fxserver. Please check our readme: https://github.com/tabarra/txAdmin#running-windowslinux

The link refers to how to install the server, but the server is already installed, but txAdmin is not available.
However, I want it to be enabled in game, I don't need it for other purposes as the server is already installed.

**Comment by tabarra** [comment]
@nc-jeni You are wrong, the linked doc paragraph tells you how to enable txAdmin on all servers.  
Furthermore, please use discord.gg/txAdmin for support.
