### ISSUE TITLE
[FEATURE]: log enhancment

### ISSUE THREAD

**Issue by msa3ds** [citizenfx/txAdmin#845]
### Scope

Web

### Feature Description

as we know that logs are important part.

the only missing log for now is when any staff Revoke the ban.
![UjMPF7gRnH](https://github.com/tabarra/txAdmin/assets/120151526/3513a9e2-3f90-4476-b498-d8474bf9615a)

this would be great if done

thanks alot

**Comment by tabarra** [comment]
Uhhh... update to v6.0.1...
