### ISSUE TITLE
[BUG] Unable to control how many restart notifications.

### ISSUE THREAD

**Issue by AngryMaximus** [citizenfx/txAdmin#848]
**txAdmin/FXServer versions:**
  6.0.1

**Describe the bug**
It is said in the documentation that the restarter tab will contain the [30, 15, 10, 5, 4, 3, 2, 1,] notifacations for the restart, but its not there.

**To Reproduce**
1. Go to 'restarter'
2. only lists resource starting time limit and scheduled restarts

**Expected behavior**
to see how many notifications it would push out and change accordingly

**Screenshots**
(https://media.discordapp.net/attachments/900180032935325707/1128359281507438632/image.png)

**Additional context**
I am on the latest release.

**Comment by tabarra** [comment]
Thanks for letting me know.  
In this case, the docs were outdated, as there is no more way for you to configure the `scheduledRestart` event firings since they are now hardcoded to fire in the `[30, 15, 10, 5, 4, 3, 2, 1]` intervals.
