### ISSUE TITLE
[BUG] Broken spectate when using "next player" function

### ISSUE THREAD

**Issue by iSentrie** [citizenfx/txAdmin#849]
**txAdmin/FXServer versions:**
v6.0.2 atop FXServer 6552
  
**Describe the bug**
While spectating and trying to spectate next player using provided function with buttons, it breaks pretty fast, with following error in screenshot, that I attached.

**To Reproduce**
1. Go to spactate
2. Click spectate next player...
3. It bugs out pretty fast 1-3 attempts and...
4. See error in screenshot

**Expected behavior**

**Screenshots**
![image](https://github.com/tabarra/txAdmin/assets/29688478/6d428d1a-9829-4463-a605-e377b25957d6)

**Comment by tabarra** [comment]
I don't know what to do about this though... you cant really switch to another player while the game is trying to resolve the current player as that would complicate the code even more than it already is.

**Comment by tabarra** [comment]
Is this still an issue?

**Comment by tabarra** [comment]
Almost one year old report, no confirmations and no repro.  
I guess this just isn't a problem anymore.
