### ISSUE TITLE
[FEATURE]: Please add MFA for Admin login

### ISSUE THREAD

**Issue by TidolopNick** [citizenfx/txAdmin#852]
### Scope

Web

### Feature Description

Please add multi factor authentication with TOTP codes

### Use Case

It makes the admin panel more secure

**Comment by tabarra** [comment]
The issue with txAdmin is that many many servers will not be secure no matter what I do, specifically when regarding the files on the server which might be accessed by:
1. backdoors
2. other admins/devs
3. anyone who can write any resource to the server (vide backdoor)
4. any admin with tx perms to start runcode and check the rcon password.

Something like WebAuthN might work as it's working with asymmetric encryption, but TOTP probably not.  
So I don't know, as much as I want to add security features to txAdmin, if I were to be realistic I would recommend people use cloudflare zero trust platform to secure access to their txAdmin.  
For now, i'm closing this issue, but will revisit this in a couple of months.
