### ISSUE TITLE
[FEATURE]: Export or Event to check when first restart notification pops up

### ISSUE THREAD

**Issue by DuncanEll2** [citizenfx/txAdmin#853]
### Scope

Developer API

### Feature Description

I was wondering if it is possible for an event to check on certain restart time.

### Use Case

for instance if the 30 minute restart pops up theres an event that can trigger certain script stops. I was wanting to stop certain robbery scripts when the first restart time pops up. 

### Proposed Solution

no

**Comment by Mycroft-Studios** [comment]
this is already thing:

> For documentation on txAdmin broadcasted server events, please check our docs page:
https://github.com/tabarra/txAdmin/blob/master/docs/events.md

In future, use our discord for support :)
https://discord.gg/txadmin

**Comment by tabarra** [comment]
As Mycroft said, you can already do that.  
Just listen to the events, then stop the resource yourself.  
If you need some time that does not have fired events (like 25 mins), when the 30m fires you can just count down 5 mins and then do whatever you need to.
