### ISSUE TITLE
[BUG] Server scheduled to restart randomly w/o any scheduled restart values

### ISSUE THREAD

**Issue by tris-ten** [citizenfx/txAdmin#854]
## **txAdmin/FXServer versions:**
![image](https://github.com/tabarra/txAdmin/assets/87451201/c489f266-dac1-4c29-9864-a4f492c1577f)

## **Describe the bug**
Server is scheduling a restart even though there is no value inside scheduled restarts.

txAdmin support refering me to Tabby relating to this issue. https://discord.com/channels/577993482761928734/589106731376836608/1134165664467263619

## **To Reproduce**
1. Remove all Scheduled Restarts values
2. Wait until it just randomly restarts (it would schedule a restart randomly at a random time as shown in screenshots)

## **Expected behavior**
It shouldn't restart at all without a scheduled restart value. And if there was an added safety precaution to auto-restart a FiveM server that's been running for more than a week or so, add a config to DISABLE IT...

### Bug occuring:
![image](https://github.com/tabarra/txAdmin/assets/87451201/c2cdd1f8-5854-47a7-8aa7-29a5190a964b)
![image](https://github.com/tabarra/txAdmin/assets/87451201/da2b747b-d085-4967-b57d-026c4bf26be3)
![image](https://github.com/tabarra/txAdmin/assets/87451201/b7d8ec58-d915-414b-b6e5-6cf22d7e819b)
Context for this image: At the time of when I sent that "disabling server restarts for stress testing" message, I removed the all scheduled server restart time values so I can stress test.. and then it randomly restarted at 6pm :face_palm:
### Scheduled Restart Config
![image](https://github.com/tabarra/txAdmin/assets/87451201/b5646fd1-0d73-4d32-a591-4830bfc86102)

## **Files**
I know you'll probably ask for files so I'll upload them here for you to review. (removed tokens and sensitive values)
Exact monitor resource: [monitor.zip](https://github.com/tabarra/txAdmin/files/12186024/monitor.zip)
Exact production server start.bat: ```@echo off
"C:/posarp-fxserver-build/build//FXServer.exe" +set serverProfile "posarp-prod" +set txAdminPort (port-that-i-used) +set txAdminVerbose "true"  +set txDataPath "C:/posarp-fxserver-build/txData/production/"```
Exact development server start.bat: ```@echo off
"C:/posarp-fxserver-build/build//FXServer.exe" +set serverProfile "posarp-dev" +set txAdminPort 40130 +set txAdminVerbose "true" +set txDataPath "C:/posarp-fxserver-build/txData/development/"
pause```
**If you need anymore files, just reply and I'll provide it.**

## **Additional context**
I run two txAdmin clients due to me needing to run a dev server since there are players on my main server and I don't want to interfere with roleplays and shit. So I had to create a main-server-replica dev server so I can edit shit and just copy and paste whenever I wanna update my main server.

I've included my start .bat's in the Files section as well.

No, I did not forget I removed the scheduled restart value. I've never had a scheduled restart value. I removed it awhile ago whenever I wanted to stress-test my server and see if it'll crash after running for a week or longer, but I can't do that stress test anymore because it's restarting by itself without a scheduled restart.

**Comment by tris-ten** [comment]
I also want to note that this only started occuring whenever I updated to v6.0.2. I can easily fix this by reverting back to v6.0.1 but why do that whenever I can just find a solution for it?

**Comment by tabarra** [comment]
I did not modify anything related to the schedule restart code between v6.0.1 and v6.0.2 ([changelog](https://github.com/tabarra/txAdmin/compare/v6.0.1...v6.0.2)).  
This issue has never been reported by anyone else, and if this was a generalized issue with txAdmin I believe we would get many reports.  
  
Hypothesis:
1. you removed the scheduled times from the settings, but didn't press the save button, or pressed the save button of another settings tab.
2. when copying the server you mixed the bot tokens, and the message you are seeing is from the other server.
  
Even though your issue report is well detailed, there is nothing in there that helps me validate or solve the issue.  
Maybe you can record a video or something?!

**Comment by tris-ten** [comment]
**It happened again.**
No idea why but it appears it's occured again. I'm not awake at this time but I'll try my best to record this issue occuring whenever it happens again. If I do miss it again, I'll download the FXServer log and provide it here (along with a line # of where the forced scheduled restart occured) to see if there's something I'm missing. I haven't changed anything in the Restarter Settings in txAdmin.
![image](https://github.com/tabarra/txAdmin/assets/87451201/65fdebba-8a16-4d13-b3f2-7c0fc8aff445)

And I forgot to reply and answer your questions..
1. Both servers have the same Restarter Settings, and I know as a fact that I save them since the notification at the top of the site says that the settings has been saved.
2. I have separate bots for the servers as shown in this screenshot: 
![image](https://github.com/tabarra/txAdmin/assets/87451201/c1b1edde-0d80-4767-aae3-298c26ecc909)

**Comment by bdbdbvd** [comment]
Getting the same issue on my server ever since 6.0.2.

**Comment by tris-ten** [comment]
Just occurred 2 hours ago again. This time I got a fxserver log with it.
![Screenshot 2023-08-08 031027](https://github.com/tabarra/txAdmin/assets/87451201/43926bb5-0d43-451a-a36e-694982d1eb70)

And I was a heir away from getting it's fxserver.log...
![image](https://github.com/tabarra/txAdmin/assets/87451201/8af59197-1b80-4ae4-97a7-ae8d922ebca4)

**Comment by tabarra** [comment]
@tristencommunity join discord.gg/txAdmin and ping me rn, please

edit: Oh well, missed opportunity

**Comment by tris-ten** [comment]
@tabarra hey sorry man I went right to sleep bro I was rlly tired.. do you
still need me to ping ya?

**Comment by tabarra** [comment]
Closed as stale.
