### ISSUE TITLE
[BUG] 15 minutes cooldown video unavailable

### ISSUE THREAD

**Issue by Red-Killer** [citizenfx/txAdmin#855]
**txAdmin/FXServer versions:**
v6.0.2
  
**Describe the bug**
The YouTube embedded video isn't available so you can't watch it on site you have to go to YouTube 

**To Reproduce**
1. Attempt multiple times to log in
2. After you received the `Too many authentication attempts, enjoy your 15 minutes of cooldown.` message you will notice that the Video isn't available.

**Expected behavior**
To watch the video while I have the cooldown

**Screenshots**
![image](https://github.com/tabarra/txAdmin/assets/59504268/0bc9a45a-239d-45ff-a286-3859db65a881)

**Additional context**
On localhost it will work but not if you enter the site externally

**Comment by tabarra** [comment]
This page has been removed, so let's call it fixed :P
