### ISSUE TITLE
Update 2.0 launch error on Linux (version convar not set or in the wrong format)

### ISSUE THREAD

**Issue by djmetla** [citizenfx/txAdmin#86]
Hey i try new 2.0 update on my dev server on Linux latest stable build 1971. I configure by your readme.md and when i try start my server i obtain this error. Can you help me?

![Screenshot_22](https://user-images.githubusercontent.com/2371031/77854691-05b21980-71ec-11ea-893c-2e052b773570.png)

**Comment by tabarra** [comment]
Follow the instructions, you need to update fxserver.

**Comment by djmetla** [comment]
@tabarra well latest linux STABLE build is 1971. Ok, for me now is better 1.5.0. I need wait for new stable build. Ty, for your answer Good Luck

**Comment by Rhydium** [comment]
You can't use the stable build w/ txAdmin v2.0.0. Use 2289 or superior if you want to use it

**Comment by djmetla** [comment]
> You can't use the stable build w/ txAdmin v2.0.0. Use 2289 or superior if you want to use it

Thanks, but i cant, 1971 is still marked as stable. I cant experiment with unstable linux shits build... Maybe later ;) we are still using 1.5.0 for now
