### ISSUE TITLE
The word "activated" in NoClip in danish is spelled wrong / mistypo 

### ISSUE THREAD

**Issue by L4wlz** [citizenfx/txAdmin#864]
**txAdmin/FXServer versions:**
You can see that at the bottom of the txAdmin page, or in the terminal as soon as you start fxserver.  
  
**Describe the bug**
The Danish language for the noclip activated is spelled wrong. 
It should be spelled: **NoClip aktiveret** please see the Screenshot.

**To Reproduce**
Just have the danish language and then join the server at do /tx and activate noclip.

**Screenshots**
![image](https://github.com/tabarra/txAdmin/assets/62191448/68c83c93-5086-4cac-9027-97f811d0cf70)

**Comment by tabarra** [comment]
Thank you.  
I suppose the line "God Mode aktiveretr" is also wrong?  
I'll change it and if that was correct please let me know and I can revert it.

**Comment by L4wlz** [comment]
> Thank you. I suppose the line "God Mode aktiveretr" is also wrong? I'll change it and if that was correct please let me know and I can revert it.

You are correct that was also spelled wrong :) thanks again.

**Comment by L4wlz** [comment]
@tabarra 
There are still a bug here :) 
![image](https://github.com/tabarra/txAdmin/assets/62191448/f54608c7-bd65-4419-be59-e741460cdbb2)
you need to remove the r in aktiveret**r**

I am running the version: v6.0.2 

And the same goes for 
![image](https://github.com/tabarra/txAdmin/assets/62191448/74dc74bd-4c06-4bf6-895b-1a412a5d3829)
as you said :)

**Comment by tabarra** [comment]
This change has been made but will only be available when the next txAdmin update (v7) is released in a month or so.

**Comment by L4wlz** [comment]
> This change has been made but will only be available when the next txAdmin update (v7) is released in a month or so.

Ahh okey perfect
