### ISSUE TITLE
Unable to authenticate txAdmin with Citizen

### ISSUE THREAD

**Issue by LawyerMorty97** [citizenfx/txAdmin#88]
Hey,

I've been using this great utility for a while now and decided to upgrade to v2.0 but upon launching i've tried server times to login and link my Citizen account with txAdmin but it fails to do so.

The error I get upon trying to give rights to bind are:
"Failed to exchange code for token. Try again. If this problem persists, check terminal for more info."

In the server terminal I get:
"[txAdmin:WebServer:AddMaster] Code Exchange error: JWT not active yet, now 1585526928, nbf 1585526947"

![Error](https://puu.sh/FqDL5.png)

Any solution?

EDIT:
Server Details:
"Server profile: dev_sv
txAdmin version: 2.0.0
FXServer build: 2310"

**Comment by jooaooalmeida** [comment]
"If you are having problems with JWT or Code Exchange while logging, make sure the clock of your computer is synchronized.
If you are not trying to create the master account (first login), you can always use the login + backup password." This was taken from txAdmin discord using the command !jwt 
You can join us using the following link https://discord.gg/AR3CgB3
