### ISSUE TITLE
[FEATURE]: type here a short description

### ISSUE THREAD

**Issue by czsquizer** [citizenfx/txAdmin#881]
### Scope

Developer API

### Feature Description

Hello, it would be cool if we had the option to get ban data of certain game identifier. Mainly to check if the identifier is banned or not.

### Use Case

Some of scripts check if player is active, for example entering his house. If player does not enter his house for 14 days, it would get removed. But if he is banned for 14 days, he can not enter his house so it would get removed. If we could see whether the player is banned or not, we could mark that player as active and do not remove his stuff.

**Comment by tabarra** [comment]
Please add your idea to #442, where I'm gathering all the ideas.
