### ISSUE TITLE
[Suggestion]: Modify kick/ban messages

### ISSUE THREAD

**Issue by jxhnch** [citizenfx/txAdmin#882]
### Scope

Developer API

### Feature Description

The possibility to set the text when you restart the server, that it does not say xxxxx (requested by xxxx" but something else you can set, as well as that in case of a ban it does not say you got banned... but in a nice layout, and in case of a kick not in front [txadmin]

### Use Case

More customisation

**Comment by tabarra** [comment]
You can modify the messages using custom a custom locale.json file, but you cant make it much "prettier" since they need to be a one liner as they are also posted by the chat resource.  
If your idea is to hide the admin name, this has been suggested and it is planned.
