### ISSUE TITLE
[BUG] some names are invisible on txadmin

### ISSUE THREAD

**Issue by ghost** [citizenfx/txAdmin#883]
**txAdmin/FXServer versions:**
v6.0.2 atop FXServer 6683
  
**Describe the bug**
When i use a name that i generated on a site, the player cant be seen on the server 

**To Reproduce**
1. Just use my name "ρωøχч χ ħνħ χ θθ χ eυłeи¢ħeαтš.¢øм χ #вøииıeαυfđıeΙ"

**Screenshots**
![image](https://github.com/tabarra/txAdmin/assets/28512867/53a2324b-433d-4c3c-9851-49bb2e338ac3)
![image](https://github.com/tabarra/txAdmin/assets/28512867/3b94e7bc-bc69-487a-9113-6091972aae8c)
![image](https://github.com/tabarra/txAdmin/assets/28512867/05a984e1-d53d-45c5-aa08-82a116528832)

**Comment by Mycroft-Studios** [comment]
this is purely because gta can only show the Ascii character set

**Comment by tabarra** [comment]
Also regarding the player not showing in the txadmin UI or the "player not found" message in the modal MIGHT be because of a bug I solved and will be available in the next update.
