### ISSUE TITLE
[FEATURE]: Player Nickname

### ISSUE THREAD

**Issue by cjosephdc** [citizenfx/txAdmin#887]
### Scope

Web

### Feature Description

Ability to change / add nickname for each players in players list. 
![image](https://github.com/tabarra/txAdmin/assets/87730839/bf6db7ca-4c03-4fcd-b40b-be9347de8ddd)

**Comment by tabarra** [comment]
I feel like this is outside of txAdmin's scope.  
Would #628 kinda cover your use case for it?  
If now, what's the use case?

**Comment by cjosephdc** [comment]
In my country, game servers often require players to start their FiveM names with their group names for admin clarity on player roles. Also, there's a rule that your in-game name should match your FiveM name. This makes it tricky since you have to adjust your name each time you switch servers. Having a nickname feature would simplify things for both admins and players dealing with different server requirements.
![image](https://github.com/tabarra/txAdmin/assets/87730839/cc4230f8-8809-4f00-8ab8-0213f2831fc5)

**Comment by tabarra** [comment]
Wouldn't it be too much work to have to go through all the players editing their nicks?

**Comment by cjosephdc** [comment]
Right now, we sometimes kick players with random names just to change fivem name and match their in-game and group names. If there's a way for admins to add a nickname in the ui that gets saved in the txadmin database, it would make things much easier.

**Comment by tabarra** [comment]
After some consideration, I decided against implementing this feature.  
The use cases I could think of for this should be covered by player notes and/or the player tag system, and if it's not covered then it's probably really outside scope for txAdmin.  
  
If this was easy to implement I would think a bit more, but it is actually kinda tricky.
