### ISSUE TITLE
[BUG] QBCore Deployment mySQL 8.0.33

### ISSUE THREAD

**Issue by iRoyalDev** [citizenfx/txAdmin#890]
**txAdmin/FXServer versions:**
txAdmin version: 6.0.2
FXServer build: 7211
  
**Describe the bug**
Attempting to deploy QBCore Framework on Debian 11 VPS running mySQL Server v8.0.33, when I click 'Run Recipe' I get slapped with an error querying database about "Task Failed: BLOB, TEXT, GEOMETRY or JSON column 'users' can't have a default value"

**To Reproduce**
1. Go to txAdmin panel
2. Choose QBCore Framework for Deployment Template and go to Recipe Deployer
3. Click Next on Review Recipe
4. Enter required Input Parameters (including database information)
5. Click 'Run Recipe'
6. Error

**Expected behavior**
Expecting QBCore to inject .sql from /tmp/qbcore/

**Screenshots**
https://i.imgur.com/0Z9vW93.png - Error from console
https://i.imgur.com/rDylH7y.png - Same information from console, but from txAdmin's page on localhost.

**Comment by Mycroft-Studios** [comment]
this is not a tx issue.

QB-Core doesnt support MySQL 8.

**Comment by iRoyalDev** [comment]
Love when projects (QBCore) don't plan for backporting, guess I'll have to look into another spin up for mariadb.

Cheers Mycroft.
