### ISSUE TITLE
[BUG] Server setup download timeout too short

### ISSUE THREAD

**Issue by fluffyspace** [citizenfx/txAdmin#891]
**txAdmin/FXServer versions:**
Server profile: default
txAdmin version: 6.0.2
FXServer build: 7257 
  
**Describe the bug**
When setting up server, on "Step 3: Run Recipe" it is downloading all necessary files. I have a very slow internet connection and I always get stuck on this:

```
[18:02:09] Running [task87:download_github]... ❌
[18:04:40] Task Failed: Timeout awaiting 'request' for 150000ms
Options: 
{
  "action": "download_github",
  "dest": "./resources/[qb]/qb-interior",
  "ref": "main",
  "src": "https://github.com/qbcore-framework/qb-interior"
}
Debug/Status: ["6.0.2","Windows 11","downloading 53%"]
```

This file size (qb-interior folder from GitHub) is too big to download under 150000ms so the wizard breaks the connections and displays this error. I can't find any settings to change this timeout interval. Connection is fine, it's just downloading very slowly, meaning that it always timeouts on downloading this folder and at different precentages: 53%, 72%, etc.

**To Reproduce**
1. Have a very slow internet connection
2. Run server setup
3. Click "Popular recipes" as Deployment type
4. Select "QBCode Framework" as Template
5. Enter validation key and fill out database credentials
6. Run recipes
7. Get stuck on downloading timeout

**Expected behavior**
I expect the wizard not to time out but rather download files for as long as it takes to download them.

**Screenshots**
![image](https://github.com/tabarra/txAdmin/assets/1338761/d5c3c80a-ceb1-4351-aecb-4e7c55638e82)

**Comment by Mycroft-Studios** [comment]
this is a timeout time placed in by Github. not a txAdmin issue :)

**Comment by Mycroft-Studios** [comment]
in fact, i might be wrong here

**Comment by fluffyspace** [comment]
I don't think GitHub would break the connection if I'm downloading the repository for too long

**Comment by Mycroft-Studios** [comment]
you can edit the recipe to have a `timeoutSeconds` option on the task to increase the time :)

**Comment by fluffyspace** [comment]
```
  - action: download_github
    dest: ./resources/[qb]/qb-interior
    ref: main
    src: https://github.com/qbcore-framework/qb-interior
    timeoutSeconds: x amout of time
```

Like this? Okay, it's running, I'll reply when it finishes.

**Comment by tabarra** [comment]
I recommend you come to our discord for support: https://discord.gg/txAdmin

**Comment by fluffyspace** [comment]
`timeoutSeconds` option doesn't do anything unfortunately.

[18:48:09] Running [task87:download_github]... ❌
[18:50:39] Task Failed: Timeout awaiting 'request' for 150000ms
Options: 
{
  "action": "download_github",
  "dest": "./resources/[qb]/qb-interior",
  "ref": "main",
  "src": "https://github.com/qbcore-framework/qb-interior",
  "timeoutSeconds": 15000000
}
Debug/Status: ["6.0.2","Windows 11","downloading 53%"]

**Comment by lemanmod** [comment]
you fix it ?
