### ISSUE TITLE
[FEATURE]: Maintenance system

### ISSUE THREAD

**Issue by SADoJ-Thomas** [citizenfx/txAdmin#892]
### Scope

Web

### Feature Description

Have a maintenance system to prevent players from logging in during an update. Maybe also have a list of people authorized to connect during maintenance.

**Comment by Mycroft-Studios** [comment]
we already have this :) .
for support visit our discord: https://discord.gg/txAdmin

**Comment by tabarra** [comment]
Settings -> Player Manager -> Whitelist Mode -> Admin-only (maintenance mode).
