### ISSUE TITLE
[FEATURE]: ability to use anonymous actions.

### ISSUE THREAD

**Issue by HenningHenriksen** [citizenfx/txAdmin#893]
### Scope

Web

### Feature Description

Ability to use anonymous nickname when you need to ban people.

### Use Case

Birdie is logged in TX admin and are going to temp ban a player that bears alot of hate towards admins actions. 
In TX admin Birdie can select "admin" name as user that bans the person

### Proposed Solution

Add ability to make actions anonymous

**Comment by Scones91** [comment]
This would be really helpful!

**Comment by tabarra** [comment]
Alright, will do... hopefully in v7.1.

**Comment by jellyton255** [comment]
A config option to globally remove the reference to the punishing admin entirely for all punishment actions would be nice as well.

**Comment by tabarra** [comment]
Confirmed for v7.3.0.  
Took a while, but got it done :P  
  
For reference, after requesting feedback from a bunch of people, this is the solution I ended up with:  
![image](https://github.com/user-attachments/assets/e0cabb5b-78a6-499b-857c-30e9de0bdaec)
