### ISSUE TITLE
[FEATURE]: remove or change that admins can change their own identifier or discord id. Since it could be abused

### ISSUE THREAD

**Issue by AmersfoortRP** [citizenfx/txAdmin#898]
### Scope

Web

### Feature Description

Account settings, changing your own identifiers and discord id.

### Proposed Solution

Maybe its just better to add an extra permissions for it, or just someone with manage admin has to activate it for you that you can change it once. only when it is activated?

### Additional Info

This issue could be abused almost verry much, i hope you guys will do something with this.

**Comment by tabarra** [comment]
Although I see why server owners are worried I don't see this as a change in the security model at all.
On txAdmin v6, if you were admin you could already:
1. give someone your steam/rockstar credentials (steam/license identifiers);
2. give someone your forum or discord credentials (identifiers used by txAdmin);
3. give someone their txAdmin web password;
4. they actually wouldn't need to give their access to anyone else, they could do the malicious thing themselves.  

It is also important to remember that every ID change is logged in the system action logs.  
I'm eager to hear more feedback on the subject, but I need very strong arguments on why to revert this change, and I haven't got one yet that isn't disproved by the arguments above.  
So maybe the question to be asked is: **How to improve the monitoring of admins?**

**Comment by tabarra** [comment]
So, it has been 3 months that v7 was released.  
Do we have any new information on real cases where this feature was abused?  
I don't see people talking about it on Discord, not even the top servers.

**Comment by tabarra** [comment]
Due to lack of feedback, I will consider this as not required.
