### ISSUE TITLE
[BUG] Unable to connect to txAdmin. If you closed it, please start again and retry.

### ISSUE THREAD

**Issue by 2531454360** [citizenfx/txAdmin#908]
Unable to connect to txAdmin.
If you closed it, please start again and retry.

i from China i try use VPN But it doesn’t seem to work

![image](https://github.com/tabarra/txAdmin/assets/60476712/d854916a-babf-4fff-9af2-28bdac5a5841)

**Comment by tabarra** [comment]
For support please go to discord.gg/txAdmin

**Comment by swghsj** [comment]
Hello 我遇到了相同的问题 请问你是否解决了它
