### ISSUE TITLE
[FEATURE]: Add filters to in-game playerlist

### ISSUE THREAD

**Issue by 766974616c79** [citizenfx/txAdmin#913]
### Scope

In-Game Menu

### Feature Description

I propose adding a new player filter to the in-game menu. To sort players only in a vehicle

### Use Case

I'm a developer and administrator on a large fivem server, and often people who don't respect the server rules are in a vehicle

### Proposed Solution

Detect players in a vehicle & Have a new filter in the in-game menu

### Additional Info

I'm available to programme this!

**Comment by tabarra** [comment]
Makes sense.  
Thanks for the suggestion.

**Comment by tabarra** [comment]
I'm actually surprised this wasn't a thing, as a filters dropdown was planned since the first version of the menu.  
I've gone ahead and implemented it in 3019da70fafc471f75ae32e9db90a1bf353612f1.  
![image](https://github.com/tabarra/txAdmin/assets/1808295/85567d0a-22f3-47d8-a2f6-384f810da787)
