### ISSUE TITLE
[BUG] TxAdmin in TxAdmin 

### ISSUE THREAD

**Issue by TheHolyFire** [citizenfx/txAdmin#914]
**txAdmin/FXServer versions:**
tx: v7.0.0 | fx: b7326
  
**Describe the bug**
When getting the Error in the Resource Tab and pressing "live console" TxAdmin opens in TxAdmin

**To Reproduce**
1. Get the Resource Error in the Resource Tab
2. Click on 'Live Console'
3. TxAdmin in Txadmin
4. See Screenshot

**Expected behavior**
Change the Tab not Open a new iframe in it

**Screenshots**
![image](https://github.com/tabarra/txAdmin/assets/53409999/8defcfcb-dcfe-4c48-a3f5-9f0c35129871)

**Comment by tabarra** [comment]
This has been solved in 6062fbe8794f33f5b3b7bcec9c3bad276c4ab39e, thanks.
