### ISSUE TITLE
Bring back CPU and RAM Monitor on 7.0

### ISSUE THREAD

**Issue by Playfust** [citizenfx/txAdmin#916]
### Scope

Web

### Feature Description

Please bring back the little CPU and RAM Monitor that was on the bottom left before 7.0

**Comment by tabarra** [comment]
In txAdmin v7, the hardware stats (cpu/memory) on the sidebar has been removed for a few reasons:
- Not much space on the sidebar, specially considering some future planned features.
- It was pretty useless for the majority of servers (which use shared hosting), as those numbers are not just misleading, but commonly faked by hosting providers.
- If you have a VPS, I recommend making a grafana dashboard for the host stats, which will be way better than anything txAdmin could do.
- The host usage is still available in the system `System > Diagnostics` page.
- Host stats are usually not as useful as process usage, which can be viewed in the Diagnostics page.
**That being said, we are reviewing the feedback and might add it back.**

**Comment by Playfust** [comment]
VPS user here so it was pretty useful, especially on the dev server which has a lot less RAM and CPU than the production server, but i will check for grafana thank you for the tip

**Comment by taoletsgo** [comment]
Hopefully this monitoring feature can be added back, so that for people who have their servers on a laptop at home, if that laptop has a memory leak I can quickly know about it without having to open a remote connection or go to a weak power room to turn on the laptop screen and launch Task Manager.
