### ISSUE TITLE
my tx admin keeps saying Unable to start the server due to error(s) in your config file(s): /home/vibegames/server.cfg: Your config file does not specify a valid endpoint for fxserver to use. Please delete all endpoint_add_* lines and add the following to the start of the file: endpoint_add_tcp "0.0.0.0:30120" endpoint_add_udp "0.0.0.0:30120"

### ISSUE THREAD

**Issue by slickzyyzz** [citizenfx/txAdmin#917]
**txAdmin/FXServer versions:**
You can see that at the bottom of the txAdmin page, or in the terminal as soon as you start fxserver.  
  

**To Reproduce**

**Expected behavior**

**Screenshots**

**Additional context**
Add any other context about the problem here, like for example if it's a server issue, which OS is fxserver hosted on.

**Comment by slickzyyzz** [comment]
@tabarra

**Comment by wowjeeez** [comment]
Please add proper repro steps, and the versions. And possibly some screenshots since we are not familiar with Vibegames

**Comment by slickzyyzz** [comment]
![image](https://github.com/tabarra/txAdmin/assets/161140570/70e8383a-41ac-4ea1-adb3-a56e98ab5886)

**Comment by tabarra** [comment]
For support, use discord.gg/txAdmin
