### ISSUE TITLE
Add the ability to disable authentication methods

### ISSUE THREAD

**Issue by tydoo** [citizenfx/txAdmin#92]
To secure authentication, it would be great to be able to choose which methods are available for authentication.

Possibility to deactivate authentication:

- By password,
- By Fivem account,
- By Discord.

Thank

**Comment by tabarra** [comment]
You want to disable globally, for your user, or for an specific admin?  
If globally, then password cannot be disabled as it is the backup way to login if the social provider is not available.  
If per user, just don't have the social IDs associated, they are fully optional.

**Comment by tydoo** [comment]
To improve security, I would like the possibility of globally disabling one or more connection methods.

For example, leave only the connection by Discord and deactivate the connection by password and the connection by fivem.

**Comment by tabarra** [comment]
Fivem is always required since its the master account thing, not to mention we are preparing it for future integrations.  
I'm not sure how much secure blocking the password would be, since they are salted+hashed, and we block brute forcing of password pretty aggressively.

**Comment by tydoo** [comment]
For exemple, i hide the form manualy on the html.

But its only hidden, its not disabled.

![image](https://user-images.githubusercontent.com/50534204/78462457-7a94c000-76d2-11ea-88d2-5e8c0393e06c.png)

**Comment by tabarra** [comment]
Password logins are actually important as a backup method for when CFX's IdM is too slow, and should be safe since we have brute-force protection.  
No need to disable other methods since Admin Managers can just not link the user's cfx/discord account.
