### ISSUE TITLE
[BUG] run recipe error

### ISSUE THREAD

**Issue by DaanP12** [citizenfx/txAdmin#920]
**txAdmin/FXServer versions:**
tx v7.0.0  /  fx b7290/ptero
  

**Screenshots**
![image](https://github.com/tabarra/txAdmin/assets/102158216/5bf71312-da6a-403f-9dc2-72b6152ddbc5)

**Additional context**
Add any other context about the problem here, like for example if it's a server issue, which OS is fxserver hosted on.

**Comment by tabarra** [comment]
For support, use discord.gg/txAdmin
