### ISSUE TITLE
[BUG] Infinite loading screen on Server Log

### ISSUE THREAD

**Issue by Keyinator** [citizenfx/txAdmin#921]
**txAdmin/FXServer versions:**
tx: v7.0.0 | fx: b7521
  
**Describe the bug**
You enter an infinite state of the server log loading.

**To Reproduce**
1. Go to 'Server Log'
2. Click on 'View older' (This will put you in mode "LOG")
3. Click on 'View Newer' (This should put you in mode "LIVE" else follow step 3.1)
3.1. (If you're still not on mode "live") Click on 'View Newer'
4. Observe error

**Expected behavior**
Load server log

**Screenshots**
Demo video: https://youtu.be/dkcdR7U_mJ4

**Additional context**
This problem has been observed since pre v7.

**Comment by tabarra** [comment]
Closed by #935, thanks for the report.
