### ISSUE TITLE
[BUG] Due to an unexpected error, the panel has crashed.

### ISSUE THREAD

**Issue by itsP33t** [citizenfx/txAdmin#925]
**txAdmin/FXServer versions:**
tx: v7.0.0 | fx: b7521/Ptero
  
**Describe the bug**
When i try to do almost anything including restarting the server or clicking on my profile, the panel crashes. I can go to my console, resources, server log and anything included in the left menu (under my server name)

I have made an image, what's in the green box, can be accessed normally, what's in the red one, crashes the panel

![](https://cdn.p33t.net/VGEMFNILDL.png)

**To Reproduce**
No idea, worked normally and i haven't changed anything

**Expected behavior**
When i click on a restart button, the server restarts, not crashes. Same with the other buttons

**Screenshots**
![](https://cdn.p33t.net/ZLAZIRIUEU.png)

**Additional context**
The stacktrace from the screenshot is:
```
s$/m/<@http://65.108.237.114:1118/index-yRcFMDW6.js:593:54289
m@http://65.108.237.114:1118/index-yRcFMDW6.js:593:54233
s$@http://65.108.237.114:1118/index-yRcFMDW6.js:593:54496
Cg@http://65.108.237.114:1118/index-yRcFMDW6.js:593:54920
Z$</<@http://65.108.237.114:1118/index-yRcFMDW6.js:633:4760
zu@http://65.108.237.114:1118/index-yRcFMDW6.js:76:24283
Ns@http://65.108.237.114:1118/index-yRcFMDW6.js:76:42411
Nk@http://65.108.237.114:1118/index-yRcFMDW6.js:76:41231
xi@http://65.108.237.114:1118/index-yRcFMDW6.js:76:40278
a0@http://65.108.237.114:1118/index-yRcFMDW6.js:76:36886
pi@http://65.108.237.114:1118/index-yRcFMDW6.js:74:3279
Bt/<@http://65.108.237.114:1118/index-yRcFMDW6.js:76:34263
```

**Comment by tabarra** [comment]
This is a react error that I never seen before.  
Which means you are probably doing some DOM manipulation on your side, be that embedding txAdmin through some iframe, setting some weird http headers through some proxy, or maybe using some weird browser or browser extension.

**Comment by itsP33t** [comment]
> This is a react error that I never seen before. Which means you are probably doing some DOM manipulation on your side, be that embedding txAdmin through some iframe, setting some weird http headers through some proxy, or maybe using some weird browser or browser extension.

I'm using firefox, tried to whitelist the page from my adblocker, didn't help, tried removing react developer tools because they always did these problems with my apps, still nothing. I have no other extensions and it started happening on my other server, worked normally for few minutes and then started happening.

Last thing i did was to change the location of the server from container/txdata/.... to container/ where i moved my server, not sure how it happened on my qbcore server (the one i created this issue about) though

**Comment by tabarra** [comment]
Can you try on chrome or edge in incognito mode please?

**Comment by itsP33t** [comment]
Works fine on edge, so this is some sort of Firefox problem i guess

**Comment by tabarra** [comment]
Well, I myself develop tx on firefox, so i guess we can close this inferring it's just some issue with your host.  
But for searchability, let me write the error as test: 
```
Permission denied to access property "getAttribute"
```

**Comment by itsP33t** [comment]
Found a problem. It was because of the **Proton Pass** extension. If someone else has a problem with this, just degrade the version of the proton pass plugin to 1.14.1. Mozilla should hopefully approve the fix they made 

https://addons.mozilla.org/en-US/firefox/addon/proton-pass/versions/
