### ISSUE TITLE
[FEATURE]: Get the play time of a player

### ISSUE THREAD

**Issue by Lxk3y** [citizenfx/txAdmin#934]
### Scope

Developer API

### Feature Description

I would like the ability to get the play time of a player on the server. This feature was requested around 2 years a go as a comment in a different issue, but I don't believe it's been requested as a specific feature.

It doesn't need to be anything complex. A simple export would be fine. 

### Use Case

Being able to get the play time of a player would provide a whole host of positive use cases for players, some of which I will list below:

- Stop players duplicating logic by creating their own play time calculation scripts. What's the point when TxAdmin already does it? 
- Allow players to use the play time to do things like issue rewards or perks to players with various amount of play time.
- Allow players to fetch and store this data in their own database to use for external web panels/websites connected to their server. 

### Proposed Solution

I believe a simple server sided export allowing you to pass the player ID OR identifier into the export to receive their play time.

**Comment by tabarra** [comment]
Sorry, but this still falls under #442
