### ISSUE TITLE
[FEATURE]: Search by identifiers/actions under new players list

### ISSUE THREAD

**Issue by oofbloxwastaken** [citizenfx/txAdmin#940]
### Scope

Web, In-Game Menu

### Feature Description

With the updated players list from v7.10, you can no longer search by identifiers/actions. This was a very useful feature as it allowed for myself, my staff, and my development team to locate individuals by their discord identifiers and license keys when attempting to punish, lift punishments, or get information on the player.

### Use Case

I wanted to search a license key in the players tab but I was not able to

### Proposed Solution

Enable searching by identifiers/actions under new players list

**Comment by tabarra** [comment]
Uhhh... the option is there
![image](https://github.com/tabarra/txAdmin/assets/1808295/01afb40a-ce23-4b99-b7c1-f2e4a2492b73)

**Comment by tabarra** [comment]
Unless that's not what you meant.

**Comment by oofbloxwastaken** [comment]
whoops i am silly man
