### ISSUE TITLE
Change language

### ISSUE THREAD

**Issue by josuens** [citizenfx/txAdmin#941]
### Scope

Web

### Feature Description

It would be interesting to be able to change the language of the admin page, for example to be able to display the language in Spanish by inheriting from the language configuration, PS: If help is required to translate the texts I could help and I know that the community could also do so for other languages

I have seen in other software that the language variables are published in a repository where the same community updates them

and for example, if the language that is placed in English has not been created, that is, all the languages are created in English, and the community itself or some volunteers (I'm in) update them.

If it has not been changed, it will continue to be in English

![Captura de pantalla 2024-04-04 093716](https://github.com/tabarra/txAdmin/assets/65885730/dbefa4b2-6f43-4659-a5e2-8da69742605e)

### Use Case

Display the language in Spanish by inheriting from the language configuration

### Proposed Solution

I have seen in other software that the language variables are published in a repository where the same community updates them

### Additional Info

I could help and I know that many people start translating in native languages

**Comment by tabarra** [comment]
Unfortunately that would be unmaintainable, specially regarding the fine tuning of the error messages and it would also make support kinda impossible.  
I'm sorry but that only works for the game and discord bot, which are rarely updated and a way smaller surface to translate.
