### ISSUE TITLE
[FEATURE]: Ability to disable the electrical effects with player mode change

### ISSUE THREAD

**Issue by oofbloxwastaken** [citizenfx/txAdmin#943]
### Scope

In-Game Menu

### Feature Description

It would be very useful to have the ability to disable the electrical effects with player mode change.

### Use Case

It is very noticeable to other players when noclipping and returning to player mode.

### Proposed Solution

Ability to disable it the effects

**Comment by tabarra** [comment]
it is possible, please check the docs
