### ISSUE TITLE
[FEATURE]:  txAdmin Ban Player Event

### ISSUE THREAD

**Issue by Crafttino21** [citizenfx/txAdmin#958]
### Scope

In-Game Menu, Developer API

### Feature Description

An event like txadmin:event:banplayer which puts a selected player on the ban list. This is good for anti-cheat integrations.

Example: TriggerEvent("txadmin:event:banPlayer", source, "You have been banned for cheating", 1044463300)

### Use Case

Intigration from txAdmin into Free or Open Source Anticheats like Incarus

**Comment by tabarra** [comment]
Please check #442
