### ISSUE TITLE
[FEATURE]: Names of players currently on the server discord bot

### ISSUE THREAD

**Issue by Honcho85** [citizenfx/txAdmin#966]
### Scope

Web

### Feature Description

We have server counts that will show up with the discord bot, is there a way we could possibly get the list of players on the server also? Thanks, in advance.

### Use Case

Allowing the discord bot show players on the server, it can help let server admins keep an eye on who's actively online.

**Comment by tabarra** [comment]
This is one feature that wouldn't work well for servers with lots of players.  
And I don't even think having this in the status would be beneficial.  
So I recommend anyone that wants this to come up with their own solutions, better suited for their own needs. Sorry :(
