### ISSUE TITLE
Automatic restart after server startup issues

### ISSUE THREAD

**Issue by R0JEA** [citizenfx/txAdmin#98]
Would be very nice to see the server auto restart after, for example, such issue or some mono runtime errors (one's you get when the Keymaster is down)
![suggestion](https://user-images.githubusercontent.com/57993332/78469841-57e3c500-772d-11ea-88e1-ace04f7d61dd.png)
This is because if this happens after an automatic restart and you are not available at the time, server players simply have to wait, because the server unsuccessfully started

**Comment by R0JEA** [comment]
It could be done by reading the last lines of console for like 30 seconds after restart and comparing them to a list of blacklisted phrases (even better if they could be in the config file) and if it maches, restart the server again. Blacklisted phrases example: "GlobalError: An error occured while parsing server license key response."

**Comment by tabarra** [comment]
Doesn't this fix itself automatically?  
I believe it keeps retrying, but it just doesn't show in the screen to you.

**Comment by R0JEA** [comment]
I don't know, experienced keymaster down, experienced mono runtime crash, experencied "FXServer Crashed." And yet it would never restart. Waited like a few minutes. It just kept the way it was, didn't try to restart I guess

**Comment by tabarra** [comment]
Check txAdmin Log, in the console tab. Look for an red error about a port being busy.

**Comment by rpa3ck** [comment]
I can confirm it does retry every X minutes when keymaster is down - at least on Windows
