### ISSUE TITLE
[BUG] NUI Focus kept active after closing module

### ISSUE THREAD

**Issue by pixelift** [citizenfx/txAdmin#993]
**txAdmin/FXServer versions:**
7.3.1
  
**Describe the bug**
Upon opening the module with a specific player, lets say /tx [id] you get the popup, if you try to close it with the X in the top right corner with your mouse NUI Focus stays and so does the mouse. Upon pressing ESC NUI Focus is set back to false.

**To Reproduce**
1. Open Chat, Type in /tx [id]
2. Attempt to close the module with the X on top right
3. NUI Focus is kept active even though it should not
4. Press ESC to resume

**Screenshots**
![image](https://github.com/user-attachments/assets/baf58702-adcd-4b0e-b298-1a14c39446db)

**Comment by tabarra** [comment]
Thanks for the report.  
Definitely a bug on my code, sorry.

**Comment by tabarra** [comment]
Fixed, update to v7.3.2.
Thanks again for the report!
