### ISSUE TITLE
[BUG] The txadmin UI takes a long time to appear.

### ISSUE THREAD

**Issue by voidvalue-dev** [citizenfx/txAdmin#995]
**txAdmin/FXServer versions:**
v7.3.1  
**Describe the bug**
When opening /tx, in the TXADMIN section, it takes a while to appear. I don't know if it's something with the machine or with txadmin.

**To Reproduce**
1. Go to /tx
2. Click on txadmin
3. See error

**Expected behavior**
It should appear without having to wait so long

**Screenshots**
![image](https://github.com/user-attachments/assets/db758a57-a05e-443a-bfe0-f9bddac7673f)

**Additional context**
Node: v16.9.1
OS: Linux 5.15.0-121-generic

**Comment by Arunn2287** [comment]
![image](https://github.com/user-attachments/assets/5ed12966-5660-4e3a-9c84-02748acef637)

We have the same issue.
We tryed with the new 10367 linux atrifact, but the same problem.

**Comment by tabarra** [comment]
This has been solved in 93f8d305b94c55bb0071d5c7d7966c3aed7e3aa3.  
A new update will be available tomorrow, thanks for the report.

**Comment by tabarra** [comment]
Fixed, update to v7.3.2.
Thanks again for the report!
