### ISSUE TITLE
[FEATURE]: Split fix/spawn/boost vehicle permissisons

### ISSUE THREAD

**Issue by ChickenDipper1** [citizenfx/txAdmin#999]
### Scope

In-Game Menu

### Feature Description

It would be great if the permissions for vehicle allowed granular control over fixing, spawning, boosting a vehicle.

### Use Case

I would only ever need any admin/mod to fix a vehicle. Spawning and boosting I would like to disallow.

### Proposed Solution

Split permissions as editing tx admin lua code is a bad idea :)

**Comment by tabarra** [comment]
Please refer to #974, thanks.
